### ISSUE TITLE
Simulator not loading when opening a started Tutorial on Edge

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#1002]
To repro:
- Open a Tutorial
- Exit
- Open it again

Simulator just spins.

![Tutorial simulator](https://user-images.githubusercontent.com/22108954/56437246-82760d00-6293-11e9-88cd-322e93ce35db.png)

**Comment by pelikhan** [comment]
This reproes on all tutorials. It seems that every 2 opening, the sim does not start.

**Comment by abchatra** [comment]
@pelikhan fixed?

**Comment by pelikhan** [comment]
Looks fixed.
