### ISSUE TITLE
Importing old script

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-adafruit#1006]
Old block is not upgraded.
Import attached script, toggle to blocks.

![Importing Old Script](https://user-images.githubusercontent.com/22108954/56438326-6ffdd280-6297-11e9-9ca7-7dd951fe38e4.png)

[circuitplayground-guitar.uf2.txt](https://github.com/Microsoft/pxt-adafruit/files/3098998/circuitplayground-guitar.uf2.txt)

**Comment by abchatra** [comment]
@jwunderl can you please help fix this for tomorrow?

**Comment by jwunderl** [comment]
Looks like the upgrade rules are getting applied properly, and somehow just leaving a broken block in the xml that shouldn't be there; the original version (it seems to be from around v0.16.22) has the same contents

![Screen Shot 2019-04-25 at 2 16 00 PM](https://user-images.githubusercontent.com/5615930/56768968-abe7da80-6764-11e9-9cec-60a06d8d19a5.png)

The upgrade rule is upgrading the music block from ``music_play_note`` to ``mixer_play_note`` properly, but not removing the old ``music_play_note`` and leaving it as 

```xml
  <block type="music_play_note" disabled="true" x="232" y="0"></block>
```

Looking into where that can be fixed now
