### ISSUE TITLE
HID data not working in windows 10 adafruit app

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt-adafruit#1007]
**To Reproduce**
1. Install windows 10 adafruit makecode app
2. Load beta (go to extensions and type /@beta)
3.  Create a simple program to 
![image](https://user-images.githubusercontent.com/6107272/56438453-dedb2b80-6297-11e9-876e-9c031b70fb27.png)

Also automatic download doesn't work.

Looks like no-embed has broken HID scenario. Live app works and programs flashed from live website continue to stream data in beta. Which means software stack there is no bug.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by abchatra** [comment]
@pelikhan @jamesadevine

**Comment by pelikhan** [comment]
Fixes are in beta.

**Comment by abchatra** [comment]
Fixed
