### ISSUE TITLE
Behind the Hardware videos

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-adafruit#1024]
Hey Galen,
Can you add these videos as cards on the Home Page?
And create a "Behind the MakeCode Hardware" category for these videos too...

NeoPixels - https://youtu.be/Bo0cM2qmuAE
Speaker -  https://youtu.be/JjJ-KGwKh_4

![Thumbnail - CPX NeoPixels](https://user-images.githubusercontent.com/22108954/57163982-8895de80-6da7-11e9-9083-32d58a0c80a2.png)

![Thumbnail - CPX Speaker](https://user-images.githubusercontent.com/22108954/57163985-8cc1fc00-6da7-11e9-87e5-61066d19e896.png)

Thanks!
Jacqueline

**Comment by ganicke** [comment]
Certainly...
