### ISSUE TITLE
`Light` category has two subsections

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-adafruit#1037]
**Describe the bug**

Light section has both `neopixel` and `more` as subsections, instead of just `neopixel`. `more` has only a single block

**To Reproduce**

1. Go to beta editor
2. open light category
3. see two new categories instead of just one

**Expected behavior**

Block in more category should probably just be in light? Seems weird to me to have two categories pop up

**Screenshots**

![2019-05-23 10 08 49](https://user-images.githubusercontent.com/5615930/58272493-81794500-7d43-11e9-8e73-2885c7bacaf2.gif)

**Comment by abchatra** [comment]
Good bug

**Comment by abchatra** [comment]
@pelikhan Is this your bug? Can you fix it?

**Comment by pelikhan** [comment]
Yes that bloc needs a group on it.

**Comment by jwunderl** [comment]
Hm, that block also just doesn't compile to javascript?
