### ISSUE TITLE
Tutorial feedback

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-adafruit#1039]
No bugs, but some suggestions as I was going through the new Tutorial experience:

- Can we have the hint dialog disappear (or animate back into the Owl) after a certain amount of time?  There is no close (X) button, so it feels a bit strange that it stays open. Not clear how to close.

- Only automatically show the Hint on the first step - as a way to show the students where this is in the future.  It's distracting and duplicative when we pop it on each step.

- Add in the little shaky animation to the hint icon after a certain amount of time on a step

- Only show new information as text in the Hint.  There's no reason to duplicate the tutorial step instructions.

**Comment by abchatra** [comment]
Completed.
