### ISSUE TITLE
Tutorial header selectable in safari

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-adafruit#1040]
**Describe the bug**

On Safari, the tutorial text is selectable.

**To Reproduce**

1. Go to tutorial in safari
2. drag from top bar down over the tutorial info box
3. See error

**Expected behavior**

should not be selectable, like it is on chrome / firefox

**Screenshots**

![2019-05-23 13 41 35](https://user-images.githubusercontent.com/5615930/58285312-5a317080-7d61-11e9-9ce6-1623d09bd442.gif)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser safari

**Additional context**

not a regression

**Comment by abchatra** [comment]
Fixed
