### ISSUE TITLE
Play Tone still sounds buzzy

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-adafruit#1041]
Audio is much improved!  
Although I'm noticing that while the Play Sound melodies all sound very nice, and volume control seems correct, the Play Tone blocks still produce sound that is very "buzzy".  
Also, when I put a Play Sound block in a loop, a strange noise sounds between sounds.
https://makecode.com/_4igATVd3K7xe

**Comment by abchatra** [comment]
@mmoskal

**Comment by mmoskal** [comment]
@Jaqster does this sound less buzzy? (the weird sound between playUntilDone should be gone as well)


[binary.zip](https://github.com/microsoft/pxt-adafruit/files/3214473/binary.zip)

**Comment by Jaqster** [comment]
No, I don't hear any improvement.  These are v1.22 firmware boards I'm testing on.  Also the Simulator doesn't sound great on the computer either...

**Comment by abchatra** [comment]
Did this bug got fixed?

**Comment by mmoskal** [comment]
I don't hear the buzzy sound...

**Comment by Jaqster** [comment]
I think the Play Tone blocks now sound less buzzy than before.  But the weird sound between PlaySoundUntil Done blocks is still there, and I'm not sure the Volume is correct - 255 still sounds quiet to me.

**Comment by abchatra** [comment]
@Jaqster playTone volume is still low for default and doesn't sound good.

**Comment by abchatra** [comment]
We have new issues, but closing this old one.
