### ISSUE TITLE
Windows 10 app doesn't close tutorial on card click

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-adafruit#1043]
**Describe the bug**
Clicking anywhere in the tutorial card does not close the tutorial

**To Reproduce**
1. Open Windows 10 App
2. Open a tutorial
3. Click on the owl or the tutorial card
4. Dialog does not close

**Expected behavior**
Should close the tutorial as it does on desktop.

**Comment by abchatra** [comment]
Does this still repro?

**Comment by abchatra** [comment]
fixed
