### ISSUE TITLE
Redundant Text from Minerva in SIREN tutorial

### ISSUE THREAD

**Issue by kimprice** [microsoft/pxt-adafruit#1044]
**Describe the bug**
Minerva speech bubble has redundant text to the instructions. The speech bubble opens right when the tutorial starts.

**To Reproduce**
1. Go to https://makecode.adafruit.com/beta
2. Click on Siren tutorial.

**Expected behavior**
I expected Minerva to have an intro speech bubble like "Hi, I'm Minerva. Click me if you need help." I don't think Minerva's speech should be the same as the instructions.

**Screenshots**
![SirenTutorial-MinervaRedundant](https://user-images.githubusercontent.com/15070078/58288616-fe6ae580-7d68-11e9-8d4d-079de12728e2.PNG)

**Comment by kimprice** [comment]
This is happening for every step in this tutorial. When clicking the next step, the speech bubble automatically appears and has the exact same text as the instructions.

**Comment by abchatra** [comment]
Fixed
