### ISSUE TITLE
Simulator collapse button in portrait mode shows two arrows

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-adafruit#1046]
**Describe the bug**

in portrait mode, simulator collapse button has two arrows (downwards, and a darkened version of the landscape collapse arrow that goes away on hover

**To Reproduce**

1. Go to editor in thin browser window
2. see error in simulator collapse button

**Expected behavior**

shouldn't have second arrow

**Screenshots**

both ios and chrome

![Screen Shot 2019-05-23 at 2 30 39 PM](https://user-images.githubusercontent.com/5615930/58288189-b4353480-7d67-11e9-9ec6-d149bfa93865.png)
![Screen Shot 2019-05-23 at 2 29 58 PM](https://user-images.githubusercontent.com/5615930/58288190-b4cdcb00-7d67-11e9-8c20-7632c0735294.png)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Smartphone (please complete the following information):**
 - Device: ios simulator

**Comment by ChaseMor** [comment]
Fixed in microsoft/pxt#5630
