### ISSUE TITLE
Tutorial tooltip goes slightly off screen on thin devices

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-adafruit#1054]
**Describe the bug**

Depending on the width of the screen, the tooltip for the tutorial icon can go ooff the screen for the first step

**To Reproduce**

1. Go to tutorial in portrait mode
2. hover over (hold down on mobile) minerva icon in first step
3. See error

**Expected behavior**

should remain fully on screen

**Screenshots**

android emulator

![Screen Shot 2019-05-23 at 3 51 15 PM](https://user-images.githubusercontent.com/5615930/58291582-c8326380-7d72-11e9-94b2-ec642da5ba1a.png)

**Smartphone (please complete the following information):**
 - Device: android emulator

**Comment by abchatra** [comment]
Check with new tutorial. Likely fixed
