### ISSUE TITLE
Tutorial dialogue pops up when the workspace / toolbox is clicked in some tutorials

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-adafruit#1056]
**Describe the bug**

specifically button flipper and loudness necklace

**To Reproduce**

1. Go to button flipper tutorial in beta
2. Do not see dialogue
3. click on workspace or toolbox
4. dialogue pops up

**Expected behavior**

Should either show up immediately or only pop up when hint is pressed

**Screenshots**

![2019-05-23 17 04 54](https://user-images.githubusercontent.com/5615930/58294187-94107000-7d7d-11e9-8aa4-b192979dada5.gif)

**Comment by abchatra** [comment]
Fixed
