### ISSUE TITLE
Can open Monaco Debugger

### ISSUE THREAD

**Issue by ChaseMor** [microsoft/pxt-adafruit#1058]
**Describe the bug**
Users have the ability to enable the debugger while in JavaScript however they are unable to set breakpoints.

**To Reproduce**
1. Open a new project
2. Go to JavaScript mode
3. Click the debugger button under the simulator

**Expected Behavior**
Either users should be able to use the debugger tool in JavaScript or they shouldn't be able to enable it.

**Comment by abchatra** [comment]
I am closing experimental feature bugs here. Add this to the feedback bug on debugger
