### ISSUE TITLE
Rainbow animation is super slow

### ISSUE THREAD

**Issue by jedgarpark** [microsoft/pxt-adafruit#1063]
Seems like maybe something changed here, the "rainbow" animation pattern is very, very slow now.

Both in browser simulator and on CPX hardware.

`forever(function () {
    light.showAnimation(light.rainbowAnimation, 500)
})
`

**Comment by pelikhan** [comment]
This is a recession. Fix coming.

**Comment by abchatra** [comment]
We should take this as hotfix.

**Comment by pelikhan** [comment]
I will prepare a PR in master that we can port

**Comment by pelikhan** [comment]
https://github.com/microsoft/pxt-common-packages/commit/1858239388aac371d2a7ef3752373d2b91326216

**Comment by abchatra** [comment]
fixed
