### ISSUE TITLE
HID Mouse buttons are swapped

### ISSUE THREAD

**Issue by jedgarpark** [microsoft/pxt-adafruit#1077]
Calling the left mouse button down event causes the HID right mouse button to be "pressed" and vice versa.

**Comment by abchatra** [comment]
Hmmm.. our enum

    declare const enum MouseButton {
    //% block="right" enumval=2
    Right = 0x02,
    //% block="middle" enumval=4
    Middle = 0x04,
    //% block="left" enumval=1
    Left = 0x01,
    }
 maps codal
https://github.com/lancaster-university/codal-core/blob/9643ee76d2af1eb501f70d5d8cbc405ab7a42291/inc/drivers/HIDMouse.h#L34

**Comment by pelikhan** [comment]
I fixed it in common packages recently. Needs deployment.

**Comment by abchatra** [comment]
fixed in /beta
