### ISSUE TITLE
"Programmable Logic" doesn't have hyperlink

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-adafruit#1079]
**Describe the bug**
"Programmable Logic" doesn't have hyperlink

**Steps to reproduce the behavior**
1. Navigate to https://makecode.adafruit.com/learnsystem/logic-lab
2. Scroll down to bottom of tutorial 
3. Observe "Logic topics" 

**Expected behavior**
"Programmable Logic" should have hyperlink

**Actual behavior**
"Programmable Logic" doesn't have hyperlink
![image](https://user-images.githubusercontent.com/23466737/63247386-7e84e680-c297-11e9-9708-9c1c21c54da2.png)

**Additional info:**
1. OS: Windows (rs6)
2. Adafruit Circuit Playground Express version: 1.4.31
3. Microsoft MakeCode version: 5.20.3
4. codal-circuit-playground runtime version: v2.0.0

**Comment by ganicke** [comment]
This lesson is added in #1074
