### ISSUE TITLE
Some pictures in the tutorial "make guitar" can't be loaded

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-adafruit#1081]
**Describe the bug**
Some pictures in the tutorial "make guitar" can't be loaded

**Steps to reproduce the behavior**
1. Navigate to https://makecode.adafruit.com/projects/guitar/make
2. Scroll down to bottom of tutorial

**Expected behavior**
Picture in the tutorial should can be loaded

**Actual behavior**
Some pictures in the tutorial "make guitar" can't be loaded
![image](https://user-images.githubusercontent.com/23466737/63252085-c3157f80-c2a1-11e9-9755-2f7319279582.png)
![image](https://user-images.githubusercontent.com/23466737/63252133-da546d00-c2a1-11e9-8c9f-697e1d6b20be.png)
![image](https://user-images.githubusercontent.com/23466737/63252191-f48e4b00-c2a1-11e9-8bae-92048652c849.png)

**Additional info:**
1. OS: Windows (rs6)
2. Adafruit Circuit Playground Express version: 1.4.31
3. Microsoft MakeCode version: 5.20.3
4. codal-circuit-playground runtime version: v2.0.0

**Comment by ganicke** [comment]
I'm seeing the same problem, this works on localserve though. Hmm, images are all here:

https://github.com/microsoft/pxt-adafruit/tree/master/docs/static/cp/projects/guitar

**Comment by ganicke** [comment]
Images are serving, closing this.
