### ISSUE TITLE
Text in "Project Settings" is not clear

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-adafruit#1082]
**Describe the bug**
Text in "Project Settings" is not clear

**Steps to reproduce the behavior**
1. Navigate to https://makecode.adafruit.com/beta#editor
2. Click "More..." -> "Project Settings" and observe

**Expected behavior**
Text in "Project Settings" should be clear

**Actual behavior**
Text in "Project Settings" is not clear
![image](https://user-images.githubusercontent.com/23466737/63256104-7c2b8800-c2a9-11e9-9e7b-bd5950f14583.png)

**Additional info:**
1. OS: Windows (rs6)
2. Adafruit Circuit Playground Express version: 1.4.31
3. Microsoft MakeCode version: 5.20.3
4. codal-circuit-playground runtime version: v2.0.0

**Comment by abchatra** [comment]
We need to remove both the settings. They are not necessary here. You can always set these as text.
