### ISSUE TITLE
Tempo Doesn't Appear

### ISSUE THREAD

**Issue by dharinirajah** [microsoft/pxt-adafruit#1087]
**Describe the bug**
The tempo isn't appearing in the melody editor but shows up in the exterior block.

**To Reproduce**
1. Go to https://makecode.adafruit.com/beta#editor
2. Drag out a melody editor block
3. See error

**Expected behavior**
You should be able to see the tempo next to the play button

**Screenshots**
![image](https://user-images.githubusercontent.com/52252036/63287093-56cd5880-c26e-11e9-88c9-172062c9b584.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox

**Comment by dharinirajah** [comment]
Text appears to be white as when highlighted the number appears.
![image](https://user-images.githubusercontent.com/52252036/63287184-94ca7c80-c26e-11e9-9669-79db975acd12.png)

**Comment by jwunderl** [comment]
will be fixed by https://github.com/microsoft/pxt/pull/5826

**Comment by abchatra** [comment]
fixed
