### ISSUE TITLE
Download and serial stream doesn't work on window10 app

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-adafruit#1095]
**Describe the bug**

**To Reproduce**
1. Install MakeCode for adafruit windows 10 app
2. Create a project
3. Click on download

**Expected behavior**
Drag and drop not required to download in windows 10 app. Also console.log data doesn' seem to flow back to the app

**Screenshots**
![image](https://user-images.githubusercontent.com/6107272/63290379-31dce380-c276-11e9-915d-213e1a62ace1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - MakeCode for Adafruit app.

**Smartphone (please complete the following information):**

**Additional context**

**Comment by darzu** [comment]
might be the same issue as https://github.com/microsoft/pxt-adafruit/issues/991

**Comment by abchatra** [comment]
Fixed
