### ISSUE TITLE
Adafruit editor page can't be loaded on IE

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-adafruit#1101]
**Describe the bug**
Adafruit editor page can't be loaded on IE

**Steps to reproduce the behavior**
1. Open browser IE 
2. Input https://makecode.adafruit.com/beta#editor in address bar and observe

**Expected behavior(Chrome, Firefox & Edge)**
Adafruit editor page should can be loaded on each browser

**Actual behavior(IE)**
Adafruit editor page can't be loaded on IE
![image](https://user-images.githubusercontent.com/23466737/63329656-efde9b00-c364-11e9-86ca-f9aed08f53dd.png)

**Additional info:**
1. OS: Windows (rs6)
2. Additional info: https://makecode.adafruit.com/beta can be loaded
3. This issue only repro on IE
4. IE version: 11.295.18362.0

**Comment by abchatra** [comment]
Fixed
