### ISSUE TITLE
Block "list insert at beginning" doesn't show in tutorial example

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#1102]
**Describe the bug**
Block "list insert at beginning" doesn't show in tutorial example

**Steps to reproduce the behavior**
1. Navigate to https://makecode.adafruit.com/beta#editor
2. Click "ADVANCED" -> "ARRAYS" -> right click on block "list insert at beginning"

**Expected behavior**
Block "list insert at beginning" should show in tutorial example

**Actual behavior**
Block "list insert at beginning" doesn't show in tutorial example
![image](https://user-images.githubusercontent.com/23466737/63335436-ead31900-c36f-11e9-9640-3597132da253.png)

**Additional info:**
1. OS: Windows (rs6)
2. Adafruit Circuit Playground Express version: 1.4.32
3. Microsoft MakeCode version: 5.20.3
4. codal-circuit-playground runtime version: v2.0.0

**Comment by jwunderl** [comment]
Issue is that unshift returns the new length of the array, so the example block needs a ``let myUnusedValue = `` in front of both unshifts.

Is the return value from unshift ever used? Seems like a really wonky behavior, but is true to actual javascript I suppose.

**Comment by ganicke** [comment]
Fixed in https://github.com/microsoft/pxt/pull/5837
