### ISSUE TITLE
Add Behind the MakeCode Hardware videos to homepage

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-adafruit#1119]
Hi Galen,
I've got 4 more "Behind the Hardware" videos.  Would be great if you could add them as cards to the homepage.  Thanks!

Accelerometer - https://youtu.be/2HzNKz-QlV0
Light Sensor - https://youtu.be/9LrWQ68lO20
Infrared Sensor - https://youtu.be/0EMuaMClfos
Microphone - https://youtu.be/g5894PVYOF4

**Comment by pelikhan** [comment]
We should create an entry on the Adafruit learn center as well - listing all movies.
