### ISSUE TITLE
Beaded Necklace Project

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-adafruit#1140]
Hi Galen,
Can you help me get this new project up on Adafruit?
All the files are posted here: https://1drv.ms/u/s!Ap0HxJvtPEYdlV67Y6mXji5YL55v?e=U8HLe8
Images may need to be shrunk, also didn't know whether to make the mp4 a gif or not.
Let me know if you have any questions.
Thanks!
Jacqueline

**Comment by ganicke** [comment]
OK, currently constructing it here... https://github.com/microsoft/pxt-adafruit/pull/1143
