### ISSUE TITLE
Wonder Woman Gauntlets project

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-adafruit#1172]
Hi Galen,
Can you post a new project for this Wonder Woman partnership?
All the files for the project are posted here: https://1drv.ms/u/s!AmMIW5Hxi0RtgZoai1RFQZptH40png?e=GBdr1a
And the card for this project should be listed on the Home Page under "Costumes" category.
Thanks!
Jacqueline

**Comment by ganicke** [comment]
![image](https://user-images.githubusercontent.com/27789908/86192153-bc7ca900-bafd-11ea-8a1d-9e29d45dbb9d.png)
