### ISSUE TITLE
Update Wonder Woman project text

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-adafruit#1182]
Hi Galen.
I swear, we'll put this project to bed soon!
We got yet another round of feedback from Warner Brothers, and they want us to make some changes.
https://makecode.adafruit.com/projects/wonder-woman-gauntlets 

- [x] Project Title - switch the title of the project from "Wonder Woman Gauntlets" to "Legendary Gauntlets".  Don't worry about updating the Home Page
![image](https://user-images.githubusercontent.com/22108954/89449025-56430180-d70d-11ea-9ea2-d8ed7d02e0d6.png)

- [x] Update the header from "Wonder Woman Gauntlets" to "Legendary Gauntlets inspired by WONDER WOMAN 1984"
![image](https://user-images.githubusercontent.com/22108954/89449372-d2d5e000-d70d-11ea-90b1-d4e09789e771.png)

- [x] Add text to the bottom of the page "WONDER WOMAN 1984 TM & © DC and WBEI. RATED PG-13"
![image](https://user-images.githubusercontent.com/22108954/89449608-2d6f3c00-d70e-11ea-867b-8c4b7d969575.png)

**Comment by ganicke** [comment]
No biggie. Might as well keep the partners happy if it's easy to do.
