### ISSUE TITLE
create switch left/right event on startup

### ISSUE THREAD

**Issue by ladyada** [Microsoft/pxt-adafruit#128]
the initial slide switch location doesn't create an event so you have to switch it back and forth to generate the setting you want

**Comment by microsoftsam** [comment]
So we now have an issue which is the exact opposite and a side effect of this bug: https://github.com/Microsoft/pxt-adafruit/issues/224

**Comment by microsoftsam** [comment]
The user would expect to only trigger the event when the switch is "moved" left / right, yet now we're firing the event on start up if it happens to be in that state. 

I think what we want here is on event that only fires when it's moved left / right, and another event that fires whenever it's moved. That way it avoids having to switch the slide from one direction and back to the other if you don't care about which direction it's switched.

**Comment by microsoftsam** [comment]
@pelikhan thoughts on that fix, only issue is that the current event is called onSwitchMoved. so not sure what we'd call the new event.

**Comment by microsoftsam** [comment]
You can also check the state of the switch on start using the slide switch reporter.

**Comment by TheKitty** [comment]
Is there a slide switch report block? It isn't under INPUT

**Comment by pelikhan** [comment]
@TheKitty all the way to the bottom.
