### ISSUE TITLE
Playing audio output through A0 doesn't work unless you short the pins

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt-adafruit#138]
Playing audio through A0 doesn't work unless you short A0 -> Gnd with your fingers. 

```
input.buttonA.onEvent(ButtonEvent.Click, () => {
    music.setOutput(SoundOutputDestination.Pin)
    music.playSound(music.sounds(Sounds.PowerUp))
})
```

https://makecode.com/_bcDEPPTjXbkE

Repro: 
- Download the code above onto a circuit playground
- With two hands hold GND with one, and the A0 pin with the other. 
Sound comes out of the speaker using Analog output.

**Comment by abchatra** [comment]
Closing
