### ISSUE TITLE
'stop all sounds' inconsistent

### ISSUE THREAD

**Issue by jedgarpark** [Microsoft/pxt-adafruit#177]
Stop all sounds block seems to simulate properly, but on the CPX it stops sounds once and never lets them start again. 

![circuitplayground-screenshot__1__1024](https://cloud.githubusercontent.com/assets/2192828/26742293/02fdd2a6-4792-11e7-8e7b-c16b9287ff71.png)

**Comment by jedgarpark** [comment]
This still seems to be an issue, possibly for different reasons? Stop all sounds seems to be permanent.

**Comment by ShawnHymel** [comment]
Tested and running into the same problems as well. I'd like to have the "stop sound" feature working for a video that I'm making.
