### ISSUE TITLE
in `control.raiseEvent` the `mode` parameter is useless

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt-adafruit#219]
If you set it to `CREATE_ONLY` the event will be completely ignored, so the default mode is the only one to make sense - I propose removing it.

Comments?

CC @pelikhan @abchatra @microsoftsam

**Comment by pelikhan** [comment]
There is a use case to send the event via radio.... I think.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mmoskal** [comment]
Indeed, the function is used, but not the `mode` argument - setting it to `CREATE_ONLY` makes the call no-op.

**Comment by abchatra** [comment]
👍

**Comment by abchatra** [comment]
@mmoskal fixed?
