### ISSUE TITLE
Menu Help/Blocks is broken in beta

### ISSUE THREAD

**Issue by veler** [Microsoft/pxt-adafruit#247]
**Expected :**
When clicking on the Blocks item in the Help dropdown menu, the sidedocs should display the documentation.

**Current situation :** 
![capture](https://user-images.githubusercontent.com/3747805/28331568-72e939e2-6ba6-11e7-930a-db17d2a7dd97.PNG)

**Reproduce :** 
- Go to [https://makecode.adafruit.com/beta](https://makecode.adafruit.com/beta)
- Click on the Help menu at the top right hand corner.
- Click on Blocks.

**Comment by abchatra** [comment]
Fixed
