### ISSUE TITLE
Compilation issue under Safari in Prod and Beta.

### ISSUE THREAD

**Issue by veler** [Microsoft/pxt-adafruit#248]
**Expected :** 
On MakeCode for Adafruit on **_Safari under MacOS_**, clicking on Save or Download button must compile the code correctly.

**Current situation :** 
Clicking on Save or Download button throw a "Compilation failed, please check your code for errors".

**Reproduce :** 
- Open [https://makecode.adafruit.com/](https://makecode.adafruit.com/) or [https://makecode.adafruit.com/beta](https://makecode.adafruit.com/beta) on _**Safari for macOS**._
- Create a new project.
- Give it a name.
- Click on Save or Download button.

Same situation if we are in the JavaScript editor.

**Comment by riknoll** [comment]
The issue is an old WebKit bug where the function `btoa()` is not defined for webworkers. This doesn't affect newer versions of Safari, but we should probably add a polyfill anyways.

**Comment by riknoll** [comment]
Also, this has been around for ~8 months or so.

**Comment by pelikhan** [comment]
We should have a polyfill... maybe for another of those conversion functions.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
@riknoll can you please prioritize this, please?

**Comment by pelikhan** [comment]
Fixed.
