### ISSUE TITLE
Download Screenshot is broken under Safari for macOS

### ISSUE THREAD

**Issue by veler** [Microsoft/pxt-adafruit#249]
**Expected :** 
We must be able to download a screenshot on all the web browser.

**Current situation :** 
Under Safari, if the block editor is not empty, unable to download a screenshot of the block editor.

**Reproduce :** 
- Open [https://makecode.adafruit.com/beta](https://makecode.adafruit.com/beta) on **_Safari for macOS._**
- Create a new project.
- Right click in the block editor, Download screenshot => **This step works fine.**
- Add a Show Ring block to the editor.
- Right click in the block editor, Download screenshot => **Nothing happens.**

**Comment by samelhusseini** [comment]
No repro anymore.
