### ISSUE TITLE
There is no paste code function when right-clicking 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#256]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Switch to "{}JAVASCRIPT" and right-click to copy code 
• Right-click again to paste 

**Expected result:**
 There should have paste function
**Actual result:**
 There didn't have paste function

**Comment by abchatra** [comment]
@microsoftsam Is this a regression due to new Monaco editor?

**Comment by abchatra** [comment]
Can't fix as it is a monaco editor feature.
