### ISSUE TITLE
There is no explanation document about the using of array

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#257]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Find block "ARRAYS" and right-click to look help

**Expected result:**
 There should have some explanation document about the using of array
**Actual result:**
 There didn't have explanation document about the using of array

**Comment by ganicke** [comment]
Arrays docs are coming soon...

https://github.com/Microsoft/pxt/pull/2561
https://github.com/Microsoft/pxt/pull/2657
https://github.com/Microsoft/pxt/pull/2658
