### ISSUE TITLE
Embedded view showing blank programs

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#259]
In OneNote, projects show up blank.

<img width="1222" alt="onenote" src="https://user-images.githubusercontent.com/22108954/28430233-91fed1e0-6d34-11e7-8ddf-c70d10adc359.PNG">

Shared URL: https://makecode.adafruit.com/14995-14439-64149-03544

**Comment by abchatra** [comment]
I can't repro this.
