### ISSUE TITLE
Block "show Animation" displays differently in different browsers.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#261]
**Repro step:**
- Navigate to [https://makecode.adafruit.com/](url)
- Drag "_on start_" from Loop to content pane
- Drag "_show Animation rainbow for 500ms_" under "_LIGHT_" and put it on "_On start_"
- Switch "_rainbow_" to "_color wipe_"
- Press "_refresh_" button at the bottom of Simulator and observe the simulator

**Expected result:**
There should be a unified display standard.

**Actual result:**
IE & FireFox:
![ie_color_wipe](https://user-images.githubusercontent.com/17866936/28446418-31d93a66-6dfd-11e7-80f8-2878ca8c9837.gif)

Chrome & Edge:
![chrome_color_wipe](https://user-images.githubusercontent.com/17866936/28446396-13df9564-6dfd-11e7-8f20-a2fa6adb3ff5.gif)

**Comment by microsoftsam** [comment]
Timing issue. Won't fix
