### ISSUE TITLE
Accessibility: Ensure keyboard control of application

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#264]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Use keyboard to operate Blocks
https://www.webaccessibility.com/best_practices.php?standard_id=14
**Standard:**
When software is designed to run on a system that has a keyboard, product functions shall be executable from a keyboard where the function itself or the result of performing a function can be discerned textually.

**Expected result:**
Keyboard should have the same function as cursor mouse
**Actual result:**
![jul-27-2017 15-01-54](https://user-images.githubusercontent.com/23466737/28658536-64337914-72de-11e7-8ac8-47372477b9ad.gif)

**Comment by abchatra** [comment]
@Helen09 Thanks for this bug. We are tracking Accessibility separately as part of PXT repo. It is still work in progress. Lets us wait for that work to be completed before opening the issues. I will close this for now.
