### ISSUE TITLE
Simulator shows different color with BLOCKS and JAVASCRIPT

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt-adafruit#265]
**Repro Steps:**
•	Navigate to https://makecode.adafruit.com/ 
•	Switch to javascript and copy below code to JAVASCRIPT

loops.forever(function () {
    light.showRing(
    `red white #000000 red #123456 red red red red red`
    )
})
•	Change to blocks

**Expect Result:**
Simulator shows the same color with blocks and javascript
**Actual Result:**
![ddd](https://user-images.githubusercontent.com/23447632/28662716-ad7e42de-72ed-11e7-954d-59dc371714b2.PNG)

**Comment by microsoftsam** [comment]
We dont support hex literals in the showRing attribute.

**Comment by Mofell** [comment]
Close this issue as hex literals are not supported in showRing
