### ISSUE TITLE
Accelerometer Y-axis values mixed on Simulator vs. Hardware

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#266]
This bug was originally reported by a customer.  I didn't understand his code or what he was trying to do, but tried this quick test, and it does look like the Y-axis values are switched on the Hardware:

loops.forever(function () {
    if (input.acceleration(Dimension.X) > 800) {
        light.showRing(
        `white white white white white red red red red red`
        )
    } else if (input.acceleration(Dimension.X) < -800) {
        light.showRing(
        `red red red red red white white white white white`
        )
    } else if (input.acceleration(Dimension.Y) > 800) {
        light.showRing(
        `red red red white white white white red red red`
        )
    } else if (input.acceleration(Dimension.Y) < -800) {
        light.showRing(
        `white white red red red red red red white white`
        )
    } else {
        light.showRing(
        `white white white white white white white white white white`
        )
    }
})
light.showRing(
`white white white white white white white white white white`
)

**Comment by abchatra** [comment]
@myjeeed did you see any issues with the accelerometer values?

**Comment by abchatra** [comment]
@riknoll this is fixed right? Can you resolve this?
