### ISSUE TITLE
After clicking "Learn more", tip on the bottom-right still exists.

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#269]
**Repro Steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click link "Learn more" on the bottom-right and then back to this page

**Expect Result:**
After clicking "Learn more", this tip should disappear.
**Actual Result:**
After clicking "Learn more", this tip still exists.
![1](https://user-images.githubusercontent.com/23466737/28711521-6d0ecade-73ba-11e7-9433-dd4101dc8e60.PNG)

**Comment by abchatra** [comment]
This is by design. Unless user explicitly closes the dialog this will stay.
