### ISSUE TITLE
Wrong sequence number in project "Dandelion"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#274]
**Repro Steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click PROJECTS-->MAKE-->Dandelion-->Make

**Expect Result:**
 "Step 4: Connect the battery" should be "Step 5: Connect the battery"
**Actual Result:**
 There exists two "Step 4: " in project "Dandelion"
![1](https://user-images.githubusercontent.com/23466737/28911811-5718c9d8-7864-11e7-9075-cb3f45c8d720.gif)

**Comment by abchatra** [comment]
Fixed by https://github.com/Microsoft/pxt-adafruit/pull/276
