### ISSUE TITLE
Text "ADD PACKAGE"'s location is not proper on firefox & safari

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#275]
**Repro Steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click "ADVANCED" and observe button "+ ADD PACKAGE"
**Expect Result:**(chrome&Edge*IE)
![screen shot 2017-08-03 at 10 15 22 am](https://user-images.githubusercontent.com/23466737/28912355-7fb2ef3e-7866-11e7-9ab5-dcd86006fbd9.png)
**Actual Result:**(firefox&safari)
Text "ADD PACKAGE"'s location is not proper on firefox&safari on Mac
![screen shot 2017-08-03 at 10 12 07 am](https://user-images.githubusercontent.com/23466737/28912320-5a6186f0-7866-11e7-9a33-1353c5e059ed.png)

**Comment by Helen09** [comment]
Closed as not repro

**Comment by abchatra** [comment]
Fixed
