### ISSUE TITLE
The documentation can't be opened in a new tab 

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#277]
**Repro Steps:**
• Navigate to https://makecode.adafruit.com/beta on Edge, IE & Firefox
• Click PROJECTS-->MAKE, choose any project such as "Dandelion"
• Open the documentation in a new tab
• On Edge & IE, it will popup box and click "Allow once" or "Always allow"

**Expected result:**
The documentation can be opened in a new tab
**Actual result:**
The documentation can't be opened in a new tab

**Notes**: If you can't repro this, you can reset the project and try again
![documentation](https://user-images.githubusercontent.com/23497626/28958596-ccd69b90-78ab-11e7-9a6c-1f063669f61b.gif)

**Comment by abchatra** [comment]
This is a edge & IE issue and not specific to makecode
