### ISSUE TITLE
Start and Stop the simulator doesn't work on IE

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#278]
**Repro Steps:**
• Navigate to https://makecode.adafruit.com/beta on IE
• Drag "show string" block  under forever block
• Click "Stop the simulator" 

**Expected result:**(Edge, Chrome & firefox)
![zheng](https://user-images.githubusercontent.com/23497626/28959928-77cf37aa-78b1-11e7-939e-f35cb3139612.gif)
**Actual result:**(IE)
![bu](https://user-images.githubusercontent.com/23497626/28959931-7c947728-78b1-11e7-8112-e4d500b7b911.gif)

**Comment by abchatra** [comment]
This is an IE bug as it doesn't apply filters. Can't fix from our side.
