### ISSUE TITLE
There is no voice on IE

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#280]
Repro Steps:
• Navigate to https://makecode.adafruit.com/beta on IE
• Drag "play sound" block under forever block
![capture](https://user-images.githubusercontent.com/23497626/29167728-19dda18e-7dfe-11e7-8345-177e54ce541f.PNG)

**Expected result:**(Edge, Chrome & firefox)
There has a voice.
**Actual result**:(IE)
There is no voice.

**Comment by abchatra** [comment]
No audio context in IE.
