### ISSUE TITLE
It doesn't work when clicking "Help" label

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#281]
**Repro Steps:**
• Navigate to https://makecode.adafruit.com/beta
• Drag such as"show animation" block under forever block
• Click wheel label
![help01](https://user-images.githubusercontent.com/23497626/29168186-6bd83858-7e00-11e7-83e4-a2ba808e6cc1.PNG)
• Right click the Popup prompt, click "Help" 

**Expected result:**
It will navigate a new tab or there is no "Help" label
**Actual result:**
It doesn't work when clicking "Help"
![help](https://user-images.githubusercontent.com/23497626/29168571-02437e1e-7e02-11e7-87f5-b61a3cc3ec9a.gif)

**Comment by microsoftsam** [comment]
No help supported for Instance mutator. Won't fix.
