### ISSUE TITLE
When clicking comments firstly, it disappear quickly

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#282]
**Repro Steps:**
• Navigate to https://makecode.adafruit.com/beta
• Drag "show animation" block under forever block
• Right click block and choose "Add Comment", put some comments in it
• Close the comments, click the blank area and open the comments again

**Expected result:**
The comments open again and does not disappear
**Actual result:**
The comments disappear quickly firstly
![record](https://user-images.githubusercontent.com/23497626/29168965-15086fee-7e04-11e7-81a8-f161fe985b4f.gif)

**Comment by Helen09** [comment]
The issue still repro, but not very stable. It repros after clicking the blank area and open the comments again
![6](https://user-images.githubusercontent.com/23466737/37447933-2cc991ea-281c-11e8-8505-5dc33e0d8f76.gif)

**Comment by WendyFeng01** [comment]
Closed as not repro.
