### ISSUE TITLE
Some blocks doesn't have explanation document.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#284]
**Repro step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Click "_?_" and choose "_Reference_"
- Click "_Control_" and "_Serial_"

**Expected result:**
There should have some explanation documents about those blocks.

**Actual result:**
It doesn't have any explanation documents about those blocks.

**Comment by ganicke** [comment]
These pages are working in my check today.
