### ISSUE TITLE
Block "length of text 'abc' " & "join", which under "TEXT", doesn't have any reference document. 

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#289]
**Repro step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Click "_ADVANCE_" and choose "_TEXT_"
- Right click "_length of text 'abc'_ " or "_join_", then choose "_help_"

**Expected result:**
Those blocks should have reference documents.

**Actual result:**
It doesn't have any reference document and the page shows:
![screen shot 2017-08-17 at 5 13 08 pm](https://user-images.githubusercontent.com/17866936/29405056-68d3f574-836f-11e7-8dee-7a52fc350342.png)

**Comment by Emma-sunny** [comment]
Under "_Arrays_", there are some blocks don't have reference documents except "_list add value to end_" and "_remove last value from list_".

**Comment by ganicke** [comment]
Missing block docs added in https://github.com/Microsoft/pxt/pull/2841.
