### ISSUE TITLE
When right clicked some blocks, there are two popup message.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#290]
**Repro step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Click "_MUSIC_" and right click any block, such as "_stop all sounds_"

**Expected result:**
Compare with other browser and blocks, it should have one popup message when right click block.

**Actual result:**
![abnormally_message](https://user-images.githubusercontent.com/17866936/29405674-24eff266-8371-11e7-92f9-d0f0c69406aa.gif)

**Comment by abchatra** [comment]
@Emma-sunny I don't see two pop ups. Are you talking about search with Baidu? This is not ours, looks like browser related.
