### ISSUE TITLE
The text is not right when the mouse focus on these items "Examples" and "Buy" under "?"

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#291]
Repro step:
•Navigate to https://makecode.adafruit.com/beta
•Click "?" to open the list
•Move mouse to the items "Examples" and "Buy"

Expected result:
The text should display "Examples" and "Buy" when the mouse focus on these items

Actual result:
The text display "Reference,lessons, ..." when the mouse focus on these items "Examples" and "Buy"

![lable-text-example-buy](https://user-images.githubusercontent.com/11880996/29406264-1ccf749c-8373-11e7-96ee-800f7169d4bc.gif)

**Comment by abchatra** [comment]
Ideally we should remove these tooltips

**Comment by yanlxu** [comment]
The design has been changed
