### ISSUE TITLE
Can't use block "set item to 0" to define an Array of type string.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#292]
**Repro step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Switch "_BLOCKS_" to "_{}JAVASCRIPT_"
- Define an Array of type string, such as:
  " _let pets=["dog","cat","parrot","goldfish"]; pets.push("guinea pig");_ "
- Switch back to "_BLOCKS_"

**Expected result:**
The project should work and no error prompt.

**Actual result:**
![aug-17-2017 18-05-20](https://user-images.githubusercontent.com/17866936/29407361-bce8c430-8376-11e7-96e1-72281bfb7ee9.gif)

**Comment by abchatra** [comment]
I see array of number[] created instead of string. Error is expected here.
