### ISSUE TITLE
The tooltip doesn't display correctly on Edge

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#293]
Repro step:
•Navigate to https://makecode.adafruit.com/beta on Edge
•Make a function named "doSomething"
•Choose the block "set item to 0" under BLOCKS "VARIABLES"
•Make a variable named "doSomething" which was same with the name of function
•There is a tip about the same name

Expected result:
The tooltip should display correctly just like display on the browser Chrome

Actual result:
The tooltip doesn't display correctly on Edge

Edge:
![function-item-name-edge](https://user-images.githubusercontent.com/11880996/29407791-3899445a-8378-11e7-8ef8-6abe77ce9174.gif)

Chorme:
![function-item-name-chrome](https://user-images.githubusercontent.com/11880996/29407798-413a2ba6-8378-11e7-9176-53387c050af1.gif)

**Comment by abchatra** [comment]
fixed
