### ISSUE TITLE
Download twice 

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt-adafruit#300]
Repro steps:
•	Navigate to https://makecode.adafruit.com/beta
•	Click Download
•       Click circuitplayground-test.uf2

Expect result:
1. After clicking circuitplayground-test.uf2, it only download one time
2. There is a close button in download pup up window

Actual result:
1. It download twice
2. No close button in download pup up window
![download](https://user-images.githubusercontent.com/23447632/29703905-2e8bf95c-89aa-11e7-899a-0a19052a4edb.gif)

**Comment by abchatra** [comment]
Better download instructions required

**Comment by pelikhan** [comment]
Tracked in #442
