### ISSUE TITLE
“Fireflies” examples missed in IE

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt-adafruit#301]
**Repro steps:**
•	Navigate to https://makecode.adafruit.com/beta
•	Click “PROJECTS”->”EXAMPLES”
•	Drag examples popup to bottom

**Additional info:**
This issue only repro on IE: 11.1012.16258.0

**Expect result:**
There is example “Fireflies”
![expect](https://user-images.githubusercontent.com/23447632/29696381-37f46dc8-897b-11e7-82f9-1b08a3563b3a.PNG)

**Actual result:**
No “Fireflies” example

**Comment by abchatra** [comment]
fixed
