### ISSUE TITLE
The icons "Play" couldn't work in document "JavaScript"->"Sequencing" and "JavaScript"->"Variables"

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#302]
Repro steps:
• Navigate to https://makecode.adafruit.com/beta
• Click "JavaScript" under "?"
• Click the "Sequencing" or "Variables"
• Click the icons "Play"

Expected result:
 The vide can be loaded when click the icon "Play"
 Actual result:
 The video couldn't be loaded when click the icon "Play"

![playbutton](https://user-images.githubusercontent.com/11880996/29703924-4550b25e-89aa-11e7-93e6-c28b7ecb08b9.gif)

**Comment by microsoftsam** [comment]
These would never work, since the JS has functions that don't exist. 
Best course of action is to use an annotation for the blocks that doesn't include the sim option.
