### ISSUE TITLE
Accelerometer not working?

### ISSUE THREAD

**Issue by ladyada** [Microsoft/pxt-adafruit#304]
hiya - i never tried the accel before but its not seeming to work

i tried this sketch from a customer
https://forums.adafruit.com/viewtopic.php?f=58&t=122142&p=612590#p612590
they say the Y dim is wrong, but i actually never get anything at all, i added a blinking red LED and it seemed to 'crash'? 
unclear whats up! :)

**Comment by abchatra** [comment]
@riknoll take a peek please.

**Comment by riknoll** [comment]
@ladyada can you send me the script that crashed? The axis is definitely flipped, but I couldn't reproduce the crash.

**Comment by ladyada** [comment]
its the same one in the thread. im on firefox win 7 if that helps :/

**Comment by abchatra** [comment]
@ladyada I can't repro the crash in firefox.  I assume browser is crashing. If yes can you share the version of firefox?

We have fixed the other bug from our end.

**Comment by ladyada** [comment]
well im also getting some sort of null error but here ya go:

![null](https://user-images.githubusercontent.com/1214161/29932166-79242552-8e41-11e7-8f7f-dbc74ccabf2d.png)

https://makecode.com/_e8F4CUHDbFXR

**Comment by pelikhan** [comment]
Looks like light.statusLED is gone. Might have been removed with the refactorings.
