### ISSUE TITLE
There is no package on 'Add Package' page

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#306]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click setting button
• Click 'Add Package'

**Expected result:**
There should have some packages for user to choose 
 **Actual result:**
There is no package for user to choose unless user to search one by one
![capture1](https://user-images.githubusercontent.com/23466737/29911560-e282f644-8e60-11e7-87df-c2147d2b21e3.PNG)

**Comment by abchatra** [comment]
Yes we don't have anything today. This is a placeholder for future.
