### ISSUE TITLE
Block 'photon forward by 1' shows differently on Edge 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#308]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta on Edge
• Drag blocks as below picture

**Expected result:(on chrome, Firefox & IE)**
![2](https://user-images.githubusercontent.com/23466737/29913776-bbbaf342-8e68-11e7-9711-61047ce221b8.gif)
 
**Actual result:(on Edge)**
![1](https://user-images.githubusercontent.com/23466737/29913788-c3d5ae1e-8e68-11e7-995d-602d6bfad8e4.gif)

**Comment by abchatra** [comment]
Fixed
