### ISSUE TITLE
Failed to add package 'neoanim'

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt-adafruit#309]
Repro steps:
• Navigate to https://makecode.adafruit.com/beta
• Click “ADVANCED”->”ADD PACKAGE”->input n to search “neoanim” package
• Click “neoanim” to add package

Expect result:
 1. "neoanim" should be added
 2. When search n, it first showed "We couldn't find any packages matching 'm'", this disappear quickly, then the right package will come out

Actual result:
1. Failed to add package "neoanim"
2. It should show the right search result 
![nnn](https://user-images.githubusercontent.com/23447632/29914408-f5242462-8e6a-11e7-9f7a-5b7cde42666a.gif)

**Comment by microsoftsam** [comment]
Neoanim is not a conventional package in that it doesn't add a category, but instead adds a button under "Light" labelled "Animation Editor"
