### ISSUE TITLE
ButtonEvent.DoubleClick works in sim, but not on actual board

### ISSUE THREAD

**Issue by sheamusburns** [Microsoft/pxt-adafruit#310]
I've tested with two boards. `ButtonEvent.DoubleClick` does not register on actual board but works in sim.

**Comment by abchatra** [comment]
@sheamusburns please share the program.

**Comment by sheamusburns** [comment]
https://makecode.com/_TqaT8yf4rJUz @abchatra has a double click and a hold event. 
DoubleClick event does not run on the actual board. Hold event runs once, but not when you try again.

**Comment by abchatra** [comment]
Codal issue. We will remove it until it is fixed

**Comment by abchatra** [comment]
Fix in Codal

**Comment by abchatra** [comment]
DoubleClick is removed from the option, until codal fix is in. This bug is tracking the original issue.

**Comment by abchatra** [comment]
Closing as the bug is not in this repo and no tracktion.
