### ISSUE TITLE
ButtonEvent.Hold only working once on the actual device and doesn't work in online sim.

### ISSUE THREAD

**Issue by sheamusburns** [Microsoft/pxt-adafruit#311]
I've been testing out the ButtonEvents for the Circuit Playground Express. 

ButtonEvent.Hold only works once on the actual device. If I try it a second time, I get nothing.
I can't seem to get the ButtonEvent.Hold  to work in the sim online.

**Comment by abchatra** [comment]
@sheamusburns please share the program.

**Comment by sheamusburns** [comment]
https://makecode.com/_TqaT8yf4rJUz @abchatra has a double click and a hold event.
DoubleClick event does not run on the actual board. Hold event runs once, but not when you try again.

**Comment by sheamusburns** [comment]
Interstingly -- I was doing some more testing and found that other button events were only able to fire once if I had a `ButtonEvent.Hold` anywhere in the program.

**Comment by pelikhan** [comment]
We've removed the hold event.
