### ISSUE TITLE
"-" can't be recognized in block "parse to integer"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#312]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta 
• Drag blocks as below picture

**Expected result:**
As the help document: "-" could be recognized
![capture1](https://user-images.githubusercontent.com/23466737/30204806-5fc2b0e6-94b9-11e7-984f-6f2f6cd9eb60.PNG)

**Actual result:**
"-" could not be recognized and there is no led on
![capture2](https://user-images.githubusercontent.com/23466737/30204819-68a225e8-94b9-11e7-99e1-f1ed75e85007.PNG)

**Comment by abchatra** [comment]
-2 is not a valid input for set pixel color. Otherwise it does work.
