### ISSUE TITLE
The "pixel color at 2" color is different from "pixel color at 1" color 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#313]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta 
• Drag blocks as below picture

**Expected result:**
 The "pixel color at 2" should be same as "pixel color at 1" 

**Additional info:**
When switch "pixel color at 1" color to indigo, violet and white, the issue also repro
**Actual result:**
 The "pixel color at 2" is different from "pixel color at 1" 
![capture3](https://user-images.githubusercontent.com/23466737/30205067-5395f9a8-94ba-11e7-928e-989a10c29fd1.PNG)

**Comment by pelikhan** [comment]
This is fixed.
