### ISSUE TITLE
Simulator started automatically

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#315]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Drag block "show animation rainbow for 500 ms" and put it under block "forever"
• Stop simulator 
• 1.Switch to another page and then switch to the current page again
• Stop simulator again
• 2.Click "-" on the page top-right and restore page again

**Expected result:**
 Simulator should keep off status

**Actual result:**
1.After switching to another page, simulator started automaticlly
![1](https://user-images.githubusercontent.com/23466737/30206304-55d5d73e-94be-11e7-88e3-cd6c4f1a0bc1.gif)
2.After minimized the page, simulator started automaticlly
![sep-08-2017 18-20-40](https://user-images.githubusercontent.com/23466737/30207544-7bccd588-94c2-11e7-9ad7-5b73b4e3add8.gif)

**Comment by abchatra** [comment]
This is per design (we start on tab active)
