### ISSUE TITLE
There is no scroll bar on IE

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#316]
**Repro Steps:**
• Navigate to https://makecode.adafruit.com/beta on IE
• Click PROJECTS
• Click MAKE

**Expect Result:(Edge,Chrome,Firefox)**
![2](https://user-images.githubusercontent.com/23497626/30208850-23fa93d6-944a-11e7-8e4a-87080762825f.PNG)

**Actual Result:(IE)**
![1](https://user-images.githubusercontent.com/23497626/30208854-29f6665c-944a-11e7-8d17-9a88b778e9a2.PNG)

**Comment by abchatra** [comment]
fixed
