### ISSUE TITLE
Lights are missing on Edge

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#317]
**Repro Steps:**
• Navigate to https://makecode.adafruit.com/beta on Edge
• Drag "show string" block under on start
• Observe the simulator
**Notes:** If you can't repro this, please refresh edge browser

**Expect Result:(IE,Chrome,Firefox)**
![4](https://user-images.githubusercontent.com/23497626/30209566-a44b13c8-944d-11e7-82b3-d0e3c147e374.PNG)
**Actual Result:(Edge)**
![3](https://user-images.githubusercontent.com/23497626/30209592-b80dc89c-944d-11e7-935d-5fed2907f234.PNG)

**Comment by abchatra** [comment]
What version of edge? I can't repro this

**Comment by WendyFeng01** [comment]
@abchatra  , Edge version is 16258.1023.170905-1207.

**Comment by abchatra** [comment]
This looks like a bug in Edge rather than us. Works fine with the older versions of the edge for us.

**Comment by abchatra** [comment]
Resolving and please reopen if you still see this.
