### ISSUE TITLE
Issue: light.pixelColor() returns different value than light.colors(Color.Color)

### ISSUE THREAD

**Issue by sheamusburns** [Microsoft/pxt-adafruit#319]
Here's a program that demonstrates the bug:

https://makecode.com/_8XpUTq2vw6hk

This program works with testColor set to black, but if you change the value to any other color, the program breaks.

**Comment by sheamusburns** [comment]
Testing this further -- does anyone know what kind of object `light.pixels.pixelColor(pixelLoc)` returns? I can test it against another instance of itself and get a `true` or `false`, but when I test it against an instance of `light.rgb(r, g, b)` or `light.colors(Colors.Color)` for example, I cant get it to return true.

**Comment by sheamusburns** [comment]
<img width="615" alt="untitled_-_adafruit_circuit_playground_express" src="https://user-images.githubusercontent.com/8462408/30776393-94bd57b8-a073-11e7-9197-b4ad9bc5d39e.png">

<img width="299" alt="untitled_-_adafruit_circuit_playground_express_2" src="https://user-images.githubusercontent.com/8462408/30776409-e9ec811e-a073-11e7-9828-08ca19dc0279.png">

<img width="326" alt="data__1__csv 2" src="https://user-images.githubusercontent.com/8462408/30776410-ebb32ade-a073-11e7-8a97-a01dce7c5fdd.png">

**Comment by pelikhan** [comment]
This is due to the brightness being applied to the color when stored in the strip (rather than keeping it separate). So by default, the brightness is low, which means the color stored is dimmer and dimmer -- and eventually falls to zero.

**Comment by sheamusburns** [comment]
...So it would seem @pelikhan `light.pixels.pixelColor(pixel)` should return the original color with the brightness levels stripped out of the value.

**Comment by sheamusburns** [comment]
Understandable. I guess if the intention of the Circuit Playground Express is to create a device and software package that is meant for projects but also for _teaching folks how to code_ (Adafruit markets this as an educational tool), a behavior this counterintuitive is confusing for learners. I know firsthand trying to teach high schoolers who are running into this. They're _setting_ the light with one color, but getting a different color value back when _getting_ the color.   

Even though it's an expected behavior of the original library, this has been throwing my students off (and other users trying to build with it: see: https://github.com/Microsoft/pxt-adafruit/issues/313 ).

**Comment by microsoftsam** [comment]
@pelikhan looking into this with delayed brightness: https://github.com/Microsoft/pxt-common-packages/pull/131

**Comment by pelikhan** [comment]
This issue should be fixed in https://makecode.adafruit.com/beta . We apply brightness when sending the buffer to the strip so we keep the original color at hand.

**Comment by sheamusburns** [comment]
Brilliant!![bitmoji](https://render.bitstrips.com/v2/cpanel/10152648-346363153_12-s4-v1.png?transparent=1&palette=1&width=246)

The kids will love that they can now build projects that check a color based on the value of one of the on-board pixels! Thanks @microsoftsam & @pelikhan. 

That said, I noticed in the beta site (which I've not been using actually) that `light.pixels.pixelColor()` is available in typescript mode, but no longer has a block for the on-board lights. Will that be available? 

S

**Comment by pelikhan** [comment]
it will be back as  a top level block: light.pixelColor()

Meanwhile it is under the light > External category

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pelikhan** [comment]
pixelColor is fixed. Light.pixels tracked in https://github.com/Microsoft/pxt-adafruit/issues/398
