### ISSUE TITLE
Customer issue - does temperature work?

### ISSUE THREAD

**Issue by ladyada** [Microsoft/pxt-adafruit#320]
see https://forums.adafruit.com/posting.php?mode=reply&f=48&t=121247

can someone verify thermistor is supported? :)

**Comment by abchatra** [comment]
![image](https://user-images.githubusercontent.com/6107272/30505480-c908d77c-9a29-11e7-9569-2d891166a8e3.png)
Here is the program from the report.

**Comment by abchatra** [comment]
@caitlin-hennessy Can you take a look when you have some spare time?

**Comment by pelikhan** [comment]
Joe has a fix in CODAL so we need to pick up the latest bits. Michal is working on a "cocal-locked" system to target specific commits.

**Comment by mmoskal** [comment]
Does this build solve the issue? https://makecode.adafruit.com/app/2665d3163fd760e170a4b5eee9f552694921916a-b211c34609

I'm not sure I'm getting the exact reading - it shows 26, but it's maybe 24 here

**Comment by microsoftsam** [comment]
Verified that the last build fixes the issue. I got it down to 13 degrees C. 

![img_1645](https://user-images.githubusercontent.com/16690124/32068475-4f827f2a-ba3b-11e7-83be-a09d51c32bef.jpg)

**Comment by microsoftsam** [comment]
Closing.
