### ISSUE TITLE
Music field editor issues

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt-adafruit#322]
![screen shot 2017-09-12 at 1 56 15 pm](https://user-images.githubusercontent.com/16690124/30347852-43188a18-97c2-11e7-85f0-4f3bdad4502f.png)
![screen shot 2017-09-12 at 1 55 58 pm](https://user-images.githubusercontent.com/16690124/30347851-43093ca2-97c2-11e7-8982-ac2a234148e0.png)

**Comment by abchatra** [comment]
Fixed
