### ISSUE TITLE
Disabled blocks may be a bit too transparent

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#325]
I could see kids easily losing these blocks on a crowded workspace
<img width="225" alt="transparency" src="https://user-images.githubusercontent.com/22108954/30358533-eaba1d5e-97f9-11e7-8c6f-6a04fb5ad105.PNG">

**Comment by microsoftsam** [comment]
How about this: 
<img width="693" alt="screen shot 2017-10-16 at 2 18 10 pm" src="https://user-images.githubusercontent.com/16690124/31635774-e61e0f24-b27c-11e7-83da-83b49520f3b3.png">


(fill-opacity: .9)

It is currently .5

**Comment by Jaqster** [comment]
Yes!

**Comment by pelikhan** [comment]
LGTM.

**Comment by abchatra** [comment]
Fixed
