### ISSUE TITLE
After adding elements to array, failed to put block “create Array with ” into "set item to".

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#327]
**Repro step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Drag “_create array with_” into content panel and use “_+_” to add elements to the array
- Then put the "_create array with'+'_" into "_set item to_"

**Expected result:**
After adding elements, block "_create array with_ '+'" should be put “_set item to_” successfully.
![screen shot 2017-09-14 at 3 07 17 pm](https://user-images.githubusercontent.com/17866936/30416413-a05608ca-995e-11e7-9fa7-c5ab577bc4a1.png)

**Actual result:**
After add elements to array, failed to put the block to ‘set item to’. Details as follows:
![fb9ab067-22e4-455f-90fc-e68192cbd416](https://user-images.githubusercontent.com/17866936/30470372-0b9efd9e-9a27-11e7-9814-36d18fd991e3.gif)

**Comment by jedgarpark** [comment]
Hi, I've found a workaround for this by setting the array in JavaScript and then converting back to blocks. Any work on a fix?

**Comment by Emma-sunny** [comment]
Closed as fixed
