### ISSUE TITLE
Error messages overlap the blocks

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#330]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/beta 
2. Drag block “Create array with +'(the parameters is decimal )’” to “forever”
3. Drag block "Create NeoPixel strip" to array
**Expected result:**
Error message can be read clearly
**Actual result:**
Error message overlap the blocks
![capture](https://user-images.githubusercontent.com/23497626/30427192-81cb1a3e-9914-11e7-8e20-87f1907b56e6.PNG)

**Comment by microsoftsam** [comment]
Possible a zindex issue as well. Fixed in beta
