### ISSUE TITLE
The example of "serialwrite buffer" out of border

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#334]
# Issue 1
**Repro step:**
Navigate to https://makecode.addafruit.com/beta on Edge & IE
Drag block “serialwrite buffer” to “forever”
Right click and choose "Help"

**Expected result:(Chrome & Firefox)**
![buffer02](https://user-images.githubusercontent.com/23497626/30468811-e058c436-99b2-11e7-9036-011492211cc2.PNG)
**Actual result:(Edge & IE)**
![bufferieedge](https://user-images.githubusercontent.com/23497626/30468914-7c3d9246-99b3-11e7-986c-e08fdd8698e6.PNG)

# Issue 2
**Repro step:**
Navigate to https://makecode.adafruit.com/beta on Edge & IE
Expand ADVANCED and click ARRAYS
Observe the blocks
**Expected result:(Chrome & Firefox)**
![chrome](https://user-images.githubusercontent.com/23497626/30469327-3f96e8d6-99b5-11e7-9c63-8bed2a118a8e.PNG)

**Actual result:(Edge & IE)**
![edge](https://user-images.githubusercontent.com/23497626/30469335-45c97fca-99b5-11e7-900e-2a6ec97ad89b.PNG)

**Comment by pelikhan** [comment]
Does this issue still repro when custom fonts are disabled?

**Comment by Helen09** [comment]
What's the custom fonts?

**Comment by pelikhan** [comment]
Unrelated to fonts. Sam has a fix coming up.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
