### ISSUE TITLE
When dragging block, it disappeared.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#339]
**Repro step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Drag block "_show animation rainbow for 500 ms_" to content panel
- Then try to put it into "forever"

**Additional information:**
- Only repro on IE[11.1032.16258.0]
- Under “LIGHT”, it seems blocks have the same issue, such as: "_set brightness_", "_photo set pen color_",...

**Expected result:**
![03af1a50-9995-4f99-a4ad-340c1546c34d](https://user-images.githubusercontent.com/17866936/30685779-9b6687c4-9ee8-11e7-96a6-9b8e592fce23.gif)

**Actual result:**
The block disappeared.
![9f6373e4-d1d5-4f06-83af-4e42c45fa8e8](https://user-images.githubusercontent.com/17866936/30686259-414a5e6c-9eea-11e7-89c8-b335a2c201bd.gif)

**Comment by Mofell** [comment]
This issue still repro on latest IE11: 11.1020.17001.0

**Comment by abchatra** [comment]
Moving to blockly @microsoftsam
