### ISSUE TITLE
There are no package names which could be referred to add these packages

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#340]
Repro step:
•Navigate to https://makecode.adafruit.com/beta
•Click the "ADD PACKAGE" in the editor
•Click "?" to get document of package information
•Input "Packages" in the InputBox of "Search"

Expected result:
There are package names which the users could refer to when they want to add these packages
Actual result:
There are no package names which the users could refer to when they want to add these packages

![package information](https://user-images.githubusercontent.com/11880996/30687449-de904472-9eed-11e7-954f-2526aaf2624b.gif)

**Comment by abchatra** [comment]
Search should be done inside the initial pop up.
