### ISSUE TITLE
Firefiles report error: "Referenced file missing: main.blocks"

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#341]
**Repro step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Click "_PROJECT_" then choose "_EXAMPLES_"
- Select “_Firefiles_”

**Additional information:**
Only repro on IE[11.1032.16258.0]

**Expected result:**
![5f352a20-1aad-4a53-95a1-2f7e2b2e7676](https://user-images.githubusercontent.com/17866936/30687290-67a7f9b8-9eed-11e7-82a3-fa4911e109ab.gif)

**Actual result:**
![df7cba9a-60fa-4357-a10d-bbefd1912a86](https://user-images.githubusercontent.com/17866936/30687516-0c32da7a-9eee-11e7-9d3c-042da38d0fd5.gif)

**Comment by Mofell** [comment]
This issue doesn't repro because page layout changed
