### ISSUE TITLE
The process of searching didn't keep staying in the documentation page

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#342]
Repro step:
•Navigate to https://makecode.adafruit.com/reference
•Input "Magic Wand" in the InputBox of "Search"

Expected result:
The process of searching should keep staying in the documentation page
Actual result:
The process of searching didn't keep staying in the documentation page, it jumped to the "Bing" page

![document search](https://user-images.githubusercontent.com/11880996/30688262-4031a67e-9ef0-11e7-8b3e-c061498999e0.gif)

**Comment by abchatra** [comment]
This by design today
