### ISSUE TITLE
The project could not be loaded in the second time

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#343]
Repro step:
•Navigate to https://makecode.adafruit.com/beta
•Click "PROJECTS"->"EXAMPLES"->"Animation shaker" to open this project
•Click "PROJECTS"->"EXAMPLES"->"Animation shaker" to open this project again

Expected result:
The project could be loaded just like the first time
Actual result:
The project could not be loaded just like the first time, it said that "referenced file missing: main.blocks"

![project example](https://user-images.githubusercontent.com/11880996/30688583-2845f9b0-9ef1-11e7-9129-453901157ea4.gif)

**Comment by abchatra** [comment]
Fixed
