### ISSUE TITLE
After clicking "Getting Started", the page keep the status of "starting tutorial..."

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#344]
**Repro step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Click "_Getting Started_"

**Expected result:**
After clicking "Getting Started", the page should be load successfully.

**Actual result:**
![b5b19e17-8c39-4b36-8976-6aceb870c02a](https://user-images.githubusercontent.com/17866936/30688903-f93b9f98-9ef1-11e7-94c3-afa574422e85.gif)

**Comment by willingc** [comment]
Is this still an issue? Possibly was due to latency.

The tutorial does load using Safari and Chrome browsers after a short delay. Perhaps make the motion of the flower greater as it is currently very subtle and it doesn't appear as if anything is happening.

cc/ @ptorrone

**Comment by abchatra** [comment]
This is fixed

**Comment by willingc** [comment]
Thanks @abchatra for the update.
