### ISSUE TITLE
No examples when click Examples

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt-adafruit#353]
Repro Steps:
•	Navigate to https://makecode.adafruit.com/beta#projects:Examples Or follow below steps:
•	Navigate to https://makecode.adafruit.com/beta 
•	Click New Project
•	Click “?”->Examples

Expected result:
There are some examples.

Actual result:
No examples

**Comment by microsoftsam** [comment]
I've removed it from this target. We no longer have different tabs in the projects view.
