### ISSUE TITLE
 The scrollbar of document doesn't work

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#354]
Repro step:
•Navigate to https://makecode.adafruit.com/beta
•Click the "Blocks" under "?"
•Click the scrollbar of document

Expected result:
 The scrollbar of document work
Actual result:
 The scrollbar of document doesn't work, the scrollbar of content panel work

![document](https://user-images.githubusercontent.com/11880996/31428366-17a99736-ae9d-11e7-8a6b-65af08cb92cb.gif)

**Comment by microsoftsam** [comment]
Fixed in beta.
