### ISSUE TITLE
The action of deleting was not correct

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#356]
Repro step:
•Navigate to https://makecode.adafruit.com/beta
•Drag the block "on button A click" to the content panel
•Drag the block "on button A click" to the space of simulator when drag it to "Delete"
•Drag the block at the space of simulator until it can't be moved to left any more at some place

Expected result:
 The block was deleted when free the click button of mouse
 Actual result:
 The block was not deleted when free the click button of mouse, and it moved with the mouse

![deletemovewithmouse](https://user-images.githubusercontent.com/11880996/31429517-dac8de90-aea0-11e7-8369-66507f5837bf.gif)

**Comment by abchatra** [comment]
I can't repro anymore
