### ISSUE TITLE
After clicking "adafruit", page can't navigate to goal page directly

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#373]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta 
• Click "+" to new a project named "test"
• Click "adafruit" on the top-left corner to page https://www.adafruit.com/product/3333

**Expected result:(Edge,chrome,Safari)**
After clicking "adafruit", page should navigate to https://www.adafruit.com/product/3333 directly
**Actual result:**
After clicking "adafruit", page navigates to home page firstly
![1](https://user-images.githubusercontent.com/23466737/31652450-b7732abc-b351-11e7-87ed-05f95bbb6fc9.gif)

**Comment by abchatra** [comment]
This is by design

**Comment by abchatra** [comment]
@microsoftsam this is expected right?
