### ISSUE TITLE
Latest Firmware download page on adafruit.com?

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-adafruit#376]
Is it possible to link from the uber CPX article (https://learn.adafruit.com/adafruit-circuit-playground-express/adafruit2-uf2-bootloader-details) into a downloadable firmware binary download?

**Comment by ladyada** [comment]
sure. what link?

**Comment by pelikhan** [comment]
We cannot host the compiled bootloader. Maybe you can have it on the CPX guide in the bootloader section?

**Comment by ladyada** [comment]
to clarify - you mean not the update.uf2, the .bin for jlink-ing?

**Comment by pelikhan** [comment]
The .uf2 file that upgrades the bootloader would be best since updating the bootloader is as easy as a drag and drop.

**Comment by ladyada** [comment]
its already there? 
https://learn.adafruit.com/adafruit-circuit-playground-express/adafruit2-uf2-bootloader-details#updating-the-bootloader

**Comment by pelikhan** [comment]
Oh snap, sorry for wasting your time. I'll cross link that page from our docs.

**Comment by pelikhan** [comment]
@ganicke let's find good spots in the docs to link to https://learn.adafruit.com/adafruit-circuit-playground-express/adafruit2-uf2-bootloader-details#updating-the-bootloader which contains a download to the bootloader.

**Comment by ladyada** [comment]
lol its all good - theres *a lot* of docs :)

**Comment by ganicke** [comment]
We have _/device/usb_ but there's no **Device** in the summary tree. Add Device page with links to these kinds of things?

**Comment by ganicke** [comment]
Links added in #427.
