### ISSUE TITLE
program terminates on CPX, not in simulator

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt-adafruit#377]
https://makecode.com/_M4rekjMRX7eL

It appears that the write to serial fails, terminating the program:

```
loops.forever(function () {
    light.pixels.photonForward(1)
    serial.writeValue("x", input.acceleration(Dimension.X))
})

```

Without the writing to serial, it works fine.

**Comment by mmoskal** [comment]
Can't repro. Are you running from localhost or from the website?

**Comment by mmoskal** [comment]
It's possible (though not very likely) this is the timing bug, since it affects USB. On the device that fails, try running it from a USB battery or charger. @tballmsft

**Comment by tballmsft** [comment]
Running from windows app..

**Comment by pelikhan** [comment]
If this is. Windows app issue, it is P2.

**Comment by mmoskal** [comment]
Please try running from a well charger please (on the same board where it hangs). Also try a different board.

**Comment by tballmsft** [comment]
Will do.

**Comment by tballmsft** [comment]
It was specific to the board - works with another board. What should I do with the buggy board?

**Comment by mmoskal** [comment]
The board requires a patch in the clock init code as discussed with Joe. Once he implements it, it should work. Mark it and keep for testing of the fix.

**Comment by tballmsft** [comment]
Got it. Thanks.

**Comment by finneyj** [comment]
This patch is now applied to master of ```codal-circuit-playground```

Can we pull this through to a beta site or localhost testing for this board, to confirm this addresses the issue?

**Comment by tballmsft** [comment]
I'll test it.

**Comment by mmoskal** [comment]
@tballmsft - it's somewhat non-trivial, since we're on an older branch of CPX Codal and also because there's another clock init code in the USB code. I would like to sort out the build system first, before we move forward with codal on CPX.

**Comment by mmoskal** [comment]
@tballmsft can you test now?

I still see there's two copies of the clock init code - I thought there was only one left.

**Comment by mmoskal** [comment]
In CPX v1.2.6 I've removed duplicate code.

 I've uploaded web app using it at https://makecode.adafruit.com/app/492c798798098523aba829daa5424f812bcf7adc-3f85280ecf

Please test both this and the main site.

**Comment by pelikhan** [comment]
@mmoskal is that fix in master already?

**Comment by pelikhan** [comment]
@tballmsft could you test again with your board? You can go to https://makecode.adafruit.com/beta to pick up the fix. Closing for now.
