### ISSUE TITLE
Buttons/logos missed on IE

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt-adafruit#378]
**Repro Step:**
•	Navigate to https://makecode.adafruit.com/beta on IE
•	Click “New Project”

**Additional Info:**
This issue only repro on IE11
IE11: 11.1024.17001.0

**Expect Result:**
Buttons/logos should display as Edge, Chrome and Firefox
![anotherhomepage](https://user-images.githubusercontent.com/23447632/31698772-ca757b88-b3f1-11e7-8428-b8ae3e3c1501.PNG)
![logochrome](https://user-images.githubusercontent.com/23447632/31698775-cfff4b4c-b3f1-11e7-8cdc-7b2caf13f246.PNG)

**Actual Result:**
Buttons/logos are missing on IE
![iehomepage](https://user-images.githubusercontent.com/23447632/31698790-de9b64d8-b3f1-11e7-84a2-58f14419c7a2.PNG)
![ie1](https://user-images.githubusercontent.com/23447632/31698795-e1e8aa4c-b3f1-11e7-93b9-91cd30fe107e.PNG)

**Comment by microsoftsam** [comment]
I dont' repro.. Please try latest.

**Comment by Mofell** [comment]
Can't repro on latest build, so close this bug.
