### ISSUE TITLE
NeoPixel docs need to be moved in a subfolder

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-adafruit#387]
We have clashing docs between the instance methods in NeoPixel class and the namespace level functions added for Adafruit.

**Comment by ganicke** [comment]
Ok, I'll adjust the doc level for the class methods and add a createStrip topic. I can build it now after your last commits.

**Comment by ganicke** [comment]
Addressed in:

https://github.com/Microsoft/pxt-common-packages/pull/138
https://github.com/Microsoft/pxt-adafruit/pull/409
