### ISSUE TITLE
Monaco toolbox shows two functions for the same method

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt-adafruit#390]
This is due to two issues: 
- Firstly, subcategories are not supported in the toolbox
- Secondly, the OO stuff is assuming that the API uses defaultInstance and needs to be fixed to support something like a placeholder field and append the function to it in its snippet. eg: 
dragging out a graph block from the external category should insert something like: strip.graph(0,0) with strip highlighted 

<img width="609" alt="screen shot 2017-10-19 at 2 59 09 pm" src="https://user-images.githubusercontent.com/16690124/31796436-62278eac-b4de-11e7-90e3-bbd0ac85d449.png">

**Comment by pelikhan** [comment]
@abchatra  I don't think this is blocking the release.

**Comment by microsoftsam** [comment]
Fixed.
