### ISSUE TITLE
Cable received api are confusing 

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt-adafruit#392]
![image](https://user-images.githubusercontent.com/6107272/31797299-6b9ccdfe-b4e2-11e7-83e0-40a7e36f8a57.png)

As it is very hard to set them up, can we move them to its own package? And keep just the infrared here.
Also remove the cog where here?

**Comment by abchatra** [comment]
And the help for these talk nothing about how to set them up. They talk about infrared.

**Comment by pelikhan** [comment]
Removed.

**Comment by pelikhan** [comment]
Cog wheel still there. Cable removed

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-common-packages/pull/144

**Comment by pelikhan** [comment]
There are 2 bugs that would require PXT support, probably from @riknoll 

- [ ] unable to specify that at least one argument (num) should be expanded in the block. I added ``?`` to the 2 other arguments to hint that those are optional. Maybe we can use that info.
- [ ] deleting any variable from the signature deletes the entire event.

**Comment by riknoll** [comment]
For the first point, there is a way to do that! Add `toolboxVariableArgs="1"`. If you want to have more copies of the block in the toolbox, separate them with semicolons (`toolboxVariableArgs="0;1;2"`).

For the second one, yeah I need to fix that.

**Comment by abchatra** [comment]
I do think @microsoftsam and I discussed this and we should give one option to receive number as there no way to send two numbers using the send api.

**Comment by pelikhan** [comment]
Right.... There is a typescript API to send an array of numbers but it's not surfaced in blocks.

**Comment by abchatra** [comment]
Makes sense. Lets just remove the gear wheel and keep one option to receive number.

**Comment by pelikhan** [comment]
There is no gearwheel anymore.
