### ISSUE TITLE
serial.writeNumber doesn't separate numbers in the serial editor

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt-adafruit#407]
A simple: 
```
serial.writeNumber(20) 
```

brings up the serial editor but doesn't log numbers on the graph properly. 
It shows 2020202020 as a single value. 

<img width="1283" alt="screen shot 2017-10-21 at 5 22 47 pm" src="https://user-images.githubusercontent.com/16690124/31856935-80f401ce-b684-11e7-812b-d1b309dd40a3.png">

**Comment by pelikhan** [comment]
By design, write number does not add a new line

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by microsoftsam** [comment]
Maybe it should show up in the console instead?

**Comment by caitlin-hennessy** [comment]
Yes.  I think we should only graph data that comes in as a key:value pair, e.g., "x:123".  Everything else should go to the console.

**Comment by pelikhan** [comment]
led.plotBarGraph sends a number per line to the console and automatically gets charted. We should not chart numbers are 256 characters long.

**Comment by caitlin-hennessy** [comment]
If we take that approach, we should define a global serial buffer length and use it throughout the code.  Right now the local serve, windows app, and simulator can each have a different buffer length - we can't count on its being 256.

Seems unnecessary to me though.

**Comment by pelikhan** [comment]
A sequence of numbers is the simplest way to generate a data stream. We support that kind of output in led.plotBarGraph and light.graph. In this case, we need to detect that the number is obviously too big (e.g. too many significant digits to be representable in JavaScript) and ignore it.

**Comment by abchatra** [comment]
@caitlin-hennessy what is the right outcome for this bug?

**Comment by pelikhan** [comment]
Follow up bug: https://github.com/Microsoft/pxt-adafruit/issues/469
