### ISSUE TITLE
Two icons overlap on "High Contrast On" model

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#417]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta 
• Go to setting and click "High Contrast On"
• Observe the icon on top left of page

**Expected result:**
Two icons shouldn't overlap
**Actual result:**
Two icons overlap
![1](https://user-images.githubusercontent.com/23466737/31930424-424b3cf8-b8d2-11e7-8fe6-c901346d32ce.gif)

**Comment by abchatra** [comment]
We are going to remove beta label soon. I am going to close this as won't fix.
