### ISSUE TITLE
Project new name can't be saved successfully

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#418]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Go to setting and choose "Project Setting"
• Delete project name and click save button
• Type a new name for the project in bottom text box of main page and click save button

**Expected result:**
New name could be saved successfully
**Actual result:**
New name can't be saved and save button 
![2](https://user-images.githubusercontent.com/23466737/31930723-523666dc-b8d3-11e7-9bd1-e8db901037b9.gif)

**Comment by microsoftsam** [comment]
Fixed.
