### ISSUE TITLE
After changing project name, blocks can't be edited on content pane

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#419]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Go to setting and choose "Project Setting"
• Delete project name and click save button
• Type a new name for the project in project setting box and click save button

**Expected result:**
After changing project name, blocks can be edited and blocks show in editor
**Actual result:**
After changing project name, blocks can't be edited on content pane
![3](https://user-images.githubusercontent.com/23466737/31936858-5cbeb61a-b8e5-11e7-9265-6fef052dc88c.gif)

**Comment by microsoftsam** [comment]
Issue here is that we're allowing you to edit a project name to null.

**Comment by Helen09** [comment]
New name was edited and simulator can show, but blocks on content pane still can't be edited

**Comment by abchatra** [comment]
Hang seems bad for users.
