### ISSUE TITLE
The page can not be displayed completely

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#420]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click ">" or "<" under 'Tutorials'

**Expected result:**
There are some items under Tutorials and can click '<' or '>'
**Actual result:**
![item11](https://user-images.githubusercontent.com/23497626/31937552-795f0876-b87a-11e7-9dd7-c61ee7d3dd32.gif)

**Comment by microsoftsam** [comment]
Please try again, can't repro on beta.

**Comment by WendyFeng01** [comment]
Not repro on the latest build, closed it.
