### ISSUE TITLE
Default is Pin instead of Button

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt-adafruit#425]
![image](https://user-images.githubusercontent.com/6107272/32006875-c5cf093a-b95c-11e7-94db-dbbe02ae2779.png)

**Comment by microsoftsam** [comment]
@mmoskal I think this is a sideeffect of your recent pin mapping changes, any idea how we can fix this?

**Comment by pelikhan** [comment]
Try reordering the sources in pxt.json. I think they get loaded in order. Otherwise, we'll probably need some weights to sort those definitions.

**Comment by microsoftsam** [comment]
Reordering the device decl in devices.d.ts fixed the issue: 
https://github.com/Microsoft/pxt-adafruit/pull/428
