### ISSUE TITLE
Getting started (Magic wand) tutorials doesn't start

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt-adafruit#434]
Due to https://github.com/Microsoft/pxt/issues/3379

The upgrade logic is interfering with the tutorial load. When the tutorial engine tried to decompile all the tutorial code, and then it upgrades (it tried to re-write a file that doesn't exist, since the decompilation is only for the engine to figure out what blocks to show).

**Comment by pelikhan** [comment]
The master version is using "tutorials/getting-started" so we can safely fix magic wand

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-adafruit/pull/458
