### ISSUE TITLE
Details view must be scrolled in view when made visible

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-adafruit#445]
If the carousel is near the bottom, the user won't see that a details view has been opened.
![scrollinview](https://user-images.githubusercontent.com/4175913/32310780-150766f0-bf52-11e7-9346-c1d119f6a506.gif)

**Comment by pelikhan** [comment]
Th

**Comment by microsoftsam** [comment]
Yeah it is, I plan to add that in the future.

**Comment by microsoftsam** [comment]
Dropping priority and removing release tag as this is now fixed. 
Keep this open to track animating feature.
