### ISSUE TITLE
Toolbox groups are not right aligned in RTL languages

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-adafruit#463]

**Comment by microsoftsam** [comment]
Good catch

**Comment by pelikhan** [comment]
The language switched (blocks-js) also does not resize. It spills in Korean.

**Comment by pelikhan** [comment]
Overall, looks pretty good though!

**Comment by microsoftsam** [comment]
Blockly isssue: https://github.com/google/blockly/issues/1208

**Comment by microsoftsam** [comment]
Non of the Blockly Flyout buttons labels or groups are properly aligned in Blockly. This is an upstream issue and has now been fixed in Google/blockly. Will integrate the next time we pull from mainline.

**Comment by samelhusseini** [comment]
This is fixed.
