### ISSUE TITLE
Rename Serial to Console. 

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt-adafruit#469]
Category : Console
Serial write line:  log
Serial write value:   log value

Change 
"Show data" to "Show console"

**Comment by pelikhan** [comment]
We should integrate those APIs to the micro:bit as well to stay consistent.

**Comment by abchatra** [comment]
Microbit we can't change the API for v0.

**Comment by pelikhan** [comment]
We can add APIs.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
@caitlin-hennessy 

Still couple of issues pending

1. Monaco toolbox still shows serial but with no blocks.
![image](https://user-images.githubusercontent.com/6107272/32558412-85ce2f3e-c459-11e7-9cf2-8aecd9967c50.png)

2. Show data is not changed to show console.

3. Can console.log can take numbers as well?

**Comment by pelikhan** [comment]
(3) This would require special compiler support. We don't support any or unions in the block signature.

**Comment by abchatra** [comment]
Lets move that to a separate issue.

**Comment by pelikhan** [comment]
@microsoftsam does the Monaco toolbox handle empty namespaces?

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/pull/3438

**Comment by microsoftsam** [comment]
If it doesn't it should. It should pretty much match the behaviour of the Blocks toolbox. If at any point that's not the case, it's a bug.

**Comment by pelikhan** [comment]
It's a namespace where all the blocks are "blocksHidden". This needs to be fixed in the pxt-monaco I guess.

**Comment by pelikhan** [comment]
@abchatra I don't think this is a ship blocker.

**Comment by microsoftsam** [comment]
The monaco toolbox lives in PXT. so should be an easy fix.

**Comment by pelikhan** [comment]
@microsoftsam toolbox issue is yours. I'll look into those missing project pages

**Comment by microsoftsam** [comment]
Sounds good

**Comment by pelikhan** [comment]
Fix coming in next bump.
