### ISSUE TITLE
Missing Toolbox scrollbar in Chrome

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#471]
I see it in Edge, but not in Chrome.
<img width="235" alt="toolboxscrollbar" src="https://user-images.githubusercontent.com/22108954/32397304-779d450a-c0a6-11e7-8d65-e456aae92e4b.PNG">

**Comment by microsoftsam** [comment]
Do you need it there? Doesn't look like you need a scrollbar here? as in there's room to show all the items without a scrollbar

**Comment by microsoftsam** [comment]
I misunderstood. I think you meant the Flyout scrollbar, and you're right it wasn't showing as it had the same colour as the Flyout. Fixed in https://github.com/Microsoft/pxt-adafruit/pull/486
