### ISSUE TITLE
IR seems to be broken with latest version

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt-adafruit#472]
Wrote a simple program that sends an index to another CP in a forever loop (once a second) and had the other plot the received number. Barely any of the packets made it through.

**Comment by mmoskal** [comment]
Does the same program works with *the same devices* with the previous version?

**Comment by mmoskal** [comment]
Also try running both from battery as usb clock will alter behavior now

**Comment by riknoll** [comment]
Yep, program works fine with non-beta editor. I also tested on battery and got the same results.

**Comment by riknoll** [comment]
Program for reference: https://makecode.com/_hqTC9yChRU5M

**Comment by mmoskal** [comment]
I did some digging and it seems with the new clock init, the timers on battery are awfully wrong (10% variance).

I have new message encoding code, will PR soon.

**Comment by microsoftsam** [comment]
@mmoskal what's the status of this. I tried with v1.2.8 and it's still very temperamental.

**Comment by mmoskal** [comment]
There is a branch in common packages, basically ready to go, might just need disabling debug. Still it has issues locking up the board after a while while sending , but so does the current one.

**Comment by mmoskal** [comment]
Should be fixed in https://github.com/Microsoft/pxt-common-packages/pull/169

**Comment by pelikhan** [comment]
Tested as fixed on hardware (USB & battery)
