### ISSUE TITLE
Bring back the Show Animation for duration block

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#477]
Hot Potato project requires this.  We can push it down to the More subcategory, but this project is already out and Boys and Girls Clubs are using it.

**Comment by pelikhan** [comment]
Can you attach a shared script url of that project?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by microsoftsam** [comment]
I agree with @Jaqster. There's value in being able to control how long an animation is played for. I don't think it needs to be at the bottom of the list, but certainly warrants another block right next to show Animation frame that has a duration field with it. 

https://makecode.com/_9YHF3ydqib6b

**Comment by microsoftsam** [comment]
and it also makes the upgrade experience better, the previous showAnimation block can be converted into that block, and all new blocks that only show an animation with a duration can use the new block.

**Comment by pelikhan** [comment]
Let’s bring back the duration in blocks then.

**Comment by pelikhan** [comment]
@Jaqster if we bring back the duration, is that enough?

**Comment by pelikhan** [comment]
How about this? 
![image](https://user-images.githubusercontent.com/4175913/32399950-bcff9330-c0b7-11e7-9f1d-8c49192153e3.png)

**Comment by pelikhan** [comment]
See https://github.com/Microsoft/pxt-adafruit/tree/showanimationduration

**Comment by pelikhan** [comment]
I think we could have a special time picker for animations with better values. In particular, 0 == automatic.

**Comment by microsoftsam** [comment]
I think we should split into two blocks. 
There's value in having a simple show animation block with no duration

**Comment by pelikhan** [comment]
In this case, the hot potato tutorial is using the instance version -- not the namespace level version. I'm not even sure this fixes the issue.

**Comment by pelikhan** [comment]
We could be smart about continuing the previous animation instead of restarting.

**Comment by microsoftsam** [comment]
That would be auto upgraded to light.showAnimation, so not really an issue.

**Comment by pelikhan** [comment]
I’d like to keep a single “show Anomatikn” block

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pelikhan** [comment]
Having 2 is just going to be confusing.

**Comment by pelikhan** [comment]
Now we do have the icon instead of the text....

**Comment by Jaqster** [comment]
I like the simplicity of having the Show Animation at the top, like the Show Ring.  Having an extra duration field adds complexity and is one more thing you have to explain and set a value for.

I think it's fine to have multiple blocks doing different things with an animation (frame, duration).

**Comment by pelikhan** [comment]
Under the hood, the show animation block still has a duration for app compat. So I don’t think we can have 2 blocks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-adafruit/pull/480

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-common-packages/pull/163

**Comment by pelikhan** [comment]
It's back.
