### ISSUE TITLE
There are lot of projects don't have the code instruction.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#485]
**Repro step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Choose project "_Watch Timer_" under "_Costumes_" and show the projects instructions
- Click "_code_" which displayed on the page's right

**Expected Result:**
It should have the concrete detail after clicking "_code_".

**Actual Result:**
There are lots of project have same issue that the content of code not exist, such as Magic Wand, Reaction!...
![bb644132-dd2f-4946-96f5-aec15cef2650](https://user-images.githubusercontent.com/17866936/32488227-e9528898-c3e6-11e7-84af-a0b7a030d303.gif)

**Comment by abchatra** [comment]
I guess this will be in release when we release the docs a s well.

**Comment by microsoftsam** [comment]
We have switched to showing instructions in a new tab. This behaviour is now outdated.
