### ISSUE TITLE
Minerva avatar is 500kb, needs to be shrinked

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-adafruit#489]
LESS was complaining that it did not fit into a data-uri.

**Comment by pelikhan** [comment]
Tutorial avatar is 1Mb too.

**Comment by microsoftsam** [comment]
We should be using a PNG.

**Comment by microsoftsam** [comment]
It shouldn't be including the SVG, but the downsized PNG.

**Comment by microsoftsam** [comment]
I'll look into what's going on.

**Comment by pelikhan** [comment]
Maybe it was before I merged your PR.

**Comment by microsoftsam** [comment]
Most likely, as I'm not repro'ing

**Comment by microsoftsam** [comment]
Closing. let me know if you repro with latest everything
