### ISSUE TITLE
Can not choose other languages

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#492]
**Repro step:**

- Navigate to https://makecode.adafruit.com/beta
- Click Setting->Language
- Select language

**Expected Result:**
There are some languages can be chose
**Actual Result:**
There is only one language and show twice
![english](https://user-images.githubusercontent.com/23497626/32538433-f9536d4c-c4a0-11e7-95f9-bf98e5d05fe8.PNG)

**Comment by abchatra** [comment]
We don't have translation for other languages yet. We will close this bug now. This will get populated as we have more languages.
