### ISSUE TITLE
Editor hangs when you leave any dialog open in the background.

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt-adafruit#493]
Leave in this state for 5 minutes by visiting a different tab
![image](https://user-images.githubusercontent.com/6107272/32557961-8127a984-c458-11e7-9d48-86ed89b8a09c.png)

Then click on discard blocks. Editor hangs. 

![image](https://user-images.githubusercontent.com/6107272/32557843-2892f1a2-c458-11e7-88fb-91283765bf91.png)

**Comment by abchatra** [comment]
I should note I am not reliably able to repro.

**Comment by abchatra** [comment]
Happened in edge as well

**Comment by abchatra** [comment]
@pelikhan - FYI

**Comment by microsoftsam** [comment]
Interesting, I'll keep an eye out for a repro.

**Comment by microsoftsam** [comment]
Note, the modal you see there is the semantic JS modal, not the react one. Could be useful info.

**Comment by microsoftsam** [comment]
I don't think this has anything to do with the modal. It's more likely it has something to do with console logging. 
When you leave it for 5 minutes, you're writing a bunch of stuff to your buffer. I would start the investigation there.

**Comment by microsoftsam** [comment]
@caitlin-hennessy FYI

**Comment by microsoftsam** [comment]
In other words, I think this would repro if you leave the editor for 5+ minutes regardless on what screen you're on. Just a hunch

**Comment by abchatra** [comment]
It is not console.log related.  There was a error in the program hence the can't decompile dialog

**Comment by abchatra** [comment]
I am not able to repro now. I will keep an eye.

**Comment by microsoftsam** [comment]
I’ll keep my eyes peeled

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/32562803-6f86935a-c464-11e7-8621-bf0a37bc1ea0.png)

**Comment by caitlin-hennessy** [comment]
I will take a look too.

**Comment by abchatra** [comment]
Can't repro. Closing
