### ISSUE TITLE
Console color is too dark for dark themed monaco editor

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-adafruit#494]
![image](https://user-images.githubusercontent.com/4175913/32561737-dbb57878-c461-11e7-91e6-f0aa25e95cea.png)

Sam, don't we automatically adjust luminosity of category colors?

**Comment by microsoftsam** [comment]
We lighten the colors automatically. But the console color is very dark.. Should just go with a different colour

**Comment by microsoftsam** [comment]
Why are we not using the same serial colour?

**Comment by microsoftsam** [comment]
<img width="311" alt="screen shot 2017-11-08 at 8 52 30 am" src="https://user-images.githubusercontent.com/16690124/32561884-32182756-c462-11e7-96e6-86cb89c6dbf2.png">

**Comment by pelikhan** [comment]
Very strange, they should be the same color.

**Comment by microsoftsam** [comment]
Yeah the color is updated in adafruit in ns.ts I'll PR.
