### ISSUE TITLE
blocks background in tutorial should have a background

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-adafruit#496]
The block workspace background is stransparent.
![image](https://user-images.githubusercontent.com/4175913/32566453-d6c1445e-c46c-11e7-9958-c38b8bbc805e.png)

**Comment by microsoftsam** [comment]
That was deliberate to keep the "chalkboard" feeling. What background would you give it?

**Comment by pelikhan** [comment]
Same color as editor since we know contrast is good there.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by microsoftsam** [comment]
ok

**Comment by pelikhan** [comment]
Unrelated but the howl is not really visible in tutorial tab
![image](https://user-images.githubusercontent.com/4175913/32566761-d12ae238-c46d-11e7-931a-309442ee185b.png)

**Comment by pelikhan** [comment]
black and black, it's cute though

**Comment by microsoftsam** [comment]
Yeah maybe we adjust and get rid of it's body, and just keep the eyes :)

**Comment by pelikhan** [comment]
Maybe white border around him

**Comment by microsoftsam** [comment]
or her?

**Comment by pelikhan** [comment]
it

**Comment by pelikhan** [comment]
what's her name?

**Comment by microsoftsam** [comment]
Minerva

**Comment by pelikhan** [comment]
Sounds like a she. It's a she then.

**Comment by samelhusseini** [comment]
Closing as contrast only important for text and block color (which is already the case in this design). Also in the docs we don't render a background, why here? 

Reopen if you feel strongly about this.
