### ISSUE TITLE
Show Console button text is not aligned

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt-adafruit#508]
![image](https://user-images.githubusercontent.com/6107272/32675376-9a8be610-c60b-11e7-9d14-085ecd1b1d2a.png)

Couple of issues:
Left margins are not aligned.
Show Console  seems  Device text doesn't seem to be at the same horizontal axis.

**Comment by cait1inhennessy** [comment]
This was fixed a while ago.
