### ISSUE TITLE
Colors for blocks are wrong in siren tutorial

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt-adafruit#509]
Authoring bug

**Comment by riknoll** [comment]
Also, description should not say firefighter

**Comment by ganicke** [comment]
Firefighter removed in https://github.com/Microsoft/pxt-adafruit/commit/a250bf14111715bbf6e771790ce4f766bf0109b2

@microsoftsam colors for block tagging isn't matching. Same deal as in #542
