### ISSUE TITLE
Feature Request: Description Area in Published Project

### ISSUE THREAD

**Issue by sheamusburns** [Microsoft/pxt-adafruit#518]
Description Area in the view of a published makecode project (see image for proposed concept mockup
![proposedmakecodedescriptionfeature](https://user-images.githubusercontent.com/8462408/32763029-1c429f52-c8cb-11e7-91ce-bff106638ad4.png)

//PS I don't know if this is the place to put feature requests -- if there's another spot in the project, please let me know and I'll put it there. Thanks.

**Comment by abchatra** [comment]
We added comments to the workspace and it is a great way to add the description which stays with the project even when you open the editor.
![image](https://user-images.githubusercontent.com/6107272/41069287-180d7f74-69a2-11e8-96a0-72d86c021c24.png)
I closing this bug in favour of that.

**Comment by abchatra** [comment]
Right click and add comment.
