### ISSUE TITLE
After setting variable "strip", block "'strip' show animation for 500ms" doesn't work.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#519]
**Repro Step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Create new project as following picture:
![capture](https://user-images.githubusercontent.com/17866936/32768622-800e7172-c953-11e7-8489-65a10cee68d1.PNG)

**Expected Result:**
1. The block " _'strip' show animatin for 500ms_" and its help instruction should correspond.
2. After setting variable "_strip_", the block should work.

**Actual result:**
![b982f06c-36ac-4bd7-807c-7766acb8f548](https://user-images.githubusercontent.com/17866936/32768704-f42009a4-c953-11e7-8348-f2e69695adc8.gif)

**Comment by abchatra** [comment]
Strip corresponds to an external strip and if you need animation you need to use on-board strip. Something like below

![image](https://user-images.githubusercontent.com/6107272/32788412-fc897ff8-c90d-11e7-9fa4-10cdd30a0586.png)
