### ISSUE TITLE
IE doesn't have "Animation Editor" under "Light".

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#520]
**Repro Step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Create new project
- Click "_Light_" and choose "_Animation Editor_"

**Expected Result:**
1. IE should have the "Animation Editor" like other browsers.
![animations](https://user-images.githubusercontent.com/17866936/32769288-3fac2964-c956-11e7-8163-19ee467d8fec.PNG)
2. After open the "_Animation Editor_", The link "Paint your NeoPixel animations" should work.[**Firefox & Chrome**]
3. After click Link "_Open this in a new window_", it should open a page in new window.[**Edge**]

**Actual Result:**
IE:
![animationchange](https://user-images.githubusercontent.com/17866936/32770040-1e4ed476-c959-11e7-94a1-67d45d984e32.png)

Edge:
![17e60c97-8f95-4f75-9d20-29ead7d7d566](https://user-images.githubusercontent.com/17866936/32769721-0700a494-c958-11e7-85ca-0913eac86e50.gif)

FireFox & Chrome:
![dcb2c57f-c945-4aad-b129-447a9c0b4d08](https://user-images.githubusercontent.com/17866936/32769893-8ec2a440-c958-11e7-8ad9-95d13803930f.gif)

**Comment by pelikhan** [comment]
Animation Editor is injected by pxt-neoanim.

**Comment by microsoftsam** [comment]
As Peli mentioned you would need to add the pxt-neoanim package.
