### ISSUE TITLE
The inputBox was black when the inputBox was full of comment on Chrome

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#521]
Repro steps:
• Navigate to https://makecode.adafruit.com/beta
• Drag block "show animation" to "forever" and right click the block to "add comment"
• Input the comment in the inputBox of "comment"

Expected result:
1.The scroll bar can be dragged
2.The inputBox can be displayed

Actual result:
1.The scroll bar can not be dragged on **safari**
2.The inputBox was black when the inputBox was full of comment on **Chrome**

![chrome-comment](https://user-images.githubusercontent.com/11880996/32770455-bb1b5602-c95a-11e7-8dfc-2101f367df4c.gif)

**Comment by abchatra** [comment]
We at overhauling the comment system. This bug needs to wait.

**Comment by yanlxu** [comment]
close as p3 priority
