### ISSUE TITLE
The color of icons are not right

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#522]
Repro steps:
• Navigate to https://makecode.adafruit.com/beta
• Click "Setting" -> "High Constrast on"
• Switch between icons "BLOCKS" and "{}JAVASCRIPT"

Expected result:
 The color of icons are right

Actual result:
 The color of icons are not right unless to click other icons or blank place

![icon-color-high constrast on](https://user-images.githubusercontent.com/11880996/32770520-f95d4ff6-c95a-11e7-9389-73fbec9efb00.gif)

**Comment by microsoftsam** [comment]
High contrast conflict between active state and highlighted state.

**Comment by yanlxu** [comment]
close as p3 priority
