### ISSUE TITLE
"Console simulator" disappears from the content panel.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#523]
**Repro step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Switch "_BLOCKS_" to " _{}JAVASCRIPT_" and copy the following code into content panel:
   _for (let i = 0; i <= 10; i++) {
    light.graph(i * 10, 100)
    loops.pause(500)
   }_
- Switch back to "_BLOCKS_"
- Click "_Show console Simulator_", wait a minute and pause the "Console Simulator"

**Expected Result:**
After paused the simulator, the console should not disappear from the content panel. And when started the simulator again, it should work as usual.

**Actual result:**
![fc95fd07-4619-4617-9411-93b9b060f192](https://user-images.githubusercontent.com/17866936/32770606-38f3c500-c95b-11e7-83c6-67b97d309af9.gif)

**Comment by cait1inhennessy** [comment]
The disappearing problem will be fixed by https://github.com/Microsoft/pxt/pull/3482.

However, the second part isn't a bug - hitting the record button in the console window doesn't restart the simulator.  Maybe we should think about how to make this more clear in our design.
