### ISSUE TITLE
Clap Lights Tutorial

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#530]
Step 2 - shouldn't we call this block "set all pixels"?  
Right now we refer to it as "set all"

**Comment by Jaqster** [comment]
Also in Step 2, should add "Set the brightness to the maximum of 255"

**Comment by Jaqster** [comment]
![claplights](https://user-images.githubusercontent.com/22108954/32921375-48843814-cae2-11e7-8101-ece011144f77.jpg)

![claplights](https://user-images.githubusercontent.com/22108954/32921541-d6594bfc-cae2-11e7-96ea-b59cacb72a16.gif)

**Comment by ganicke** [comment]
Fixed in #533

**Comment by pelikhan** [comment]
You need to rotate and crop the gif

**Comment by pelikhan** [comment]
We should add a fake “clap” on the gif since there is no sound

**Comment by ganicke** [comment]
Yea, I did the rotate and crop in the PR.

**Comment by pelikhan** [comment]
My bad!!!!!
