### ISSUE TITLE
Loudness Necklace Tutorial

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#531]
Add photo + gif
![loudnessnecklace](https://user-images.githubusercontent.com/22108954/32922253-31ba70c2-cae6-11e7-893d-c57298f212a9.jpg)

![loudnessnecklace](https://user-images.githubusercontent.com/22108954/32922258-35afe162-cae6-11e7-8dfe-db87769555fa.gif)

**Comment by ganicke** [comment]
Images added in #533
