### ISSUE TITLE
Night Light Tutorial

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#532]
Add image and gif
![nightlight](https://user-images.githubusercontent.com/22108954/32922776-d0728cc0-cae8-11e7-82b1-28c5a3d4658c.jpg)

![nightlight](https://user-images.githubusercontent.com/22108954/32922781-d706f7a6-cae8-11e7-8d09-2c982b980975.gif)

**Comment by ganicke** [comment]
Images added #533
