### ISSUE TITLE
Button Flipper Tutorial changes

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#534]
[ ] Step 2 - Replace "We’ll use this to run some code based on a random value." with "We'll use this to determine if you win or lose based on a random number."

[ ] Step 3 - Can we make the Math blocks in the Tutorial instructions more purple?  Right now they look closer to the Input pink color...
![image](https://user-images.githubusercontent.com/22108954/32963422-bae623de-cb84-11e7-97b5-a12a247d7052.png)

[ ] Step 3 - Can we break this step into 2 steps: 3) "Drag the less than comparison block < into the If true Then block replacing 'true' condition"  4) "From the Math toolbox drawer, drag a Pick Random block and place it into the first slot of the Less than comparison block <.  In the second slot, type 5.  This will pick a random number between 0 and 10.  If it's less than 5 it will run the code in the first part of our If block, and if it's 5 or greater it will run the code in the else part of our If block."

[ ] Step 4 - We need to stay consistent in the Instructions and Solution - you tell them to use Show Animation blocks in the instructions, but the Hint uses a Set all Pixels block.  Let's stick to Show Animation for the solution.  Also, you spell it "lose", not "loose".
![image](https://user-images.githubusercontent.com/22108954/32964015-a287f69e-cb86-11e7-8771-c40a5f17a081.png)

[ ] Step 5 - Can we make the Download pink?  To match the button?

[ ] Step 5 - Replace "Press A to try your luck…"  with "Press button A to try your luck..."

[ ] Add image
![buttonflipper](https://user-images.githubusercontent.com/22108954/32966079-80d5b1c4-cb8d-11e7-8cc0-1f10c4dcbc05.jpg)

**Comment by ganicke** [comment]
Tutorial changes made in #542. Deferring to @microsoftsam for the block css color changes.
