### ISSUE TITLE
Firefox: Simulator Buttons non-responsive

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#539]
In Firefox, the Simulator highlights the A and B buttons but doesn't register the click.  I've noticed if I tab to the button and hit enter, it does register the click.
Reported by Michael Taylor, and I've confirmed the repro.

**Comment by abchatra** [comment]
Can't repro on 57.0 (64-bit) Firefox. What is your version?

**Comment by abchatra** [comment]
fixed
