### ISSUE TITLE
The home page didn't display correctly on Edge

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#543]
Repro steps:
• Navigate to https://makecode.adafruit.com/beta on Edge
• Click "New Project" to edit the project
• Click the icon "adafruit"

Expected result:
The home page displayed correctly

Actual result:
The home page didn't display correctly

![content](https://user-images.githubusercontent.com/11880996/33118664-6f008fbe-cfa7-11e7-9bed-3b705c51f7e2.gif)

**Comment by abchatra** [comment]
I can repro this easily. Looks like where there is a scroll bar in the toolbox, it always shows up in the home page.

**Comment by microsoftsam** [comment]
What version of Edge are you running?

**Comment by abchatra** [comment]
Edge 16 repo for me

**Comment by yanlxu** [comment]
not repro now, close it
