### ISSUE TITLE
 There is only "English" could be selected in the Language

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#544]
Repro steps:
• Navigate to https://makecode.adafruit.com/beta
• Click "Setting" -> "Language"

 Expected result:
 There are many language to select
Actual result:
 There is only "English" could be selected

![language](https://user-images.githubusercontent.com/11880996/33119830-2682a9da-cfab-11e7-861c-c65c0db2c288.jpg)

**Comment by abchatra** [comment]
This is by design today. We don't have translations for these languages.
