### ISSUE TITLE
Ad bar for app closes when clicked on it

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt-adafruit#546]
![image](https://user-images.githubusercontent.com/6107272/33295538-c55dcfca-d38a-11e7-8426-547e930cf457.png)

Here is what we discussed:
1. Make the entire bar not clickable.
2. Make the "Get App" look like a link compared to rest of the text (with blue color and underline or something similar to our other links)

**Comment by cait1inhennessy** [comment]
Fixed by https://github.com/Microsoft/pxt/pull/3522
