### ISSUE TITLE
Two projects named "Untitled" on home page

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#547]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta 
• Click "New Project" to go to the project page and then go back to Home page
• Click "New Project" again and go back to Home page again

**Expected result:**
 There should have some difference for the first project and second project name, for example "Untitled(1)" or remind user to change name for project

**Actual result:**
 There are two projects named "Untitled"
![1](https://user-images.githubusercontent.com/23466737/33308038-daccc1a8-d453-11e7-93a3-195cdf6794ba.gif)

**Comment by abchatra** [comment]
By design. If you create multiple projects with the same name, you will get multiple instances,
