### ISSUE TITLE
There is no navigation link for Documentation->About

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#549]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/docs
• Click "About" under Documentation

**Expected result:**
 There should be a link for Documentation->About

**Actual result:**
There is not a link for Documentation->About
![5](https://user-images.githubusercontent.com/23466737/33311399-b25a6908-d45f-11e7-8b5f-f36ab79e676e.gif)

**Comment by ganicke** [comment]
Fixed in #583.
