### ISSUE TITLE
Add Jingle Bells to built-in sounds

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-adafruit#551]
For the holidays, could we add Jingle Bells to our built-in sounds?
    music.playTone(330, music.beat(BeatFraction.Half))
    loops.pause(100)
    music.playTone(330, music.beat(BeatFraction.Half))
    loops.pause(100)
    music.playTone(330, music.beat(BeatFraction.Whole))
    loops.pause(100)
    music.playTone(330, music.beat(BeatFraction.Half))
    loops.pause(100)
    music.playTone(330, music.beat(BeatFraction.Half))
    loops.pause(100)
    music.playTone(330, music.beat(BeatFraction.Whole))
    loops.pause(100)
    music.playTone(330, music.beat(BeatFraction.Half))
    loops.pause(100)
    music.playTone(392, music.beat(BeatFraction.Half))
    loops.pause(100)
    music.playTone(262, music.beat(BeatFraction.Half))
    loops.pause(100)
    music.playTone(294, music.beat(BeatFraction.Half))
    loops.pause(100)
    music.playTone(330, music.beat(BeatFraction.Whole))

**Comment by pelikhan** [comment]
Should be added in a package.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
