### ISSUE TITLE
The blocks in help document are different from the blocks in editor

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#559]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click "LIGHT" and then click "...NEOPIXEL"
• Right-click and to look block help

**Expected result:**
 The block in help document should be same as the block in editor
![capture2](https://user-images.githubusercontent.com/23466737/33654280-957af3ec-daaa-11e7-8e5c-d9dba686e3a7.PNG)

**Actual result:**
The block in help document is different from the block in editor
![capture1](https://user-images.githubusercontent.com/23466737/33654212-5e4e2010-daaa-11e7-8610-4d05c28747b6.PNG)

**Issue blocks:**
![capture3](https://user-images.githubusercontent.com/23466737/33654665-c378bb2a-daab-11e7-96a7-be1d53174b2f.PNG)

**Comment by ganicke** [comment]
Fixed in https://github.com/Microsoft/pxt-common-packages/pull/197
