### ISSUE TITLE
Lacking existing packages usage

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#560]
**Repro step:**
• Navigate to https://makecode.adafruit.com/beta
• Click "ADVANCED" -> "+EXTENSIONS" -> "?" on the opeded window

**Expected Result:**
 There should have existing packages usage like on https://makecode.microbit.org/packages
![capture5](https://user-images.githubusercontent.com/23466737/33654834-4ef16c9c-daac-11e7-90e0-b2ebfc5986f8.PNG)

**Actual result:**
 There are lacking existing packages usage on https://makecode.adafruit.com/packages
![capture4](https://user-images.githubusercontent.com/23466737/33654839-5464c1b0-daac-11e7-809c-fd958579f996.PNG)

**Comment by abchatra** [comment]
I am closing this. This is waiting on third party to write packages.
