### ISSUE TITLE
The block 'on start' is missing when using keyword 'on' to search

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#565]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Put 'on' in the search box 

**Expected result:(Chrome)**
The block 'on start' should be included in the search results
![screen shot 2017-12-12 at 2 45 40 pm](https://user-images.githubusercontent.com/23497626/33871017-9cf668c2-df4b-11e7-8447-f6c82a0d9c74.png)

**Actual result:(Safari & Firefox)**
There is no block 'on start' in the search results
![screen shot 2017-12-12 at 2 46 19 pm](https://user-images.githubusercontent.com/23497626/33871078-d30bae0e-df4b-11e7-933b-98e7af9f37fb.png)

**Comment by abchatra** [comment]
I am closing this as P3 won't fix. There are many blocks with "on" and "on start" is on the workspace by default as well.
