### ISSUE TITLE
The 'Help' button is not available under MATH block 'pick random...' 

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#566]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click "MATH" and then right click "pick random ..."
• Click 'Help' to look documentation

**Expected result:**
The 'Help' can be clicked and the block in help document is displayed in right
**Actual result:**
![01](https://user-images.githubusercontent.com/23497626/33873211-f49f57e6-dece-11e7-8799-75e59b95fd6f.gif)

**Comment by abchatra** [comment]
fixed

**Comment by ganicke** [comment]
Fixed in https://github.com/Microsoft/pxt/pull/3638
