### ISSUE TITLE
The block's help document in a new tab and the page is not exists

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#568]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click "ADVANCED" and then click "TEXT"
• Right-click and to look block's help

**Expected result:**
The block's help should display in browser's right
**Actual result:**
![text01](https://user-images.githubusercontent.com/23497626/33875179-48f94d40-ded6-11e7-97b8-90d7f4201b51.gif)

**Comment by abchatra** [comment]
fixed
