### ISSUE TITLE
The documentation of Blocks and JavaScript could not load in setting

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#569]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click "?" and then click "Blocks" or "JavaScript"

**Expected result:**
The documentation should have some items about Blocks and JavaScript
**Actual result:**
![blockandjavascript](https://user-images.githubusercontent.com/23497626/33875627-aee9e546-ded7-11e7-8e9f-c6393c16e409.gif)

**Comment by abchatra** [comment]
fixed
