### ISSUE TITLE
The result is not right when search block with string "show"

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#570]
Repro steps:
• Navigate to https://makecode.adafruit.com/beta
• Input "show" in the box of "SEARCH"

Expected result:
 The blocks which were searched should all contain string "show"
 Actual result:
There is one block which didn't contain string "show"

![search-show](https://user-images.githubusercontent.com/11880996/33925336-a087b81e-e014-11e7-89ad-4ac9eb54e70f.png)

**Comment by pelikhan** [comment]
By design, the search is fuzzy and will match losely couple words.
