### ISSUE TITLE
The dialog of comment should not pop up when didn't click the icon of comment

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#571]
Repro steps:
• Navigate to https://makecode.adafruit.com/beta on Edge, Chrome, Firefox
• Drag blocks like the followed picture 
• Right click the block "if...then" to add the comment
• Click the variable "true"
![blocks](https://user-images.githubusercontent.com/11880996/33926398-ec0b6e08-e018-11e7-925b-2ed5f4906673.png)

Expected result:
Just pop up the dialog of variable, not pop up the dialog of comment

Actual result:
The dialogs of variable and comment all popped up

![comment-dialog](https://user-images.githubusercontent.com/11880996/33926249-4e01c0fe-e018-11e7-8d82-13c6ad7f06f8.gif)

**Comment by pelikhan** [comment]
This is by design, we pop open comments when clicking on the blocks.
