### ISSUE TITLE
The button of "Add Comment" is not available on IE

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#572]
Repro steps:
• Navigate to https://makecode.adafruit.com/beta on IE
• Drag some blocks to the content panel
• Right click any block to add the comment

Expected result:
The block can be added the comment
Actual result:
The button of "Add Comment" is not available

![comment-ie](https://user-images.githubusercontent.com/11880996/33926651-ee6923ba-e019-11e7-9b42-38635a529687.gif)

**Comment by pelikhan** [comment]
By design
