### ISSUE TITLE
USB keyboard

### ISSUE THREAD

**Issue by ladyada** [Microsoft/pxt-adafruit#574]
hiya @Jaqster @pelikhan  we'd like to add USB keyboard (HID) support. this can be 'hacked' to do datalogging, MIDI, and of course BANANA PIANOs :)

we see https://github.com/lancaster-university/codal-samd21/blob/master/source/USB.cpp some action going on here.

two Qs:
1. whats the best way to do that kind of low level development?
2. is there a place where we can find the rest of the USB code?

**Comment by Jaqster** [comment]
Awesome!!  That would be great :-)  Yeah, we can set up a quick call with Joe to go through the CODAL repo and explain how you could add an extension.  Will look for some time.

**Comment by ladyada** [comment]
thank you!

**Comment by pelikhan** [comment]
1) Adafruit could publish new driver/low level code compatible with CODAL in github repos. We would then be able to link them into MakeCode in a sustainable way. Would love to talk about enabling this for you.
2) This is where we use the CodalUSB device in MakeCode: https://github.com/Microsoft/pxt-common-packages/blob/c0d078f79b46c3349453c45c945c1ec1e22d6128/libs/core/usb.cpp

**Comment by pelikhan** [comment]
@mmoskal

**Comment by mmoskal** [comment]
@ladyada USB.cpp is just the SAMD21 specific driver. There is a generic HID interface here https://github.com/lancaster-university/codal-core/blob/master/inc/drivers/HID.h and https://github.com/lancaster-university/codal-core/blob/master/source/drivers/HID.cpp

We have a custom HID interface here https://github.com/Microsoft/pxt-common-packages/blob/master/libs/core/hf2.cpp and https://github.com/Microsoft/pxt-common-packages/blob/master/libs/core/hf2.h

It should be relatively easy to add a HID Keyboard, probably in Codal, not in pxt-common-packages.

**Comment by ladyada** [comment]
kk - we have to change the custom descriptor and reports. would you rather we piggyback on the current HID interface or have a composite device?

**Comment by mmoskal** [comment]
Adding another `CodalUSBInterface` (including one derived from `USBHID `) will automatically create a composite device, so no need to piggyback.

**Comment by mmoskal** [comment]
i.e., we can have the current `HF2` interface, and a new Keyboard one derived from USBHID (or `CodalUSBInterface` for that matter), and by adding both of them to CodalUSB we will have a composite device.

**Comment by ladyada** [comment]
awesome. i didnt know it was pluggable USB. thats awesomepants :) should we have the keyboard interface active no matter what or would the existance of an 'onstart' block cause it to be added (e.g. in python we must init USB before the usercode starts so all pyboards have USB HID/MSD/CDC composites)

**Comment by ladyada** [comment]
awesome. i didnt know it was pluggable USB. thats awesomepants :) should we have the keyboard interface active no matter what or would the existance of an 'onstart' block cause it to be added (e.g. in python we must init USB before the usercode starts so all pyboards have USB HID/MSD/CDC composites) ?

**Comment by mmoskal** [comment]
This would be decided on PXT not Codal side. Codal doesn't support dynamic adding of interfaces, but I think neither does USB protocol in general (short of doing a full USB reset). In PXT we could delay USB initialization for say 20ms and then decide what interfaces to include. I think that would be nicer, because at some point we'll start to run out of USB endpoints.

**Comment by ladyada** [comment]
OK!

**Comment by ladyada** [comment]
hiya, good news! @deanm1278 has added USB HID keyboard support

https://github.com/adafruit/codal-core/commit/bfe5145d949646e33ca94b463733bffd71b25ebc

and has a basic demo

```
#include "CircuitPlayground.h"
CircuitPlayground cplay;
#include "HIDKeyboard.h"
CodalUSB usb;
USBHIDKeyboard hid;
static const char *string_descriptors[] = {
    "Example Corp.", "PXT Device", "42424242",
};
int main()
{
    int status = 0;
    usb.stringDescriptors = string_descriptors;
    usb.add(hid);
    usb.start();
    uint8_t key = 0;
    //we need a bit of a delay for USB
    cplay.sleep(500);
    while(1)
    {
        cplay.io.led.setDigitalValue(status);
        //press a key
        hid.keyPress(key);
        cplay.sleep(100);
        //release the key
        hid.keyUp();
        key++;
        cplay.sleep(800);
        status = !status;
    }
}
```

our next question is - what is the API you want to this from typescript. e.g. should we just have a keycode-sender and typescript does the character-to-keycode conversion? OR we can take in an ascii string and do it all for ya. just depends where you want to split the labor. 

note that each country has a different keymapping >.< we could do US for sure but other countries would be a little challenging for us to properly test

**Comment by pelikhan** [comment]
Something that maps to https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values would be great

________________________________

**Comment by mmoskal** [comment]
IMHO the more we put in TypeScript the better especially for more esoteric features. The C++ code generally gets linked every time whereas Typescript is only linked as needed.

________________________________

**Comment by deanm1278** [comment]
What if the C++ API was just
>
>  keyDown(uint8_t key, uint8_t report=GENERIC);

 keyDown(uint8_t key, uint8_t report=GENERIC);


Where GENERIC would be regular key codes and CONSUMER would be multimedia
keys

C++ would manage the internal state of which keys are pressed, and you
would basically do in typescript what you do with your fingers on the
keyboard:
pressKey('shift'), pressKey('a'), releaseKey('a'), releaseKey('shift')

**Comment by deanm1278** [comment]
sorry typo, C++ API would be:
>
>  keyDown(uint8_t key, uint8_t report=GENERIC);

 keyUp(uint8_t key, uint8_t report=GENERIC);

**Comment by deanm1278** [comment]
also just to clarify intent, typescript would be doing all the keycode
lookups. C++ would just feed through the passed keycodes to the host
machine.

**Comment by deanm1278** [comment]
an implemented API is here for your consideration:
https://github.com/adafruit/codal-core/commit/17cf9b41c94c81ec697b9ad249268f9aa5567db2

        int modifierKeyDown(uint8_t key, uint8_t
> reportID=HID_KEYBOARD_REPORT_GENERIC);
>         int modifierKeyUp(uint8_t key, uint8_t
> reportID=HID_KEYBOARD_REPORT_GENERIC);
>         int keyDown(uint8_t key, uint8_t
> reportID=HID_KEYBOARD_REPORT_GENERIC);
>         int keyUp(uint8_t key, uint8_t
> reportID=HID_KEYBOARD_REPORT_GENERIC);


Typescript would decide whether the key sent was a modifer (e.x.
pressKey('LSHIFT') ) or a normal key (e.x. pressKey('A') )

The main.cpp example is:

#include "CircuitPlayground.h"


> CircuitPlayground cplay;


> #include "HIDKeyboard.h"

CodalUSB usb;

USBHIDKeyboard hid;


> static const char *string_descriptors[] = {

    "Example Corp.", "PXT Device", "42424242",

};


> int main()

{

    usb.stringDescriptors = string_descriptors;

    usb.add(hid);

    usb.start();


>     uint8_t key = 0;


>     //we need a bit of a delay for USB

    cplay.sleep(500);


>     while(1)

    {

        //hold left shift key

        hid.modifierKeyDown(0x02);


>         //press a key

        hid.keyDown(key);


>         cplay.sleep(100);

        //release the key

        hid.keyUp(key);

        key++;


>         //release left shift key

        hid.modifierKeyUp(0x02);


>         cplay.sleep(800);

    }

}

**Comment by deanm1278** [comment]
Hello! just pinging this thread again, I have added HID mouse and HID
gamepad as well:
https://github.com/adafruit/codal-core

The mouse implementation has 3 buttons, wheel, and xy movement and the
interface is:

int buttonDown(USBHIDMouseButton b);
> int buttonUp(USBHIDMouseButton b);
> int move(int8_t x, int8_t y);
> int moveWheel(int8_t w);


The gamepad has 2 joysticks, 2 throttles (values 0-31) and 16 buttons. This
layout can of course be changed. The interface is:

int buttonDown(uint8_t b);
> int buttonUp(uint8_t b);
> int move(int8_t num, int8_t x, int8_t y);
> int setThrottle(uint8_t num, uint8_t val);

**Comment by pelikhan** [comment]
Thanks! Most of the teams are on holiday break so this will have to wait till Jan.

________________________________

**Comment by deanm1278** [comment]
no worries! We'll hold off on any more updates until then.

**Comment by ladyada** [comment]
@pelikhan wooo happy new year! lets do this thing - we have this exciting code written and ready to merge in and implement, are you ready? :)

**Comment by pelikhan** [comment]
@deanm1278 @ladyada the C++ api looks great. The next step is to get it PR/Reviewed/merged in codal-core. I'll start building the TypeScript layer around it.

**Comment by ladyada** [comment]
ok should dean submit it as a PR? or is that something you do?

**Comment by pelikhan** [comment]
I think you should submit the PR for CODAL-core.

**Comment by ladyada** [comment]
great - its submitted :)

**Comment by pelikhan** [comment]
@ladyada there is an alternative route to sending a PR to CODAL-core which is creating your own repos:

* create a new repo under your github org that exposes the USB HID C++ code (eg. adafruit/codal-usbhid).
* create a new repo that contains the makecode gluing code (e.g. adafruit/pxt-usbhid). Once setup, the user can add this package using the "Extensions" button from the editor and get the new blocks.

Benefits: there is no bottleneck to deliver new drivers (like people taking the holidays off :)), new blocks can be delivered through the "Extensions" feature and tested. The most popular ones can be preloaded eventually

@finneyj

**Comment by ladyada** [comment]
i thought it would be kinda cool to have it be built-in by default, rather than an extension? whichever way y'all prefer!

**Comment by pelikhan** [comment]
Yeah, USBHID is a special universal one... Other driver might fall under the "do your own repo" kind of category, similarly to your various Arduino drivers.

**Comment by ladyada** [comment]
ok going forward for specialized drivers we will do so! :)

**Comment by pelikhan** [comment]
Happy to help with the plumbing for the next one :)

**Comment by mmoskal** [comment]
To clarify: I don't think we support a separate C++ repo per extension, however a `pxt-my-driver` repo can contain C++ code.
