### ISSUE TITLE
Hard crash when using servo on batteries

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-adafruit#575]
I was trying to automate the mouth of my Nutcracker (https://twitter.com/pelikhan/status/941540080065196033) but the CPX keeps on crashing after a few seconds when on battery. Here is a minimal repro that calls servo write until the CPX locks. It is connected to 3xAAA battery + SG92R.

It locks within 10secs on battery only
```
loops.forever(function () {
    pins.A1.servoWrite(Math.randomRange(30, 45))
})
```

* I've tried to repro in CircuitPython but there does not seem to be easy servo support.
* the Arduino ``sweep`` sketch does not lock
* the ``sweep`` scripting translated to MakeCode does not lock either
```
loops.forever(function () {
    for (let pos = 0; pos <= 180; pos += 1) { // goes from 0 degrees to 180 degrees
        // in steps of 1 degree
        pins.A1.servoWrite(pos)
        loops.pause(15);                       // waits 15ms for the servo to reach the position
    }
    for (let pos = 180; pos >= 0; pos -= 1) { // goes from 180 degrees to 0 degrees
        pins.A1.servoWrite(pos)
        loops.pause(15);                       // waits 15ms for the servo to reach the position
    }
})
```
* the following C++ program locks after a few seconds
```

#include "CircuitPlayground.h"

CircuitPlayground cplay;

int main()
{
    int status = 0;
    while(1)
    {
        cplay.io.led.setDigitalValue(status);
        cplay.io.a1.setServoValue(30 + rand() % 15);
        cplay.sleep(20);
        status = !status;
    }
}
```

**Comment by pelikhan** [comment]
Seems like it is CODAL - https://github.com/lancaster-university/codal/issues/34

**Comment by pelikhan** [comment]
@mmoskal @finneyj

**Comment by abchatra** [comment]
I am closing this issue in favor of tracking codal issue.
