### ISSUE TITLE
The role of these two menus "adafruit" and "HOME" is the same

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#577]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click the  "New Project"
• Click the menu "adafruit" or "HOME", give the project a name such as "Test" and click "Done"
• Click the "Test" project, and click these two menus again

**Expected result:**
Like microbit site, when clicked the "micro:bit", it will show the instructions about microbit.
![instruction](https://user-images.githubusercontent.com/23497626/34198758-5d4ce446-e520-11e7-87b6-9e6bb5a221ec.gif)

**Actual result:**
The role of "adafruit" and "HOME" is the same. When clicked the "adafruit", the new tab should show the instructions about adafruit.
![adafruit](https://user-images.githubusercontent.com/23497626/34198485-6baca130-e51f-11e7-84ce-546396939acc.gif)

**Comment by pelikhan** [comment]
By design.
