### ISSUE TITLE
The Same project, simulator doesn't work under "BLOCKS".

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#579]
**Repro Step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Create New Project and Switch to _{}JAVASCRIPT_
- Copy the following code into content panel and run it 
"
_let spinit = false;
let pixels = light.createStrip();_

    _input.buttonA.onEvent(ButtonEvent.Click, () => {
        spinit = false;
        pixels.clear();
    })_
_control.runInBackground(() => {
    pixels.setPixelColor(0, Colors.Blue);
    while (spinit) {
        pixels.move(LightMove.Rotate, 1);
        loops.pause(250);
    }
})_
_spinit = true;
for (let i = 0; i < 5; i++) {
    loops.pause(1000);
    pixels.setPixelColor(0, Colors.Blue);
}_
"
- Then switch back to _BLOCKS_ and run it

**Expected result:**
After switching back to "_BLOCKS_", it should work as like working on "_{}JAVASCRIPT_".
![157bbfdc-04c6-43b7-97f8-ac481e1a8f70](https://user-images.githubusercontent.com/17866936/34202157-e27b07e2-e5b1-11e7-8579-1ac8fef292fd.gif)

**Actual Result:**
![2bbcbede-aec6-41e8-8c14-41321ae1cff3](https://user-images.githubusercontent.com/17866936/34202270-421145d6-e5b2-11e7-9cb1-048639c1dba7.gif)

**Comment by Helen09** [comment]
**Actual result:**
After clicking "BLOCKS", it shows error
 
![123](https://user-images.githubusercontent.com/23466737/37085289-9482eb64-21ec-11e8-9e42-7198ca2fafab.gif)

**Comment by samelhusseini** [comment]
We no longer support the colors enum in blocks. Use the color value instead like: 0xff0000
