### ISSUE TITLE
Customer issue with InfraRed input

### ISSUE THREAD

**Issue by ladyada** [Microsoft/pxt-adafruit#580]
https://forums.adafruit.com/viewtopic.php?f=58&t=128057
not working/hanging? 
i haven't tested IR extensively - but we recommend the NEC mini-remote since it's similar to many low cost remotes.

**Comment by mmoskal** [comment]
The IR blocks do not support custom protocols of remotes. It only supports its own custom protocol. We'll need to investigate the hang though.

**Comment by abchatra** [comment]
Closing as this is duplicate of https://github.com/Microsoft/pxt-adafruit/issues/649
