### ISSUE TITLE
How to force update?

### ISSUE THREAD

**Issue by ladyada** [Microsoft/pxt-adafruit#581]
on my win 7 desktop w/firefox i still get 

> A Blocks / JavaScript code editor for the Adafruit Circuit Playground Express.
> Adafruit Circuit Playground Express version: 0.10.13
> Microsoft MakeCode version: 1.3.6
> C++ runtime version: master

how can i force it to update? I tried 'reset' to no avail :)

**Comment by pelikhan** [comment]
Could open the JavaScript console and share the output on a full reload?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ladyada** [comment]
> Logging system initialised at Wed Dec 20 2017 12:49:25 GMT-0500 (Eastern Standard Time)
> common.js:195:17
> Loading failed for the <script> with source “blob:https://makecode.adafruit.com/92cd40c7-d330-4a81-9318-45040d2d9277”.
> makecode.adafruit.com:1
> The Application Cache API (AppCache) is deprecated and will be removed at a future date.  Please consider using ServiceWorker for offline support.
> makecode.adafruit.com
> Download the React DevTools for a better development experience: https://fb.me/react-devtools
> main.js:49721:9
> unreachable code after return statement
> [Learn More]
> main.js:15201:4
> Browser: firefox 57.0 on windows
> pxtlib.js:1219:13
> Logging system initialised at Wed Dec 20 2017 12:49:26 GMT-0500 (Eastern Standard Time)
> common.js:195:17
> Logging system initialised at Wed Dec 20 2017 12:49:31 GMT-0500 (Eastern Standard Time)
> common.js:195:17
> Ignoring non-existent field NUM in block neopixel_colors

![image](https://user-images.githubusercontent.com/1214161/34220966-6a0bdffc-e584-11e7-855e-b3477da2e3b9.png)

**Comment by pelikhan** [comment]
Could you also dump the network tab data? I wonder why it is trying to get that initial URL.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ladyada** [comment]
do you know an elegant way to extract the data? its in a table >.<

**Comment by pelikhan** [comment]
Is this still an issue?

**Comment by ladyada** [comment]
i never resolved it, so i just deleted all browser data which is one way of fixing the problem :D

**Comment by abchatra** [comment]
No repro
