### ISSUE TITLE
The simulator didn't display clearly on firefox

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#586]
Repro steps:
• Navigate to https://makecode.adafruit.com/beta on **firefox**
• Drag blocks like the followed picture
• Drag block "on shake" to the content panel
![block](https://user-images.githubusercontent.com/11880996/34432509-d9e956e4-ecb2-11e7-9107-cd9d73d31abc.png)

Expected result:
The simulator should display clearly

Actual result:
The simulator didn't display clearly 

![simulator](https://user-images.githubusercontent.com/11880996/34432577-79564700-ecb3-11e7-9f95-315a5055c761.gif)

**Comment by microsoftsam** [comment]
What version of Firefox?

**Comment by microsoftsam** [comment]
Please add browser details in the future: Browser version and Operating System.

**Comment by yanlxu** [comment]
@microsoftsam, the version of Firefox is 57.0.3, the Operating System build: \\winbuilds\release\RS_ONECORE_WEBPLAT_STAGE_DEV3\17058.1004.171227-1700\x86fre

**Comment by Helen09** [comment]
The issue still repro on the latest build: 17607.1011.180305-1700 on firefox(version: 58.0.2)
![15](https://user-images.githubusercontent.com/23466737/37195464-cff4e6b4-236a-11e8-8251-b42d49c7c230.gif)

**Comment by Helen09** [comment]
Closed as not repro

**Comment by yanlxu** [comment]
close as not repro
