### ISSUE TITLE
The block "create array with" can't add new elements in "BLOCKS"

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#592]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Switch to "{ }JAVASCRIPT" and copy below code on it
*******************************************************
let words: string[] = []
words = ["Hello", "there", "Hi", "Good", "Well"]
*******************************************************
• Switch to "BLOCKS" and click "+" to add elements to Array

**Expected result:**
There is a new blank textbox that can write words
**Actual result:**
![array](https://user-images.githubusercontent.com/23497626/34816910-362deb1a-f66b-11e7-8301-ceb613fd037f.gif)

**Comment by abchatra** [comment]
@WendyFeng01 Great bug
