### ISSUE TITLE
After adding block "reset", project can't be published

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#596]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Drag blocks like below picture
• Click "SHARE" to publish this project

**Expected result:**
 The project should be published successfully
**Actual result:**
This project can't be published for adding block "reset"
![3](https://user-images.githubusercontent.com/23466737/34821979-409fcf26-f6bd-11e7-9ed0-1ee7b19d7b32.gif)

**Comment by samelhusseini** [comment]
Can't repro anymore on /beta. Please try again and reopen if still repro.

Would be great in this scenario if you could add a JS copy of the code used so we can debug further.

**Comment by Helen09** [comment]
I validate this bug, it not repro on Edge, but it still repro on **Firefox, Chrome & IE**
**Firefox**: 59.0.2
**Chrome**: 66.0.3359.117
**IE**: 11.1.17134.0

**The JS copy of the code:**
forever(function () {
    light.showRing(
        "red red red red red red red red red red"
    )
    control.reset()
})

**Comment by Helen09** [comment]
**The beta version info:**
Adafruit Circuit Playground Express version: 1.1.9
Microsoft MakeCode version: 3.8.18
C++ runtime version: v0.2.2

**Comment by Helen09** [comment]
The detail is as below .gif
![issue596](https://user-images.githubusercontent.com/23466737/39238971-2a2795ae-486f-11e8-9084-602e75e8302b.gif)

**Comment by Helen09** [comment]
Could you help reopen this bug?@Sam

**Comment by samelhusseini** [comment]
It's the same root cause as this: https://github.com/Microsoft/pxt-adafruit/issues/702
