### ISSUE TITLE
A block "Middle C" has two displaying forms.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#598]
**Repro Step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Drag "_set item to 0_" from "_VARIABLE_" and put it into "_forever_"
- Then put "_Middle C_"(Music) into "_set item to ‘0’_ " and click "_Middle C_"

**Expected Result:**
![middlecexpectedresult](https://user-images.githubusercontent.com/17866936/35139442-05a8dba4-fceb-11e7-915e-dbbfcde707e7.gif)

**Actual Result:**
![05197052-5d96-4db0-af05-054e8e4310a0](https://user-images.githubusercontent.com/17866936/35139583-ac36bb76-fceb-11e7-93c0-1595d69042da.gif)

**Comment by abchatra** [comment]
@samelhusseini is this worthwhile to fix for the release?

**Comment by samelhusseini** [comment]
Fix is being integrated.
