### ISSUE TITLE
Block "light.createStrip()" results in the simulator doesn't work after switching from "{}Javascript" to "BLOCKS"

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#603]
**Repro Step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Copy the following code into content panel:
_let strip = light.createStrip()
for (let i = 0; i < strip.length(); i++) {
    strip.photonForward(1)
    loops.pause(150)
}_
- Switch back to "_BLOCKS_" and run the project

**Expected Result:**
1.  "let strip = light.createStrip()" should be equivalent to "let strip = light.createStrip(pins.A1, 0)", and after switch back to "BLOCKS", it should display like following:
![default](https://user-images.githubusercontent.com/17866936/35142532-7f8d895a-fcf6-11e7-82ce-c990d0a22b8c.PNG)
2. After switching to "BLOCKS", it should display like follows GIF. And maybe block "onboard strip" should be better than "light.createStrip()".
![expectedresult](https://user-images.githubusercontent.com/17866936/35142300-ccfd7e08-fcf5-11e7-8916-d4acfb1c5416.gif)

**Actual Result:**
issue 1: "let strip = light.createStrip()" could become "let strip = light.createStrip(pins.A1, 0)", but when switching back to "BLOCKS", it shows like following picture. 
![issue](https://user-images.githubusercontent.com/17866936/35142752-2c2564d0-fcf7-11e7-8237-9e95be2a1345.PNG)

issue 2:
When switch back to "BLOCKS", the simulator doesn't work. Detail as following:
![34c9bdfa-d960-4a9d-ad74-c95019f55d80](https://user-images.githubusercontent.com/17866936/35142305-d1f6e962-fcf5-11e7-97e1-7d0fab177975.gif)

**Comment by samelhusseini** [comment]
Dupe here https://github.com/Microsoft/pxt-adafruit/issues/674
