### ISSUE TITLE
analogWrite to pads doesnt work?

### ISSUE THREAD

**Issue by ladyada** [Microsoft/pxt-adafruit#604]
hiya trying to generate a PWM signal on the pads does not seem to do anything?

![image](https://user-images.githubusercontent.com/1214161/35314468-62a4ea8a-0094-11e8-902b-3db4a03869d2.png)

also, relatedly, A8, A9 and A10 should not appear here as they are internal sensors and its weird to have them be outputs! :)

![image](https://user-images.githubusercontent.com/1214161/35314450-40b4cb84-0094-11e8-8704-6031e3499269.png)

**Comment by pelikhan** [comment]
The pin map is defined here: https://github.com/Microsoft/pxt-adafruit/blob/master/libs/circuit-playground/device.d.ts#L34 . Any other we should remove?

**Comment by ladyada** [comment]
just A8, A9, and A10 should be removed from that list
A0 doesnt have a timer so PWM is hard to do but you can do true analog writes

**Comment by jedgarpark** [comment]
I'm trying to do analogWrite to A0, but this seems like it currently doesn't output any voltage when you send 1023 or any other values.

**Comment by pelikhan** [comment]
Is it just A0?

________________________________

**Comment by jedgarpark** [comment]
that's the only one I'm trying because i want a real analog signal, not PWM like the other pins.

**Comment by pelikhan** [comment]
Looking into this.

**Comment by pelikhan** [comment]
And the results are in:
- [ ] A0: lock
- [ ] A1: ok
- [ ] A2: ok
- [ ] A3: ok
- [ ] A4: lock
- [ ] A5: lock
- [ ] A6: lock
- [ ] A7: lock

**Comment by pelikhan** [comment]
A fix is in beta. @ladyada We ended up restricting PWM out to A1 and A2. Use 3 PWM pins would lock the device and pins A4, A5, A6, A7 lock the device as well because of an mbed issue (see https://github.com/lancaster-university/codal-circuit-playground/issues/5). Maybe we can get some cycles from your engineers to help fix this issue.

**Comment by ladyada** [comment]
ok according to my docs, only A1, A2 A3 and A6 have PWM out, so A1 and A2 are good!

**Comment by ladyada** [comment]
@pelikhan heya related Q, i want to try this and also test out a customer issue https://forums.adafruit.com/viewtopic.php?f=58&t=133680 but i can only update to 1.0.28 adafruit CPX release which is from ~2 weeks ago and it looks like some stuff was released since. is there a way to 'force' makecode to upgrade to the latest?

![image](https://user-images.githubusercontent.com/1214161/38715933-262aafe4-3eac-11e8-8ce9-2532046dacff.png)

**Comment by pelikhan** [comment]
The easiest trick to defeat caching is to use incognito/inprivate/anonymous mode is your browser... or add ?v=djebeizizkfb to the url where
djebeizizkfb is generated by banging the keyboard :)

We also stage our next update on https://makecode.adafruit.com/beta . That version has Michal’s fixes to support analogWrite on A0.

_____________________________

**Comment by abchatra** [comment]
This bug seems to be fixed.
