### ISSUE TITLE
Prompting information is not displayed under "High Contrast on"

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#606]
**Repro Step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Click "_More..._" and choose "_High Contrast On_"
- Select "_VARIABLE_" or "_FUNCTIONS_"

**Addtional Information:**
_The issue only repro on Safari, Firefox & Chrome_
Safari: 11.0.3(13604.5.6)
Chrome:64.0.3282.119
Firefox: 58.0

**Expected Result:**
![prompt](https://user-images.githubusercontent.com/17866936/35382325-c5aa582c-01b6-11e8-9048-1db7ec4ca836.PNG)

**Actual Result:**
"_Variable_":
![prompt1](https://user-images.githubusercontent.com/17866936/35382417-1230048a-01b7-11e8-8db6-370e0cee6499.PNG)

"_Functions_":
![prompt2](https://user-images.githubusercontent.com/17866936/35382425-17ad85d6-01b7-11e8-8a4a-2cce54e266e7.PNG)

**Comment by Helen09** [comment]
This issue also repro on Edge

**Comment by Emma-sunny** [comment]
Close as fixed
