### ISSUE TITLE
There are no "Projects" and "Examples" items under the "help"

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt-adafruit#610]
Repro steps:
• Navigate to https://makecode.adafruit.com/beta
• Click the "New Project"
• Click the "help"
• Navigate to the "Documentation" https://makecode.adafruit.com/docs

Expected result:
There are "Projects" and "Examples" items under the "help" just like in the document, so that the user can easily open these example projects under "help"

Actual result:
 There are no "Projects" and "Examples" items under the "help", the user need to open these example projects through the document or the main page

help:
![help](https://user-images.githubusercontent.com/11880996/35383830-550d3684-01bb-11e8-8a82-fb10dd9a5a0a.png)

Documentation:
![document](https://user-images.githubusercontent.com/11880996/35383976-cfacb95a-01bb-11e8-9c9a-596fa7e9b962.png)

**Comment by samelhusseini** [comment]
By design
