### ISSUE TITLE
Block "Console log..." doesn't work.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt-adafruit#611]
**Repro Step:**
- Navigate to [https://makecode.adafruit.com/beta](url)
- Create new Project and copy the following code into content panel:

```
let newList: string[] = []
newList = ["pellow", "newWorld", "About", "568789"]
for (let value of newList ) {
    console.log(value)
}
```

**Expected Result:**
Block "_Console log..._ " should show all string into the following area.
![screen shot 2018-01-26 at 10 11 46 am](https://user-images.githubusercontent.com/17866936/35422093-c95fadc2-023e-11e8-8dcb-9b6b1c3d10dd.png)

**Actual Result:**
![screen shot 2018-01-26 at 10 12 32 am](https://user-images.githubusercontent.com/17866936/35422133-0d3db4c6-023f-11e8-80af-d85405ebfc23.png)

**Comment by Helen09** [comment]
This bug still repro on Chrome&Safari on Mac
On other browsers, it shows as below:
![123](https://user-images.githubusercontent.com/23466737/38023107-e7a6716e-3270-11e8-9402-c3fd36d039ba.gif)

**Comment by Emma-sunny** [comment]
Closed as fixed
