### ISSUE TITLE
Editor is not displayed correctly when user right-click mouse and click backspace

### ISSUE THREAD

**Issue by shunzhan** [Microsoft/pxt-adafruit#616]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Switch to "BLOCKS" mode
• Click any block(eg: show ring) in the editor and same time pressing the backspace
• Click "LIGHT" again , then observed 'block' on firefox
•  Click "LIGHT" again and try to drag 'block' on chrome&edge&safari
**Expected result:**
 Block should be displayed correctly and block should be able to be dragged

**Actual result:**
On firefox: The block overlapped
![editor](https://user-images.githubusercontent.com/34087467/35667980-8a470246-0727-11e8-9b04-3e52654a3eee.PNG)
On chrome&edge&safari: The block can not be dragged
![drag](https://user-images.githubusercontent.com/34087467/35668193-74c5a228-0728-11e8-962d-8b8b0de42a34.gif)

**Comment by samelhusseini** [comment]
Woah, the size of the field editor in firefox is a little out of wack.

**Comment by abchatra** [comment]
I can't reproduce this

**Comment by abchatra** [comment]
Reopen if you can
