### ISSUE TITLE
Out of range number can type on block "set volume"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#625]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Drag block "set volume"
• Change the number on block "set volume" to "666666" or "-123" 

**Expected result:**
1.It should show a message the number range of "set volume" 
2.It can't type number on the block out of the range from 0 to 256
![1](https://user-images.githubusercontent.com/23466737/36016063-3c673404-0d69-11e8-9c6f-bb48bc94a7bc.gif)

**Actual result:**
![2](https://user-images.githubusercontent.com/23466737/36016069-426008e0-0d69-11e8-8a0f-a8b98f4ed54e.gif)

**Comment by abchatra** [comment]
This is by design. There is no errors in blockly and it will clamp to lowest or highest value
