### ISSUE TITLE
Home Screen - highlight on the 2nd recent card

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#629]
Edge
Repro: work on a project, go back to Home screen. Expect that the most recent project would be highlighted.  Instead, it's always the second card that's highlighted.

![recentprojecthighlight](https://user-images.githubusercontent.com/22108954/36044868-dd712d54-0d88-11e8-8c4a-31ce1bdd83ad.PNG)

**Comment by abchatra** [comment]
I  don't repro this bug in beta
