### ISSUE TITLE
Package "cable" can't be added successfully

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#641]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click "ADVANCED" -> "EXTENSIONS" -> "cable"

**Except result:**
After clicking this package, it can be added successfully
**Actual result:**
After clicking this package, it can't be added
![1](https://user-images.githubusercontent.com/23466737/36583624-6aef1fde-186e-11e8-8a6b-383ffd9d407a.gif)

**Comment by abchatra** [comment]
Cable API is part of Network category. This is by design.
