### ISSUE TITLE
Error with retrieving seconds

### ISSUE THREAD

**Issue by efredericks** [Microsoft/pxt-adafruit#643]
When trying to do a task on a second-by-second basis I tried using the `control.seconds` call, however it results in an error that `Property 'seconds' does not exist on 'typeof  control'`

This comes from using the JavaScript or Blocks interface.  Moreover, clicking the Blocks interface drops in a call to `control.control.seconds()`, which also doesn't work.

Using `control.millis()` and modding with the appropriate value works fine.

**Comment by abchatra** [comment]
We have only control.millis() You can get seconds by multiplying 100.
