### ISSUE TITLE
Back to home page, the second opened history project is selected

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#648]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Open few project and then back to the home page

**Expect result:**
After opening a new project and then back to the home page, any opened history project shouldn't be selected
**Actual result:**
After opening a new project and then back to the home page, the second opended history project is selected
![1](https://user-images.githubusercontent.com/23466737/36879704-f5443a90-1dbc-11e8-814b-fae1e426e8cd.gif)

**Comment by abchatra** [comment]
P3. Close
