### ISSUE TITLE
The help document covers the block selection menu

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#652]
**Repro steps**:
• Navigate to https://makecode.adafruit.com/beta
• Open project document on the right-page and blcok selection menu together

**Expect result**:
Only open/close help document button floating on the block selection menu
![2](https://user-images.githubusercontent.com/23466737/36965621-1d3b01f4-2052-11e8-8631-a0f264bd5455.gif)
 
**Actual result:**
The help document covers the block selection menu
![4](https://user-images.githubusercontent.com/23466737/36965793-95c2439e-2052-11e8-971a-f454cd364133.png)

**Comment by samelhusseini** [comment]
The actual result makes sense. Looks broken in micro:bit here. 
If we place the flyout on top of the sidebar, where are you going to drag the blocks to? It makes sense in that view to either close the simulator or expand your view if you can / zoom out.
