### ISSUE TITLE
serial blocks

### ISSUE THREAD

**Issue by jallwine** [Microsoft/pxt-adafruit#656]
Why are there no serial communication blocks like the microbit version of make code? This would be a fantastic way to interface over USB with programs running on a computer. Is this in the road map?

**Comment by pelikhan** [comment]
The CPX for MakeCode supports HF2, https://github.com/Microsoft/uf2/blob/master/hf2.md, but not serial. HF2 allows to interact with WebUSB or the windows app.

**Comment by jallwine** [comment]
Are there any blocks for sending arbitrary data using WebUSB? What windows app are you referencing?

**Comment by samelhusseini** [comment]
Windows app: https://www.microsoft.com/en-us/store/p/makecode-for-adafruit/9pgzhwsk0pgd?SilentAuth=1

**Comment by abchatra** [comment]
You need windows app and console.log block will send data to the app.
