### ISSUE TITLE
Project name "Untitled" can't be deleted once on "Project Settings"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#657]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click "More..." -> "Project Settings" -> try to update a new name for the project

**Expect result:**
After first clicking, "Untitled" should be selected and can be deleted once
![14](https://user-images.githubusercontent.com/23466737/37136760-db991830-229a-11e8-960b-3eac25473adc.gif)

**Actual result:**
Project name "Untitled" can't be selected and can't be deleted once
![13](https://user-images.githubusercontent.com/23466737/37136776-f04b4eec-229a-11e8-8fc8-345422190340.gif)

**Comment by samelhusseini** [comment]
You should be able to do a Ctrl + A to select all and delete. Not other behaviour is expected. 

In the first scenario you're describing the focus and selectall, but we don't do that for the second scenario.
