### ISSUE TITLE
Block comment can't be selected 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#661]
**Repro steps**:
• Navigate to https://makecode.adafruit.com/beta
• Click "LIGHT" to drag any block like "show ring" and put it under forever
• Right-click to add comment for "show ring"
• Try to select the comment and deleted

**Except result**:
The comment should be selected 
**Actual result**:
The comment can't be selected 
![1](https://user-images.githubusercontent.com/23466737/37386766-bbde4c98-2751-11e8-87b9-f576c75d3901.gif)

**Comment by samelhusseini** [comment]
Fixed in /beta

**Comment by samelhusseini** [comment]
Please verify.

**Comment by Helen09** [comment]
This bug has been fixed, but the comments shows differently on Edge&Chrome

**Chrome: 66.0.3359.117**
![capture1](https://user-images.githubusercontent.com/23466737/39239832-a0a7e39e-4871-11e8-86d9-9b8817c3b270.PNG)

**Edge:**
![capture2](https://user-images.githubusercontent.com/23466737/39239844-a6c618c2-4871-11e8-9a2b-953f99af9515.PNG)

Adafruit Circuit Playground Express version: 1.1.9
Microsoft MakeCode version: 3.8.18
C++ runtime version: v0.2.2

**Comment by samelhusseini** [comment]
You are looking at two different versions of the editor. One is the old style of comments and the other is the new style.. If you reload the previous editor in Chrome, you'll notice they're the same.

**Comment by Helen09** [comment]
Ok, I got it. Thank you~
