### ISSUE TITLE
The cursor disappeared in comment box

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#662]
**Repro steps**:
• Navigate to https://makecode.adafruit.com/beta
• Click "LIGHT" to drag any block like "show ring" and put it under forever
• Right-click to add comment for "show ring"
• After adding some comments, zoom in/out the comment box

**Expect result**:
The cursor shouldn't disappear
**Actual result**:
The cursor will disappear in comment box, so user can't update comment
![4](https://user-images.githubusercontent.com/23466737/37389975-357c17d6-275e-11e8-8539-6172d8fd9988.gif)

On **chrome**, when the comment is long enough, the comment will become black
![3](https://user-images.githubusercontent.com/23466737/37389625-fc3eb97a-275c-11e8-8788-acd0ca664dcd.gif)

**Comment by abchatra** [comment]
Closing P3
