### ISSUE TITLE
Project "Patience" is empty after opened except on chrome on windows

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#663]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Drag scrollbar to "Games" -> open project "Patience!"

**Expect result(Chrom on windows):**
Project "Patience" should be opened on every browser
![capture](https://user-images.githubusercontent.com/23466737/37441606-2fe3f644-27fa-11e8-8ea3-bd7e7066c3ec.PNG)

**Actual result(Safari, edge, IE, firefox):**
Project "Patience" is empty after opened 
![5](https://user-images.githubusercontent.com/23466737/37441570-01331e60-27fa-11e8-8d13-1f4971271f25.gif)

**Comment by Helen09** [comment]
When opening this project, it's empty on every browser

**Comment by abchatra** [comment]
Fixed
