### ISSUE TITLE
Text "https://makecode.com/..." didn't hide when copying project URL

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#664]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click "Import" on the right-page
• Click "Import URL" and the move cursor mouse to text box to copy URL of project

**Expect result:**
After clicking in text box, the text "https://makecode.com/..." in it should hide
**Actual result:**
After clicking in text box, the text "https://makecode.com/..." didn't hide
![8](https://user-images.githubusercontent.com/23466737/37506117-4e2d57c6-28e0-11e8-9e15-47ebfc870793.gif)

**Comment by abchatra** [comment]
P3 Closing
