### ISSUE TITLE
Text issues on menu bar links

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#666]
**Repro steps:**
• https://makecode.adafruit.com/beta#editor
• Move cursor mouse on menu bar and observe

**Expect result:**
There should have text instruction like others
![5](https://user-images.githubusercontent.com/23466737/37814538-70f72714-2e62-11e8-8b3f-229b7b4c5adb.gif)

**Actual result:**
Issue 1: When moving cursor mouse on "adafruit", there is no text instruction
![6](https://user-images.githubusercontent.com/23466737/37814647-ea1a3abe-2e62-11e8-9847-7487ab73178d.png)

Issue 2: The text of "Microsoft"  at the bottom-left is too long on chrome
![untitled1](https://user-images.githubusercontent.com/23466737/37814698-3533e432-2e63-11e8-9534-178d7a768472.png)

**Comment by samelhusseini** [comment]
The bottom left corner text is a browser feature when you hover over links. 
There is no expected "title" field over the image. Only alt text, which I've verified exists.
