### ISSUE TITLE
There don't have a checking if the typed project name has existed

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#671]
**Repro steps:**
• https://makecode.adafruit.com/beta
• Click "New Project" -> go to the editor page -> Click "Home" -> type Project Name as "12345"
• Do as the second step again and named the second project as "12345"

**Expect result:**
There should have a chekcing if the typed project name has existed 
**Actual result:**
There don't have a checking if the typed project name has existed
![12](https://user-images.githubusercontent.com/23466737/38011875-a9646a04-324e-11e8-92a3-f1f9ab21f5b1.gif)

**Comment by samelhusseini** [comment]
Nope, by design you can name a number of projects with the same name.
