### ISSUE TITLE
Explain better that Serial is for the app only

### ISSUE THREAD

**Issue by ladyada** [Microsoft/pxt-adafruit#672]
https://makecode.adafruit.com/reference/serial

a few people so far have been confused
https://forums.adafruit.com/viewtopic.php?f=64&t=133073

**Comment by pelikhan** [comment]
@mmoskal @abchatra  should we call it HF2 as well? Maybe we should hide those blocks and rely on console.log instead.... since it is not the kind of serial communication one would expect typically.

**Comment by abchatra** [comment]
We have renamed the blocks. We should update the documentation. "Serial write line" Console.log now

**Comment by Jaqster** [comment]
I think it might be good to do a tutorial on how to use these blocks and show the Console screen as well.

**Comment by pelikhan** [comment]
I’ll add an article on learn.adafruit.com

________________________________
