### ISSUE TITLE
The content on "JavaScript" content pane is not clear

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#673]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta#editor
• Click "ADVANCED" -> "+EXTENSIONS" ->"keyboard"
• Then switching from "BLOCKS" mode to "{}JAVASCRIPT" mode
• Drag blocks in ToolBox "GAMEPAD" to JavaScript content pane

**Expect result:**
The content on content pane should be clear
![1235](https://user-images.githubusercontent.com/23466737/38078903-3d3ab236-332d-11e8-86c3-ef97d2269844.gif)

**Actual result:**
The content on content pane is not clear
(After switching to 'High contrast on' mode and then switching to 'High contrast off' mode again, it can shows clearly)
![1234](https://user-images.githubusercontent.com/23466737/38078918-442eae76-332d-11e8-935c-d154fad2f21a.gif)

**Comment by samelhusseini** [comment]
Well. So there is an issue here in that when you switch back from high contrast we don't re-load the theme for coloring...

What you're describing is a poor choice in the color of the category, perhaps we can do something to change the color slightly knowing that it's a dark toolbox, but ultimately it's a choice of color of the package. 

Won't fix for now, but will fix this issue with not returning the original coloring of text.

**Comment by samelhusseini** [comment]
Fixed in PR.
