### ISSUE TITLE
After switching to "BLOCKS" mode, the program didn't run

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#674]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta#editor
• Copy the below code on "JavaScript" pane and the click button A

let strip = light.createStrip()
input.buttonA.onEvent(ButtonEvent.Click, () => {
    strip.showAnimation(light.cometAnimation, 2000)
})

• Switch to "BLOCKS" mode and click button A again

**Expect result:**
After clicking button A, the program should run in "BLOCKS“ mode as in 'JavaScript' mode
**Actual result:**
After switching to "BLOCKS" mode, the program didn't run
![12347](https://user-images.githubusercontent.com/23466737/38081225-08a2934e-3333-11e8-8706-7b90576af9dd.gif)

**Comment by samelhusseini** [comment]
There's something funny going with the decompilation. @riknoll 

```
let strip = light.createStrip()
input.buttonA.onEvent(ButtonEvent.Click, () => {
strip.showAnimation(light.cometAnimation, 2000)
})
```

is decompiled into 
![screen shot 2018-04-24 at 9 16 41 pm](https://user-images.githubusercontent.com/16690124/39226047-ce0b54f0-4804-11e8-959d-3117b274e2ca.png)


and then back to
```
let strip: light.NeoPixelStrip = null
input.buttonA.onEvent(ButtonEvent.Click, function () {
    strip.showAnimation(light.cometAnimation, 2000)
})
strip = light.createStrip(pins.A1, 0)

```

hence why it's not running.

**Comment by samelhusseini** [comment]
Same issue here: https://github.com/Microsoft/pxt-adafruit/issues/626

**Comment by samelhusseini** [comment]
Another here: https://github.com/Microsoft/pxt-adafruit/issues/603

**Comment by samelhusseini** [comment]
Another dupe here: https://github.com/Microsoft/pxt-adafruit/issues/593

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-adafruit/commit/952869c15cbc33b16dd7f42c7c0f97da51e1f6ea
