### ISSUE TITLE
remove serial reference

### ISSUE THREAD

**Issue by ladyada** [Microsoft/pxt-adafruit#680]
this has been renamed console right?
https://makecode.adafruit.com/reference/serial
can this page be removed altogether

(customer request: https://forums.adafruit.com/viewtopic.php?f=64&t=133073#p662781)

**Comment by abchatra** [comment]
@ganicke can we remove these?

**Comment by abchatra** [comment]
We have console blocks documented here: https://makecode.adafruit.com/reference/console

**Comment by ganicke** [comment]
I suppose so since they no longer show as available blocks in the toolbox.

**Comment by pelikhan** [comment]
Let's keep. The serial blocks are back and they actually talk UART properly.

**Comment by abchatra** [comment]
test
