### ISSUE TITLE
These two blocks' shape are different

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#699]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta#editor
• Drag blocks as below .gif
• Drag block "create array with" and put it in block "length of array"
**Expected result:**
 The shape of block "create array with" should be same as the block "length of array"
**Actual result:**
 These two blocks' shape are different
![1](https://user-images.githubusercontent.com/23466737/39043703-9fbeab90-447d-11e8-8923-3b5c2b479978.gif)

**Comment by samelhusseini** [comment]
Fixed in master.
