### ISSUE TITLE
On Light Dark Reference doc error

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#707]
The doc for On Light Dark block shows the value from 0 to 1023 (instead of 0 to 255).
Also, I think the example code is fracked...
Galen, can you fix?
https://makecode.adafruit.com/reference/input/on-light-condition-changed

**Comment by ganicke** [comment]
Parameter ranges fixed in https://github.com/Microsoft/pxt-common-packages/pull/305.
