### ISSUE TITLE
After creating a new variable, the "Logic" flyout opened

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#710]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta#editor
• Click "VARIABLES" -> "Make a Variable" to make a new variable

**Expected result:**
After creating a new variable keeps the flyout open and shows the new variable in that flyout 
**Actual result:**
After creating a new variable, the "Logic" flyout opened
![1](https://user-images.githubusercontent.com/23466737/39614783-0674d35c-4f62-11e8-8c07-e73cbdc83eaa.gif)

**Comment by samelhusseini** [comment]
Good bug. Thanks!
