### ISSUE TITLE
The text is selected when opening "Extensions" window

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#711]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta#editor
• Click "EXTENSIONS" and then close this window
• Repeat the second step again

**Expected result:(Chrome,Firefox & IE)**
The text should not be selected when opening "Extensions" window
**Actual result:(Edge)**
The text is selected when opening "Extensions" window
![2](https://user-images.githubusercontent.com/23466737/39618726-8ff71a7e-4f74-11e8-876b-203710ed24e3.gif)

**Additional info:**
Adafruit Circuit Playground Express version: 1.1.14
Microsoft MakeCode version: 3.12.9
C++ runtime version: v0.2.2

Edge: 42.17134.1.0

**Comment by samelhusseini** [comment]
I don't repro. What browser / OS?

**Comment by Helen09** [comment]
The machine build is 17134.1.180410-1804.rs4_release.amd64fre.enterprise_en-us_vl
Edge version: 42.17134.1.0

**Comment by abchatra** [comment]
Doesn't repro anymore as we have a new UI
