### ISSUE TITLE
Set All Pixels to Black

### ISSUE THREAD

**Issue by jedgarpark** [Microsoft/pxt-adafruit#714]
If there isn't an alternative way to turn off all the on board NeoPixels it would be nice to add black to the color palette choices for the **Set All Pixels To**  node. I'm able to go to JavaScript and change the line to `light.setAll(0x000000)` but would like to be able to do that in the blocks as well.

This would make it more consistent with the **Show Ring** block which can set pixels to "off" (although they appear gray).

**Comment by pelikhan** [comment]
We have a fix in /beta 
![image](https://user-images.githubusercontent.com/4175913/39788109-a341a13c-52dd-11e8-8b5b-9ac1d7987c91.png)

**Comment by jedgarpark** [comment]
Terrific!

**Comment by abchatra** [comment]
fixed in beta
