### ISSUE TITLE
On TemperatureCondition.hot, reduce temperature, event is triggered 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#719]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Drag block as below .gif and click "Slow-Mo"
• Drag down the temperature

**Expected Result:**
 On TemperatureCondition.hot, reduce temperature, event should not be triggered
**Actual Result:**
 On TemperatureCondition.hot, reduce temperature, event is triggered. But drag down again it will not be triggered
![2276](https://user-images.githubusercontent.com/23466737/40227539-557a9672-5a7e-11e8-8f0b-9623af0f8b6b.gif)

**Comment by abchatra** [comment]
Event will be triggered as soon as you interact with the temperature bar (either increase or decrease). We don't trigger on start of simulator but when you interact it is already above 15 degrees. Better test is try cold on 15 or hot on 35
