### ISSUE TITLE
The block "up" button is gray and "down" button is green

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#725]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta#editor
• Click "ADVANCED" -> "EXTENSIONS" -> "mouse" to add it 
• Open "MOUSE" toolbox and drag block "mouse button right" to content pane

**Expected result:**
The block "up" button should be green and "down" button should be gray
**Actual result:**
The block "up" button is gray and "down" button is green
![4](https://user-images.githubusercontent.com/23466737/40355802-e96e0ece-5da6-11e8-8133-d5a0f3b1e519.gif)

**Comment by abchatra** [comment]
P3 won't fix
