### ISSUE TITLE
Level example is ignoring Y axis.

### ISSUE THREAD

**Issue by gearsincorg** [Microsoft/pxt-adafruit#726]
**Describe the bug**
From the code in the "Level" example, I would assume it's meant to be summing the abs value of the acceleration of two horizontal axes to determine if the board is near level.  

Instead, The code is processing the X axis twice, rather than the X and the Y..

if (Math.abs(input.acceleration(Dimension.X)) + Math.abs(input.acceleration(Dimension.X)) < 64) {

should be

if (Math.abs(input.acceleration(Dimension.X)) + Math.abs(input.acceleration(Dimension.Y)) < 64) {

**Comment by abchatra** [comment]
fixed
