### ISSUE TITLE
After dragging out the items block, it can't be put back

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#728]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta#editor
• Click "ADVANCED" -> "Arrays" 
• Drag "set list" blcok out and put it under "forever"
• Click "+" to add items and until it becomes a vertical column
• Drag items block out and put it back

**Expected result:**
After dragging out the items block, it should be put back
![compare1](https://user-images.githubusercontent.com/23466737/40605281-5c888638-6251-11e8-8e42-9e8e1deee5b3.gif)

**Actual result:**
After dragging out the items block, it can't be put back
![issue1](https://user-images.githubusercontent.com/23466737/40605179-00c8c4e8-6251-11e8-93c3-6fda6cd15380.gif)

**Comment by samelhusseini** [comment]
Known interaction issue, let's track it here: https://github.com/Microsoft/pxt-blockly/issues/51

Issue is input blocks use middle left as the point of connection, so with blocks that big, it's a little unintuitive to use the middle to connect, but if you do, it works.
