### ISSUE TITLE
Custom RGB not working in BLOCK mode

### ISSUE THREAD

**Issue by dalirium** [Microsoft/pxt-adafruit#732]
I cannot generate a custom color by just using block...
Your own 'Reference' material has the example.

visit:
https://makecode.adafruit.com/reference/light/rgb

Then follow the block sample to create a custom Yellow color (Cannot be done in block)
Luckily, the javascript is also provided and works fine:

**let strip = light.createStrip()
let myYellow = light.rgb(255, 228, 181)
input.buttonA.onEvent(ButtonEvent.Click, () => {
    strip.setAll(myYellow)
})**

But when you switch to block you get an error 
![image](https://user-images.githubusercontent.com/39774689/40736193-f3664a6a-6402-11e8-84b5-abf2c2157af1.png)

_"Argument of type 'string' not assignable to parameter of type 'number'."_

and the code stops working.

If i switch back to Javascript code here's what I see instead of what I had initally entered:

**let myYellow = 0
let strip: light.NeoPixelStrip = null
input.buttonA.onEvent(ButtonEvent.Click, function () {
    strip.setAll(myYellow)
})
strip = light.createStrip(pins.A1, 0)
myYellow = light.rgb("" + 0, "" + 190, "" + 210)**

All I want is to easily create a unique color using RGB

**Comment by Hovdekorp** [comment]
I have the exact same problem in both the online version and the APP.

**Comment by abchatra** [comment]
fixed in https://makecode.adafruit.com/beta . Fix will be released to live soon.
