### ISSUE TITLE
The website will crashed when opening example code in JavaScript mode

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#736]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Scroll down and open example code 
• For example: "Music" -> "Beat visualizer" and then click "Open Example"
• Click "{ }JavaScript" to switch to JavaScript editor

**Expected result:(Edge&Firefox&IE)**
The example code can be opened in editor successfully
**Actual result:(Chrome)**
The website will crashed when opening example code in JavaScript mode
![issue1](https://user-images.githubusercontent.com/23466737/41023783-e1e18c14-695c-11e8-8fb5-1592ce51b9d4.gif)

**Comment by Helen09** [comment]
**Additional info:**
Chrome Version: 67.0.3396.6

**Comment by samelhusseini** [comment]
I haven't been able to repro this on Chrome Version 67.0.3396.79 on Mac. 

Are you able to consistently repro? If so this is concerning.. @abchatra

**Comment by samelhusseini** [comment]
Looks like Chrome fixed this issue on 67.0.3396.79

Closing this.
