### ISSUE TITLE
Tutorial splash screen rendering issue

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-adafruit#753]
The first time you open a tutorial in the browser, the intro/splash screen only half disappears when you dismiss it.  Repro-ed on Siren & Magic Wand tutorials.

This is on Edge using 1280 x 1024 resolution.

![tutorial splash screen](https://user-images.githubusercontent.com/22108954/41177896-74f1ded2-6b1a-11e8-995a-fa6997712952.PNG)

**Comment by abchatra** [comment]
Should be fixed with new tutorial.
