### ISSUE TITLE
Function placeholder appears as a default value

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-adafruit#757]
Not sure if it's just me but the function placeholder appears like it's a default value. 
So clicking OK doesn't do anything (because there's nothing in the field), it's just a placeholder..

![screen shot 2018-06-08 at 1 23 19 pm](https://user-images.githubusercontent.com/16690124/41179338-3db0f20a-6b1f-11e8-9a26-2eed8b4ae4c3.png)

Repro steps: 
- Create a function
- Hit ok without editing anything

**Comment by Jaqster** [comment]
Yeah, this is confusing - we should create a function named "doSomething" when user clicks Ok

**Comment by peterblazejewicz** [comment]
That appears to be fixed

**Comment by samelhusseini** [comment]
Yep. I fixed this.
