### ISSUE TITLE
Default NeoPixel variable name

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#760]
We use "strip" as the default variable name.  But the process of instantiating a new NeoPixel strip is not clear.  Many times users will declare a different variable name, but "strip" is the default in all our NeoPixel blocks.

What if we included the Set variable block with the default strip name, and create strip block pre-populated in the NeoPixel drawer?  Like we do for Sprites?  This would be much more intuitive.

**Comment by pelikhan** [comment]
Good one. Fixed.
