### ISSUE TITLE
The example code is not clear

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#775]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click on "LIGHT" -> right click on block "show ring" -> open help tutorial
• Scroll down and click opening example code button 
**Expected result:**
The code should be clear
**Actual result:**
The code is not clear
![issue2](https://user-images.githubusercontent.com/23466737/41395830-979a02ec-6f9e-11e8-8cb2-3a410ae31ed4.gif)

**Comment by pelikhan** [comment]
All example have a black background which makes them unreadable.

**Comment by Helen09** [comment]
Closed by fixed
