### ISSUE TITLE
pause block adds __internal.__timePicker code in TS

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-adafruit#776]
Time picker in PXT shows __internal.__timePicker. TD_ID should be set on that block.. 

This is what I get if you add a pause block in your code.

```
forever(function () {
    pause(__internal.__timePicker(100))
})
```

**Comment by samelhusseini** [comment]
The change to move the timePicker to PXT has an issue, shim=TD_ID is not respected there..

**Comment by pelikhan** [comment]
Fixed in https://github.com/Microsoft/pxt/commit/724b7cf6ced99e1cb871d1b89ff198c7439c30fd

**Comment by pelikhan** [comment]
Fixed in beta.
