### ISSUE TITLE
Package "cable" & "storage" can't be addedd successfully

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#784]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click on "ADVANCED" -> "EXTENSIONS" -> click on these packages one by one

**Expected reuslt:**
Every package should be added successfully

**Actual result:**
Package "cable" & "storage" can't be addedd successfully

**Comment by abchatra** [comment]
These are by design. Package cable blocks are populated in an existing category. Cable blocks go to Network category and  Storage is typescript only api.
