### ISSUE TITLE
"About" pathway link is too long in document

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#785]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• Click on "Watch Timer" -> "Show Instructions" -> open this instruction
• Click on "About" to navigate to https://makecode.adafruit.com/about
• Observe the guide link on the top of the page
**Expected result:**
The guide link should be "Docs > About"
**Actual result:**
The guide link is "Docs > About > > About > About"
![12](https://user-images.githubusercontent.com/23466737/41902174-5610c850-7922-11e8-8650-46cf8af29dc7.gif)

**Comment by ganicke** [comment]
"Fixed" in #796.
