### ISSUE TITLE
Using Crickit Servo Pauses Music Playing

### ISSUE THREAD

**Issue by TheKitty** [Microsoft/pxt-adafruit#793]
**Describe the bug**
When using the new Crickit stepper move block, if music like the play sound block will pause while the stepper moves, then sound resumes.

**To Reproduce**
Use of program attached. Adafruit Crickit + Circuit Playground Express. Build as of 7/5/2018.

**Expected behavior**
That the stepper motor would move with a button press and any music would continue to play at the same time

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 
![image](https://user-images.githubusercontent.com/1911920/42390134-fe0bebe0-8118-11e8-940f-8822b8ee9fb4.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10 latest build
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 67.0.3396.99 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] N/A

**Additional context**
Timer conflict? Or something blocking?

**Comment by abchatra** [comment]
@TheKitty Can you try with pause instead of wait? Wait is blocking wait and pause gives control to other fibers.
![image](https://user-images.githubusercontent.com/6107272/42524027-319eda5e-8424-11e8-9e8b-49eaea412541.png)

**Comment by TheKitty** [comment]
Actually steppers require a brief pause, about 10-20 milliseconds between step movements. Most of my examples have moved to 10 milliseconds.

Pause is too limited for timing, it only has 6 or so allowed values. If pause could have more control over the time settings, I could use it instead of wait.

**Comment by abchatra** [comment]
You can type any value in pause. Don't have to use drop down

**Comment by TheKitty** [comment]
Seriously! Now I know. I'll test, it may take a day or two. Thanks!

**Comment by TheKitty** [comment]
Bug can be closed, maybe ensure wait is documented as a blocking time call? Thanks for your help.

**Comment by abchatra** [comment]
@ganicke Can we add to the documentation of wait information about it being blocking compared to pause (May be a section about comparison between pause & wait)? https://makecode.adafruit.com/reference/control/wait-micros

**Comment by ganicke** [comment]
Sure, I can get at that.
