### ISSUE TITLE
Mouse Extension Button Emulation Incorrect

### ISSUE THREAD

**Issue by TheKitty** [Microsoft/pxt-adafruit#798]
**Describe the bug**
The Mouse Extension for using Adafruit Circuit Playground Express - clicking right button sends left button click. sending left button click activates right button click

**To Reproduce**
Advanced - Extensions - Install Mouse over HID extension
Create the code shown below and download
When Button A is clicked it simulates the Right mouse button.
When Button B is clicked it simulates the left mouse button

**Expected behavior**
A should be left, B right - it appears in the code for pxt there may be a swap somewhere

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 
![image](https://user-images.githubusercontent.com/1911920/43277583-75d84872-90d6-11e8-82d9-99d73fce815a.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Chrome
 - Version Version 67.0.3396.99 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] N/A

**Additional context**

**Comment by pelikhan** [comment]
Fixed in https://github.com/Microsoft/pxt-common-packages/commit/13c9907d2e450a77228427e8ce2ecc06c2c27318#diff-a2076eda0b39eb85a091f46460508467
