### ISSUE TITLE
No help available for Mouse Extension blocks

### ISSUE THREAD

**Issue by TheKitty** [Microsoft/pxt-adafruit#799]
**Describe the bug**
When you try  to pull up help for the mouse extension blocks, help is greyed out and there is no help.

**To Reproduce**

**Expected behavior**
right click a Mouse block and if you click Help the right pane opens with standard block description, doc, and example(s)

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 67.0.3396.99 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] n/a

**Additional context**

**Comment by pelikhan** [comment]
@ganicke can you take a peek?

**Comment by ganicke** [comment]
Sure. It needs docs for the three blocks exposed.
