### ISSUE TITLE
When clicking in the text box, the text in text box doesn't disappear

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#802]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/beta
2. Click "Import" -> "Import URL..."
3. Click in the text box and then click on blank area

**Expected result(IE):**
When clicking in the text box, the text in text box should disappear
![compare80102](https://user-images.githubusercontent.com/23466737/43516559-7c3a9aee-95b8-11e8-89eb-c74cd0698e9e.gif)

**Actual result(Edge, Chrome & Firefox):**
When clicking in the text box, the text in text box doesn't disappear
![issue80102](https://user-images.githubusercontent.com/23466737/43517256-9ab4c48e-95ba-11e8-945e-2ce112adb0e1.gif)

**Comment by riknoll** [comment]
This is just the browser's behavior for input hints.
