### ISSUE TITLE
Decompiler bug: Problem with switching to blocks after coding in javascript

### ISSUE THREAD

**Issue by anahitagharai** [Microsoft/pxt-adafruit#803]
the "play sound" block turns gray after you code it in JavaScript and switch to Blocks. Decompiler bug

1. Go to javascript 
2. Code some random sound with the "play sound" in javascript
3. Switch to blocks
4. See error (play sound block is gray)

The code should have converted correctly and should be orange, not gray

 - OS: Windows
 - Browser: chrome

**Comment by abchatra** [comment]
I can' repro this for vaild input. Strings as input are not supported in blocks and you get gray blocks
