### ISSUE TITLE
Simulator shows wrongly when tilting simulator

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#805]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/beta#editor
2. Drag blocks as below .gif
3. Tilt simulator up or down

**Expected result:**
When tilting simulator up, it should show blue and tilting simulator down it should show yellow

**Actual result:**
When tilting simulator up, it shows yellow and tilting simulator down it shows blue
![issue80702](https://user-images.githubusercontent.com/23466737/43768878-f4bfd11c-9a6a-11e8-89ba-864c8b750763.gif)

**Comment by riknoll** [comment]
This is the correct behavior. The mouse is at the bottom of the simulator but the top of the board (the part with the USB) is tilting towards the user (up)

**Comment by kevinjwalters** [comment]
I've rediscovered this. I think this is mainly a _naming_ issue and will continue to create confusion as is: https://github.com/microsoft/pxt-arcade/issues/1190
