### ISSUE TITLE
There is no "Green Screen" mode on IE

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#814]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/beta#editor
2. Click "More..." and observe

**Expected result(Edge, Chrome & Firefox):**
There should have "Green Screen" mode on each browser
![issue815001](https://user-images.githubusercontent.com/23466737/44140975-59221ffe-a0ae-11e8-8379-da99d4f024b8.gif)

**Actual result:**
There is no "Green Screen" mode on IE
![issue815002](https://user-images.githubusercontent.com/23466737/44140963-52074a82-a0ae-11e8-84b9-53a919423557.png)

**Comment by riknoll** [comment]
I believe this is intentional
