### ISSUE TITLE
The simulator can't be loaded on IE

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#816]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/projects
2. Navigate to "Examples" and open any example such as "Blinky", "Animation Shaker"...
3. Scroll down the page and click "rectangle" button to run this example 

**Expected result(Edge, Chrome & Firefox):**
The simulator should be loaded on each browser 

**Additional info:**
IE version: 11.228.17134.0
Build: rs4_release.180410-1804.17131.1.amd64fre

**Actual result(IE):**
The simulator can't be loaded on IE
![issue81601](https://user-images.githubusercontent.com/23466737/44191731-289ad180-a15f-11e8-852e-2ad4f509f2a7.gif)

**Comment by pelikhan** [comment]
These samples are gone.
