### ISSUE TITLE
The few functions overlapped on content pane

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#817]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/beta#editor
2. Click "ADVANCED" -> "FUNCTIONS" -> "Make a Function" to make few new functions

**Expected result:**
The few functions should not overlap

**Actual result:**
The few functions overlapped on content pane
![issue82302](https://user-images.githubusercontent.com/23466737/44516034-96fb0900-a6f6-11e8-98b8-87c3ab937005.gif)

**Comment by abchatra** [comment]
P3 closing as wont' fix
