### ISSUE TITLE
Graph block docs confusing

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#821]
Hey Galen,
I'm finally going through Rob's maker curriculum, and his explanation of the Graph block is confusing. We actually changed this block to not show the max value field by default.  But the explanation and the examples in the docs is also complicated and confusing... https://makecode.adafruit.com/reference/light/graph.  
I wonder if you can take a pass at trying to simplify this explanation a bit?  And can we cover the most common scenarios for this block as examples - i.e. 
light.graph(input.acceleration(Dimension.X)).

**Comment by ganicke** [comment]
Ok, I'll redo the discussion a bit.
