### ISSUE TITLE
Graph block rendering weirdness

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#822]
On both Chrome and Edge, the expanded property in the Graph block is not displaying correctly...

![graphblock1](https://user-images.githubusercontent.com/22108954/44998869-d1259f80-af6d-11e8-8429-9a0b9b0bda0c.PNG)
![graphblock2](https://user-images.githubusercontent.com/22108954/44998871-d682ea00-af6d-11e8-9860-e70a59860183.PNG)

**Comment by abchatra** [comment]
I can repro this, need to add and remove acceleration block from the graph block to repro.

**Comment by pelikhan** [comment]
Fixed.
