### ISSUE TITLE
Microphone resets every 10 secs with Adafruit CPX

### ISSUE THREAD

**Issue by caternuson** [Microsoft/pxt-adafruit#832]
**Describe the bug**
Mic related code blocks seem to do some sort of auto recal every 10 seconds that creates unexpected behavior.

**To Reproduce**
Use an Adafruit Circuit Playground Express. Then, there are a couple of ways to show the issue. This one may be easiest to demonstrate:
https://makecode.com/_ivKbL1CoTgVJ
The louder the sounds, the more neopixels are lit. It initially works. Be quiet for more than 10 seconds. All or most of the lights will come on. Make a loud noise. They mostly go out (reset). 

The other example is the clap/light demo which uses `on loud noise`:
https://makecode.com/_MJ7KfeCyg731
Again, it initially works - clap or shout and the lights come on for 2 seconds. Be quiet for more than 10 seconds. The lights may suddenly come on. Or it no longer responds to loud noises. But will again after another loud noise.

**Expected behavior**
The mic has consistent behavior all of the time.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Jaqster** [comment]
Not sure if this is related, but I'm finding that the On Loud Sound block is not working at all.  It runs on start of the program, but then never again.

**Comment by pelikhan** [comment]
For the first example, add 255 to the argument count. It will set the max value used by the graph to scale.
```
light.graph(input.soundLevel(), 255);
```
If you don't provide this, the graph block automatically scales with a certain window of time so if you keep quiet for a time, the sound range shortens and you get "zoomed in" effect.

**Comment by pelikhan** [comment]
@Jaqster do you have a repro, on loud event works for me.

**Comment by Jaqster** [comment]
does it work consistently on hardware?  I find that it works the first couple times, then stops.

**Comment by pelikhan** [comment]
What program do you use?

**Comment by pelikhan** [comment]
Tested as fixed in v1.3.1 https://makecode.adafruit.com/beta
