### ISSUE TITLE
The email link is not a correct link on contact page

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#838]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/contact
2. Observe the email link on this page

**Expected result:**
The email link should be a link

**Actual result:**
The email link is not a correct link on contact page
 ![issue1010001](https://user-images.githubusercontent.com/23466737/46717211-9fed6d00-cc99-11e8-8745-1da013ffbb3c.PNG)

**Comment by abchatra** [comment]
This is intentional.
