### ISSUE TITLE
Maker Curriculum

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#839]
Finally done editing this!!!

All files uploaded here: https://1drv.ms/f/s!AvnYExTCocXPglRM7ZgoxKXgb-FT

Please go through this and review everything.  We should also make all the projects to validate too.

**Comment by ganicke** [comment]
Maker Curriculum added: https://makecode.adafruit.com/courses/maker

Related PR's:

#841, #853, #854, #855, #860, #861, #862, #871, #872, #876, #879, #884, #889, #891, #892, #893, #900, #903, #904, #906.
