### ISSUE TITLE
On "Fabric friend" code page, it shows "Sorry, the page is missing"

### ISSUE THREAD

**Issue by AimeeCao18** [Microsoft/pxt-adafruit#842]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/projects/fabric-friend
2. Scroll down to the bottom of the page
3. Click on "Code" to open the code

**Expected result:**
The code page should not be missing

**Actual result:**
On "Fabric friend" code page, it shows "Sorry, the page is missing"
![actual](https://user-images.githubusercontent.com/44188776/48333383-237fec80-e692-11e8-8045-8101e571b460.gif)

**Comment by ganicke** [comment]
Ah, need to remove that. It's part of the new 'Maker' course now.
