### ISSUE TITLE
Tutorial "Siren" doesn't have picture on IE

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-adafruit#846]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/beta
2. Scroll down scroll bar and observe tutorial "Siren"

**Expected result:(Edge, Chrome & Firefox & Windows App)**
Tutorial "Siren" should have picture on IE
![issue1113compare](https://user-images.githubusercontent.com/23466737/48399761-812e3a80-e75f-11e8-8d8c-6e327e0844cc.PNG)

**Actual result:(IE)**
Tutorial "Siren" doesn't have picture on IE
![issue111303](https://user-images.githubusercontent.com/23466737/48399777-87bcb200-e75f-11e8-9160-25df04b6d21c.PNG)

**Comment by ganicke** [comment]
OK, weird...lemme check it on IE...

**Comment by ganicke** [comment]
Can't repro this, more info please:

![image](https://user-images.githubusercontent.com/27789908/48654045-7a513300-e9be-11e8-922b-343606b026da.png)

**Comment by ganicke** [comment]
Wait, this happens in the current release:

![image](https://user-images.githubusercontent.com/27789908/48654095-f0559a00-e9be-11e8-865a-73cda9a0fac5.png)

Wait I'm testing off or HEAD.

**Comment by ganicke** [comment]
No, it's some IE vs. cloud problem:

![image](https://user-images.githubusercontent.com/27789908/48654433-a7ebab80-e9c1-11e8-97f7-1acb6bf86fb8.png)

**Comment by Helen09** [comment]
This bug repro on below beta vesion on IE:

Adafruit Circuit Playground Express version:  1.2.9
Microsoft MakeCode version:  5.1.5
codal-circuit-playground runtime version:  v1.5.6
