### ISSUE TITLE
"Go back" button is not clear enough

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#850]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/beta
2. Click "Import" -> "Import URL" -> copy link "https://makecode.com/_1Ke4oHf9wXd8" to open this project
3. Click "Show console Simulator" under simulator and then observe "Go back"

**Expected result:**
"Go back" button should be clear

**Actual result:**
"Go back" button is not clear enough
![issue1114003](https://user-images.githubusercontent.com/23466737/48470512-9ae98380-e82c-11e8-9db3-b389415a70f9.PNG)

**Comment by samelhusseini** [comment]
Dupe of https://github.com/Microsoft/pxt-adafruit/issues/843
