### ISSUE TITLE
Moving on block "on switch moved", short instruction is not clear enough

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#852]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/beta#editor
2. Click "INPUT" and move cursor mouse on block "on switch moved"
3. Observe the instruction for the block

**Expected result:**
The instruction should be clear enough

**Actual result:**
Moving on block "on switch moved", short instruction is not clear enough
![untitled2](https://user-images.githubusercontent.com/23466737/48474804-4f3bd780-e836-11e8-9557-401f3dda9570.png)

**Comment by ganicke** [comment]
Fixed in https://github.com/Microsoft/pxt-common-packages/pull/477. Next version of common packages.
