### ISSUE TITLE
Any multiplication in TS breaks decompilation

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#856]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/beta
2. Scroll down scroll bar and open example project such as "Dice", "Energy glove", "Egg game", "patience"
3. Observe the editor content pane

**Expected result(Edge, Chrome & Firefox & Windows app):**
The example project should not be empty on IE
![issue111501compare](https://user-images.githubusercontent.com/23466737/48526558-0d0ca780-e8c3-11e8-9454-a99569267e47.gif)

**Actual result:**
The example project is empty on IE
![issue111501](https://user-images.githubusercontent.com/23466737/48526550-0716c680-e8c3-11e8-8384-5e59d16e7410.gif)

**Comment by samelhusseini** [comment]
Issue here is Math.imul is not supported on IE, and we're using it in https://github.com/Microsoft/pxt/blob/28e192df12889f36015c8ed7c80c146d0b2cd0bd/pxtcompiler/emitter/hexfile.ts#L704

Fix is to polyfill imul for IE.

**Comment by pelikhan** [comment]
v1.2.3 should fix thi sissue.
