### ISSUE TITLE
An error occurred when opening the tutorials on IE

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#858]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/beta
2. Scroll down scroll bar to tutorials and open tutorials such as "Siren", "Magic Wand", "Clap lights",etc

**Expected result(Edge, Chrome & Firefox):**
Tutorial should be opened normally

**Actual result(IE):**
An error occurred when opening the tutorials on IE
![issue111503](https://user-images.githubusercontent.com/23466737/48537548-dcd9fe80-e8ec-11e8-9587-6cd2668c1836.gif)

**Comment by pelikhan** [comment]
Fix coming...

**Comment by pelikhan** [comment]
Dup of https://github.com/Microsoft/pxt-adafruit/issues/857
