### ISSUE TITLE
Error "Program Error: bad time start" shows when running this example code

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#863]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/beta#editor
2. Click "MUSIC" -> move cursor mouse on "ring tone" -> right click to navigate to help tutorial
3.  Copy the example to JavaScript content pane and click "start" button to run this example code

**Expected result:**
The program should can be run with no error

**Actual result:**
Error "Program Error: bad time start" shows when run this example code
![issue111601](https://user-images.githubusercontent.com/23466737/48602290-9dbfb200-e9ad-11e8-9de5-989e4896187a.gif)

**Comment by samelhusseini** [comment]
@abchatra
