### ISSUE TITLE
Except first block "digital Read", other "PINS" blocks don't have help tutorials

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-adafruit#864]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/beta#editor
2. Click "ADVANCED" -> "PINS" -> right click on blocks one by one to open help tutorial

**Expected result(Windows app):**
"PINS" blocks should have help tutorials as it on Windows app

**Actual result(IE, Edge, Chrome & Firefox ):**
Except first block "digital Read", others "PINS" blocks don't have help tutorials
![issue111602](https://user-images.githubusercontent.com/23466737/48606932-77a10e80-e9bb-11e8-98a7-88507bd072dc.gif)

**Additional info:**
Adafruit Circuit Playground Express version:  1.2.4
Microsoft MakeCode version:  5.0.4
codal-circuit-playground runtime version:  v1.5.4

**Comment by ganicke** [comment]
@riknoll, @samelhusseini - anyone know why the first attempt at context help to sidedoc fails and then after viewing the full document the sidedoc view works? Is this related to a necessary created instance of a pin?

![pins-sidedocs](https://user-images.githubusercontent.com/27789908/48655387-023d3a00-e9cb-11e8-942e-c2e3f62636a5.gif)

**Comment by ganicke** [comment]
Sidedocs open for Pins blocks with help...

![pin-side-docs](https://user-images.githubusercontent.com/27789908/60304691-02050580-98ef-11e9-943f-9dc7bd4b3795.gif)
