### ISSUE TITLE
 Locking with a basic program. 

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-adafruit#867]
**Describe the bug**
Locking with a basic program. 

```
input.buttonA.onEvent(ButtonEvent.Click, function () {
    light.showAnimation(light.rainbowAnimation, 500)
})
forever(function () {
    light.showRing(
    `white white white red red red red red red red`
    )
})

```

**To Reproduce**
1. Flash the above program
2. Click on button A
3. It runs the animation and then locks and doesn't return to the forever

**Expected behavior**
Don't lock. 

Repro's on beta but not master.

**Comment by abchatra** [comment]
@mmoskal @pelikhan is this related to compiler changes?
