### ISSUE TITLE
Max volume has been reduced in /beta

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-adafruit#881]
**Describe the bug**
This bug only affects beta but the max volume has been reduced (the whole thing is much quieter). 

**To Reproduce**
1. Try setVolume(256) on both beta and release and notice the difference on hardware

**Expected behavior**
Same behavior as release

**Comment by samelhusseini** [comment]
@mmoskal any idea what could be going on here? Was this code touched at all?

**Comment by pelikhan** [comment]
We changed the amp pin here: https://github.com/Microsoft/pxt-common-packages/commit/2e3ab195375de66909215d28d89e3429169a5d1f#diff-cbd245b705dd002eb55b88222b7aaf2f

**Comment by samelhusseini** [comment]
Do we need to update that somewhere?

**Comment by samelhusseini** [comment]
https://github.com/Microsoft/pxt-adafruit/blob/master/libs/circuit-playground/config.ts#L13
?

**Comment by samelhusseini** [comment]
Any other pin mapping that's changed?

**Comment by samelhusseini** [comment]
This is fixed.
