### ISSUE TITLE
Crash when using IR and onshake

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-adafruit#882]
**Describe the bug**
This is more of a reliability thing. Using the following code and shaking 10 times crashes the code. 
```
input.onGesture(Gesture.Shake, function () {
    light.setAll(Math.randomRange(0, 16777216))
    network.infraredSendNumber(Math.randomRange(0, 10))
})
```

**Comment by mmoskal** [comment]
It's the known timer issue. Need to upgrade to mbed-less codal-samd and re-test.

**Comment by pelikhan** [comment]
Tested on nombed as fixed.
