### ISSUE TITLE
Block "datalogger" label text is out of box on Firefox

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#910]
**Describe the bug**
 Block "datalogger" label text is out of box on Firefox

**Steps to reproduce the behavior**
1. Navigate to https://makecode.adafruit.com/beta#editor
2. Click "ADVANCED" -> "EXTENSIONS" -> click "datalogger" to add this extension

**Expected behavior**
![20181130](https://user-images.githubusercontent.com/23466737/49276237-dfc21b00-f4b8-11e8-8722-177024ab8549.PNG)

**Actual behavior**
Block "datalogger" label text is out of box on Firefox
![issue113001](https://user-images.githubusercontent.com/23466737/49276241-e3ee3880-f4b8-11e8-86ef-2b8361867368.gif)

**Desktop (please complete the following information)**
-  OS: Windows
-  Browser: Firefox(63.0.3)

**Comment by abchatra** [comment]
This is P3 won't fix
