### ISSUE TITLE
Maker Curriculum sample code

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#914]
Shouldn't the code snippet example on this page be using the Play Tone blocks (instead of the Ring tone)?
https://makecode.adafruit.com/courses/maker/general/coding/music
![music sample](https://user-images.githubusercontent.com/22108954/49537043-bddfe400-f87c-11e8-99cc-03b18eeb7c7c.PNG)

**Comment by ganicke** [comment]
Eh, oops. Corrected in #915.
