### ISSUE TITLE
Simple Crickit servo example freezes with neopixel 'error code'?

### ISSUE THREAD

**Issue by ladyada** [Microsoft/pxt-adafruit#924]
this one is something that got introduced recently perhaps. it definately didn't used to happen - moving a servo back and forth on crickit will crash and the neopixels on CPX will display a blue/red pattern (despite not having any neopixel code in the sketch)

see this post
https://forums.adafruit.com/viewtopic.php?f=64&t=144212

the code used to run before, now it doesnt run more than a few seconds
https://makecode.adafruit.com/94109-45880-18074-48992

- Adafruit Circuit Playground Express version:  1.2.9
- Microsoft MakeCode version:  5.1.5
- codal-circuit-playground runtime version:  v1.5.6

taggin' @jamesadevine because i saw you were doing a bunch of codal stuff, could be some mishandled i2c (crickit servos are fully handled over i2c)?

**Comment by jamesadevine** [comment]
@ladyada I'm working on hopefully making a more maintainable, less buggy build for CPX without mbed.

I did however take a cursory glance, and in the simulator I get a PANIC! 108 error message. If it's simulating this, there's a good change this will be happening on the real device.

Perhaps @pelikhan and @mmoskal could lend their thoughts?

**Comment by ladyada** [comment]
yes thank you for the CPX rewrite! it will be awesome

the PANIC is a known 'bug', due to the simulator asking over i2c for a version number and not getting a reply (since its, well, simulated) - that's not related. its odd because jp does not get this when he compiles the example, and i do... and we're running the same version. uf2's in the thread link above

**Comment by mmoskal** [comment]
The neopixel stuff is a panic message - it says `0x0000010100 == 20`. Panic 20 is out of memory.

**Comment by ladyada** [comment]
ok maybe its because im using firefox to compile? will try on chrome

**Comment by ladyada** [comment]
nope still doesnt work when i use chrome to compile. maybe cause im on window and he's on a mac? its really mysterious

**Comment by ladyada** [comment]
its definitely a browser-based thing
https://forums.adafruit.com/viewtopic.php?f=64&t=144212&p=714014#p714014

**Comment by jedgarpark** [comment]
This issue is coming up again https://forums.adafruit.com/viewtopic.php?f=64&t=145923 Happening for me on a Mac with Google Chrome 71.0.3578.98 (Official Build) (64-bit)

**Comment by caternuson** [comment]
Another one:
https://forums.adafruit.com/viewtopic.php?f=47&t=145851

I tested a recreated on Ubuntu 18.04.1 LTS with Firefox 64.0 (64-bit).

**Comment by caternuson** [comment]
https://forums.adafruit.com/viewtopic.php?f=58&t=146779

**Comment by ladyada** [comment]
@pelikhan @mmoskal @jamesadevine @Jaqster  hiya folks - this bug is making crickit tough to use in makecode cause servos is the first thing people want to use and it hard crashes after a few minutes. can we help in any way to get this bug squished?

**Comment by pelikhan** [comment]
Did a quick test on maker, and it seems that we are crashing earlier in there. 
https://makecode.com/_EDhcFa6REJh3

**Comment by pelikhan** [comment]
It seems that this is due to using SPI to drive the neopixels.

**Comment by ladyada** [comment]
are you using SPI DMA?

**Comment by pelikhan** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ladyada** [comment]
kk what about this demo from original post? doesnt have any neopixels in it
https://makecode.adafruit.com/94109-45880-18074-48992

**Comment by pelikhan** [comment]
@ladyada i am snowed in without a power supply for the crickit. Could you try this one? I disabled neopixels over SPI in the project settings. The light pattern is gone (and neopixels are still working).

https://makecode.com/_Uf0L7w27J496

**Comment by pelikhan** [comment]
Found a cable... servo is moving fine and no more neopixel noise with the fix. I will push it to beta.

**Comment by pelikhan** [comment]
Fix live in /beta. Make sure **v1.2.12** or higher is loaded (and this build is done https://travis-ci.org/Microsoft/pxt-adafruit/builds/489246261). @ladyada

**Comment by TheKitty** [comment]
Just tested with a real CPX and Crickit. No dice with beta 2.1.12. It runs the code for like 2 loops and on the third one it stops and displays neopixel pattern blue-blue-red-blue-red-5 blues.

Image of About box:
![image](https://user-images.githubusercontent.com/1911920/52306402-d5fbde80-2965-11e9-8ca0-553b9dc1a494.png)

**Comment by TheKitty** [comment]
I tried the javascript program @pelikhan an wrote on 1.2.11, it works
![image](https://user-images.githubusercontent.com/1911920/52307121-b960a600-2967-11e9-811b-39116e028b7d.png)

on 1.2.12, the javascript will not compile, error 
![image](https://user-images.githubusercontent.com/1911920/52307255-14929880-2968-11e9-8938-6d5d792524e3.png)

And the .uf2 does nothing

**Comment by TheKitty** [comment]
> @ladyada i am snowed in without a power supply for the crickit. Could you try this one? I disabled neopixels over SPI in the project settings. The light pattern is gone (and neopixels are still working).
> 
> https://makecode.com/_Uf0L7w27J496

This code does not compile, 3 errors. Taking an extra ) off the end takes it to one error but I cannt determine what that is

**Comment by pelikhan** [comment]
Just tried this sample and it worked for me on HW.
```
let index = 0
crickit.servo1.setAngle(0)
forever(function () {
    for (let index = 0; index <= 18; index++) {
        crickit.servo1.setAngle(index * 10)
        pause(100)
    }
    for (let index = 0; index <= 18; index++) {
        crickit.servo1.setAngle(180 - index * 10)
        pause(100)
    }
    pause(1000)
})
forever(function () {
    light.showAnimation(light.rainbowAnimation, 500)
})
```

**Comment by pelikhan** [comment]
@TheKitty you need to add the "crickit" extension.

**Comment by TheKitty** [comment]
That makes sense, just a sec

**Comment by TheKitty** [comment]
Adding the Crickit extension, your code works on 1.2.12 beta

**Comment by TheKitty** [comment]
I am retrying a block based program on the same make. The CPX will not go into bootloader mode. I will look to put circuitpython on it then put into bootloader mode then try a block program

**Comment by TheKitty** [comment]
Yes, right now, my CPX is essentially stuck running the javascript code. I cannot get into bootloader no matter what I try. Conferred with Limor.

**Comment by jedgarpark** [comment]
The issue (or some version of it?) seems to still be occurring in the example from [this forum post](https://forums.adafruit.com/viewtopic.php?f=64&t=145923&p=727995#p721291):
```
let notes: number[] = []
let i = 0
let open_angle = 0
let close_angle = 0
let lvl = 0
let angle = 0
/**
 * An example of playing two loops concurrently. This based on Snake Charmer Box and Jingle Bells With Red-Green Lights
 */
/**
 * Crashes shortly after beginning 2nd pin A1 touch!
 */
input.pinA1.onEvent(ButtonEvent.Click, function () {
    crickit.servo1.setAngle(close_angle)
    pause(100)
    move_servo_and_play_notes2()
})
function move_servo_and_play_notes2() {
    angle = open_angle
    i = 0
    while (angle > close_angle && angle <= open_angle) {
        if (i > notes.length - 1) {
            i = 0
        }
        if (notes[i] != 0) {
            music.playTone(notes[i], music.beat(BeatFraction.Half))
        } else {
            music.rest(music.beat(BeatFraction.Half))
        }
        angle = angle - 2
        crickit.servo1.setAngle(angle)
        pause(100)
        i = i + 1
    }
}
lvl = 32
close_angle = 30
open_angle = 150
notes = [262, 294, 311, 294, 262, 0, 262, 294, 311, 392, 294, 311, 262, 0, 0]
```
I wonder if this is due to the addition of sound to the mix?

**Comment by jedgarpark** [comment]
@pelikhan do you want to reopen this issue?

**Comment by pelikhan** [comment]
Oh boy... here we go again.

**Comment by jedgarpark** [comment]
Wheeeeee

**Comment by tavdog** [comment]
I'm seeing this issue when running a motor.  The code works for a few loops then crashes. Using CPX and Crickit with Adafruit geared motors.

**Comment by pambrose** [comment]
@tavdog If you are on OSX, make sure you are using Chrome and not Safari.

**Comment by tavdog** [comment]
Yes I am using Chrome on OSX 10.11.16

**Comment by danowall** [comment]
I'm seeing a crashing issue when I run the code below

https://makecode.adafruit.com/36105-40587-05667-52989

This is set up so that button presses trigger servos to move, it works for at most about a minute before crashing. There is no change to any onboard NeoPixels or LEDs when it crashes. I've noted the behavior is the same whether using the regular /#editor or /beta#editor suffix. It will always eventually crash independent of whether or not any buttons are pressed. 

Using Chrome on a Macbook Air running OSX 10.14.3
Code written with MakeCode version 5.1.5 for Adafruit Circuit Playground Express version 1.2.12

![screen shot 2019-02-21 at 6 32 45 pm](https://user-images.githubusercontent.com/4594264/53209076-431a9f80-3607-11e9-92fe-5d9f8c3ad4db.png)

![img_1988 2019-02-19 12_58_14](https://user-images.githubusercontent.com/4594264/53207922-16fd1f80-3603-11e9-86db-b7302daefb15.gif)

**Comment by pelikhan** [comment]
Investigating https://github.com/Microsoft/pxt-adafruit/issues/924#issuecomment-461688664

**Comment by pelikhan** [comment]
No lock observed on maker (using new CODAL) - https://makecode.com/_Dru2k6iayDgp

**Comment by ladyada** [comment]
one thing to really try a bunch is reading from the crickit, capacitive touch and the 8-pin 'I/O' port never worked :(

**Comment by pelikhan** [comment]
You mean capacitive touch from crickit?

**Comment by ladyada** [comment]
yep

**Comment by pelikhan** [comment]
@ladyada we don't have the bandwidth to test the crickit features. Looks like it is fixed on this end at least. Tested on the nombed branch.

**Comment by ladyada** [comment]
ok we can do the testing and report back! fingers crossed :)

**Comment by tavdog** [comment]
I will test to see if this fixes the crashes I've been seeing ? Is the fix live on makecode.com ?

**Comment by pelikhan** [comment]
@tavdog @ladyada @danowall @jedgarpark @TheKitty @jamesadevine all the fixes are available in https://makecode.adafruit.com/beta (v1.3.*)
