### ISSUE TITLE
Cartoon Network - Go Live stuff

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#937]
Here's the stuff that needs to go live for the Cartoon Network launch on Monday (1/7):

- [x] New Home Page banner (files at https://github.com/Microsoft/pxt-adafruit/tree/master/resources)
- [x] New "Cartoon Network" carousel on Home Page with project cards (let's put this on the first row for a few weeks, and then we can move it down)
- [x] Blog post - I'll work on a draft of this

**Comment by Jaqster** [comment]
Here are the files for the Blog post.  Feel free to edit.

[Cartoon Network Announce.docx](https://github.com/Microsoft/pxt-adafruit/files/2728472/Cartoon.Network.Announce.docx)
![makecode at cn](https://user-images.githubusercontent.com/22108954/50709802-ded35a80-101d-11e9-99c2-65403b0fc189.jpg)
![projectcards](https://user-images.githubusercontent.com/22108954/50709803-e135b480-101d-11e9-9178-0b6796b688fd.PNG)

**Comment by ganicke** [comment]
@abchatra added gallery and banner in #939

**Comment by ganicke** [comment]
CN stuff posted and live.
