### ISSUE TITLE
Add internal pull-up resistor support for Crickit Signal IO

### ISSUE THREAD

**Issue by jedgarpark** [Microsoft/pxt-adafruit#944]
The Signal IO ports currently can be read for digital IO, but require use of external pull-up resistors. Could we add support for enabling the internal pull-ups?

**Comment by pelikhan** [comment]
Do you have more details? There is the pins.....setPull(...) api

**Comment by pelikhan** [comment]
@jedgarpark does https://makecode.adafruit.com/reference/pins/set-pull work for you?

**Comment by jedgarpark** [comment]
Thanks, that works perfectly. Now, to hunt down the original request on the Adafruit forums : ]

**Comment by jedgarpark** [comment]
Oops, I misread that and only tested on CPX, my bad. Reopening while I test on Crickit.

**Comment by jedgarpark** [comment]
I don't know how I would use **set pull pin** for a Crickit Signal pin.

**Comment by pelikhan** [comment]
Oh, so that's really a request for the https://github.com/adafruit/pxt-crickit repo...

**Comment by jedgarpark** [comment]
Ah, yes. Looks like it exists there: https://github.com/adafruit/pxt-crickit/issues/11
