### ISSUE TITLE
Serial Redirect block only has two parameters missing Baud Rate

### ISSUE THREAD

**Issue by oumichaelm** [Microsoft/pxt-adafruit#947]
![screenshot 2019-02-12 13 24 31](https://user-images.githubusercontent.com/3843734/52662514-01cd1600-2eca-11e9-8787-9486ff5b7c78.png)

Seems the makecode block is missing the third argument to set the Baud Rate.

**Comment by pelikhan** [comment]
Fixed by https://github.com/Microsoft/pxt-common-packages/pull/743
