### ISSUE TITLE
There is an extra "> Projects" guide link 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#948]
**Describe the bug**
There is an extra "> Projects" guide link 

**Steps to reproduce the behavior**
1. Navigate to https://makecode.adafruit.com/projects
2. Observe the guide link on the top of the page

**Expected behavior**
The link should be "Docs > Projects"

**Actual behavior**
There is an extra "> Projects" guide link 
![issue22501](https://user-images.githubusercontent.com/23466737/53316967-be7c9980-3904-11e9-80dd-b6c3f0dbecfe.gif)

**Comment by abchatra** [comment]
Fixed
