### ISSUE TITLE
"crickit run motor" causes "PANIC! 108" 

### ISSUE THREAD

**Issue by darzu** [Microsoft/pxt-adafruit#950]
**Describe the bug**
Using "cricket run motor" block causes the editor to error out with Code 108.

**To Reproduce**
1. Open: https://makecode.com/_3rF5Yz6oh6Ka
2. Notice the panic

**Expected behavior**
Don't panic.

**Screenshots**
![image](https://user-images.githubusercontent.com/6453828/53921201-dcb66800-406f-11e9-8bc9-a373f7e6668e.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3 (18D109)
 - Browser Safari Version 12.0.3 (14606.4.5)
 - MacBook Pro 2018, i9, 32GB

**Comment by pelikhan** [comment]
Adafruit designed the library so that it fails hard if the i2c handshake fails. We should probably make it fail silently.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by darzu** [comment]
Does that mean no cricket programs work in the simulator?

**Comment by pelikhan** [comment]
Correct no simulator support for now. We don’t have a shield story really. Not crashing would be much better.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by darzu** [comment]
Some sort of "sorry, this code can't run in the simulator" error might be nice.
But shouldn't we be able to run the rest of the code (e.g. if there are some neopixel animations) regardless?

**Comment by pelikhan** [comment]
IMO we should silently ignore the failure. Or maybe blink the D13 LED.

**Comment by pelikhan** [comment]
This issue belongs to the https://github.com/Adafruit/pxt-crickit repo.
