### ISSUE TITLE
light sensor only reads value between 51 (e.g. 200) and 193 (eg ~800)

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-adafruit#954]
It seems that the sensivity of the light sensor has changed. It does not go near zero when covered or does not max when pointing a phone flash light.

**Comment by jamesadevine** [comment]
Hmmmm pretty sure I was seeing a far bigger range. Will take a look

**Comment by jamesadevine** [comment]
https://github.com/lancaster-university/codal-circuit-playground/releases/tag/v1.5.4-samd-peripherals.11

**Comment by pelikhan** [comment]
Nice work!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
