### ISSUE TITLE
Light levels problems in no-mbed (/beta) 

### ISSUE THREAD

**Issue by bborncr** [Microsoft/pxt-adafruit#956]
Light levels in the CPX are not calibrated correctly using the no-mbed code (/beta)
- Using finger to cover the light sensor = 44 (should be close to zero)
- Ambient light in my office = 59
- LED from phone = 194

I expect the values of the light sensor to be close to zero when the light sensor is covered and near the maximum (255?) when a bright light is shined directly on it.

If the light sensor does not go down close to zero then functions like graph() do not work properly.

**Comment by bborncr** [comment]
Duplicate issue already reported by @pelikhan

**Comment by pelikhan** [comment]
Your report was more detailed!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
