### ISSUE TITLE
"MUSIC" drawer doesn't show in toolbox of "Siren" tutorial

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#960]
**Describe the bug**
"MUSIC" drawer doesn't show in toolbox of "Siren" tutorial

**Steps to reproduce the behavior**
1. Navigate to https://makecode.adafruit.com/beta
2. Open tutorial "Siren" and click tutorial step one by one
3. When clicking to 5th step observe the toolbox

**Expected behavior**
"MUSIC" drawer should show in toolbox

**Actual behavior**
"MUSIC" drawer doesn't show in toolbox of "Siren" tutorial
![Issue318001](https://user-images.githubusercontent.com/23466737/54511037-8e1b9e80-498a-11e9-8982-760098945098.gif)

**Additional info:**
1. This bug repro on Edge, Firefox, Chrome & IE on Windows
(17763.1.amd64fre.rs5_release.180914-1434)

**Comment by pelikhan** [comment]
Requires to update the tutorial to reflect the new music blocks.

**Comment by pelikhan** [comment]
Waiting for release to fix.

**Comment by abchatra** [comment]
@ganicke we are planning to release this today. Sorry for the late notice. Is it possible to generate a PR for these tutorials. As soon as the release is done, we will merge the PR.
