### ISSUE TITLE
"MUSIC" drawer doesn't show in toolbox of "Magic wand" tutorial

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#961]
**Describe the bug**
"MUSIC" drawer doesn't show in toolbox of "Magic wand" tutorial

**Steps to reproduce the behavior**
1. Navigate to https://makecode.adafruit.com/beta
2. Open tutorial "Magic Wand" and click tutorial step one by one
3. When clicking to 4th step observe the toolbox

**Expected behavior**
"MUSIC" drawer should show in toolbox

**Actual behavior**
"MUSIC" drawer doesn't show in toolbox of "Magic wand" tutorial
![Issue318002](https://user-images.githubusercontent.com/23466737/54512112-18193680-498e-11e9-8ddd-2cdc9f3f1ae7.gif)

**Additional info:**
This bug repro on Edge, Firefox, Chrome & IE on Windows
(17763.1.amd64fre.rs5_release.180914-1434)

**Comment by Helen09** [comment]
This bug also repro on tutorial "Button flipper"'s 5th step, there is no "MUSIC" drawer in toolbox
![Issue318003](https://user-images.githubusercontent.com/23466737/54513311-046fcf00-4992-11e9-8763-a30f1f8c3b31.gif)

**Comment by pelikhan** [comment]
Requires updates to tutorial to match new music blocks.

**Comment by pelikhan** [comment]
Waiting for release to fix.

**Comment by abchatra** [comment]
@ganicke we are planning to release this today. Sorry for the late notice. Is it possible to generate a PR for these tutorials. As soon as the release is done, we will merge the PR.
