### ISSUE TITLE
There are duplicate 5th step in tutorial "room-sign"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#962]
**Describe the bug**
There are duplicate 5th step in tutorial "room-sign"

**Steps to reproduce the behavior**
1. Navigate to https://makecode.adafruit.com/projects/cartoon-network/room-sign
2. Scroll down to the 5th step and observe

**Expected behavior**
There should only one 5th step in tutorial "room-sign"

**Actual behavior**
There are duplicate 5th step in tutorial "room-sign"
![Issue318004](https://user-images.githubusercontent.com/23466737/54519796-51f43800-49a2-11e9-8a45-810a80e68a93.gif)

**Comment by Helen09** [comment]
This bug also repro on https://makecode.adafruit.com/projects/cartoon-network/bmo-music-box
The step is from step 4 turns to step 7
![Issue318006](https://user-images.githubusercontent.com/23466737/54523692-0eea9280-49ab-11e9-99c3-560872f8d9d3.gif)

**Comment by pelikhan** [comment]
@ganicke

**Comment by ganicke** [comment]
Well, that's an oops...will fix that.

**Comment by Helen09** [comment]
@ganicke This bug also repro on  https://makecode.adafruit.com/projects/cartoon-network/bmo-music-box

**Comment by ganicke** [comment]
Thanks @Helen09 I see the step order problem. Will fix.
