### ISSUE TITLE
Pins A1-A6 can't be clicked on simulator

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#963]
**Describe the bug**
Pins A1-A6 can't be clicked on simulator

**Steps to reproduce the behavior**
1. Open shared project https://makecode.com/_E0oAwYA1h3C6
2. Test program in the Simulator by clicking on each of the Pins A1 – A6 to see the colors change

**Expected behavior**
Pins A1-A6 should can be clicked

**Actual behavior**
Pins A1-A6 can't be clicked on simulator
![Issue318005](https://user-images.githubusercontent.com/23466737/54521328-ab119b00-49a5-11e9-969a-622114993520.gif)

**Additional info:**
This bug repro on Edge, Chrome(73.0.3683.75), Firefox(65.0.2) and IE(11.379.17763.0) on windows

**Comment by pelikhan** [comment]
Fixed.
