### ISSUE TITLE
No blocks image show in tutorial "Rube Goldberg" 3rd and 4th step

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#966]
**Describe the bug**
No blocks image show in tutorial "Rube Goldberg" 3rd and 4th step

**Steps to reproduce the behavior**
1. Open https://makecode.adafruit.com/projects/rube-goldberg/code
2. Scroll down this page and observe step 3 and step 4

**Expected behavior**
There should show blocks image
![compare319](https://user-images.githubusercontent.com/23466737/54593818-4d935200-4a6a-11e9-82a5-d7e6fd3ec865.PNG)

**Actual behavior**
No blocks image show in tutorial "Rube Goldberg" 3rd and 4th step
![Issue31902](https://user-images.githubusercontent.com/23466737/54593758-2472c180-4a6a-11e9-8b14-352bc7ffb3c8.gif)

**Comment by pelikhan** [comment]
@ganicke can you take a peek?
