### ISSUE TITLE
Issue on tutorial Rube Goldberg

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#967]
**Describe the bug**
Issue on tutorial Rube Goldberg

**Steps to reproduce the behavior**
1. Open https://makecode.adafruit.com/projects/rube-goldberg/code
2. Scroll down this page and observe step 3 and step 4

**Expected result:**
Tutorial should change the A0 in both "servo write pin" blocks to A2 because A3 can't be chosen 
![Issue319002](https://user-images.githubusercontent.com/23466737/54595016-c85d6c80-4a6c-11e9-8a05-abdb30131cb7.gif)

**Actual result:**
Issue on tutorial Rube Goldberg
![Issue31901](https://user-images.githubusercontent.com/23466737/54595714-2474c080-4a6e-11e9-97ed-802b510741a1.PNG)

![Capture11](https://user-images.githubusercontent.com/23466737/54595573-de1f6180-4a6d-11e9-811d-c0c6d0cf6694.PNG)

**Comment by Helen09** [comment]
The 4th step also need to be updated
![Issue3190001](https://user-images.githubusercontent.com/23466737/54595851-70276a00-4a6e-11e9-97eb-632f30262cb9.PNG)

**Comment by pelikhan** [comment]
@ganicke can you take a peek?
