### ISSUE TITLE
There are duplicate 3rd step in tutorial "musical-cloud"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#976]
**Describe the bug**
There are duplicate 3rd step in tutorial "musical-cloud"

**Steps to reproduce the behavior**
1. Navigate to https://makecode.adafruit.com/projects/musical-cloud/code
2. Scroll down to the 3rd step and observe

**Expected behavior**
There should only one 3rd step in tutorial "musical-cloud"

**Actual behavior**
There are duplicate 3rd step in tutorial "musical-cloud"
![Issue32001](https://user-images.githubusercontent.com/23466737/54656327-1ff8e800-4b00-11e9-9a9b-49ca4dbbfb75.PNG)

**Comment by pelikhan** [comment]
@ganicke

**Comment by ganicke** [comment]
Aey, this seems epidemic. ``pxt checkdoc --validate-steps``. Just kidding.

**Comment by Helen09** [comment]
Closed as fixed
