### ISSUE TITLE
A "twinkle" variable from "variables" can't be put into "play sound"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#985]
**Describe the bug**
A "twinkle" variable from "variables" can't be put into "play sound"

**Steps to reproduce the behavior**
1. Navigate to https://makecode.adafruit.com/projects/musical-cloud/code
2. Follow the step to drag blocks on content pane
3. Until the 4th step, as shared project
https://makecode.com/_FWRUhkY3tgj4

**Expected behavior**
Drag a "twinkle" variable from "variables" into the "play sound" where is says "power up"
![Capture](https://user-images.githubusercontent.com/23466737/55459419-1acc8a80-5622-11e9-8e44-ecaacf213ad1.PNG)

**Actual behavior**
A "twinkle" variable from "variables" can't be put into "play sound"
![Issue40301](https://user-images.githubusercontent.com/23466737/55459430-1e601180-5622-11e9-8fdd-a84602c1e0bf.gif)

**Additional info:**
1. test OS: Windows
2. Adafruit Circuit Playground Express version:  1.4.7
    Microsoft MakeCode version:  5.5.37
    codal-circuit-playground runtime version:  v1.5.4-samd-peripherals.11

**Comment by pelikhan** [comment]
I think this is more of a block definition issue.

**Comment by ganicke** [comment]
The situation is that this project wants to compose a sound and uses the now deprecated **playSound** block. The new melody blocks don't support a custom sound string. 

The new **play** block has he exact same text as **playSound**. So, the coding steps won't work with the available blocks. We'll need to get rid of the "twinkle" sound or have the user to stay in JS only.

```typescript
let twinkle = ""
music.playSound(twinkle)
music.baDing.play()
```

![image](https://user-images.githubusercontent.com/27789908/56385441-f81aa400-61d3-11e9-8f96-12ceb3bd303b.png)

**Comment by pelikhan** [comment]
The customizable api was nice. This is an issue.

**Comment by ganicke** [comment]
Maybe a melody editor, makes one byte notes packed into `Buffer`... sometime later, over the horizon.

**Comment by pelikhan** [comment]
It perfectly acceptable to instantiate a new Melody and play it. We should have a block that takes a string.

**Comment by ganicke** [comment]
Yea, maybe add a helper to create it that takes a string: `let song = createMelody("e:2 b:4")`?

**Comment by pelikhan** [comment]
Will not work with fixed instances...

**Comment by ganicke** [comment]
Change melody up a bit to do...

```
//% fixedInstances
export class StaticMelody extends Melody {
}

export class ComposedMelody extends Melody {
}
```

...except compile the melody on create rather than in `play()` in order to not retain the bulky melody string.

**Comment by abchatra** [comment]
@ganicke we are planning to release this today. Sorry for the late notice. Is it possible to generate a PR for these tutorials. As soon as the release is done, we will merge the PR.

**Comment by abchatra** [comment]
Hmm ignore my comment. I don't know what we can do here.

**Comment by ganicke** [comment]
OK, I'm fixing the others now...
